Theano/Theano

- theano/tests/record.py
- theano/tests/test_record.py
I moved the file to Theano and fixed its PEP8 style. Everything seems to work. 
I hope by adding the file to the "tests" directory the testing framework will pick it up automatically. 
However, we don't have any test to check the formatting of Theano files (like test_format.py in Pylearn2), but maybe we should have it at some point?
- Julian
> Fixed #2071: Moving test_record.py from Pylearn2 to Theano.

- doc/install_ubuntu.txt
Includes full documentation on how to build an *optimized* Numpy/SciPy/Theano on current Ubuntu LTS (14.04), including the BLAS dependencies (and configuration). I've tested the code under Kubuntu 14.04 (Ubuntu derivative) for the git code path, but haven't actually tested the pip-install path. That said, I haven't actually tried with a clean install, I expect we are actually missing such things as build-essentials or the like, though that's not likely to be a problem for readers of the docs for Theano.
> Document steps required to get Theano up-and-running on Ubuntu LTS (optimized)

- theano/scalar/basic.py
- theano/scalar/tests/test_basic.py
Hi @dwf ,
Here I just handle output[0] of a FunctionGraph in a Composite.
I'm now sure how should I print multiple outputs.
I'm still struggling with a good test file. The only thing I found is this test:
import numpy
import theano
def detect_nan(i, node, fn):
for output in fn.outputs:
if numpy.isnan(output[0]).any():
print '*** NaN detected ***'
theano.printing.debugprint(node)
print 'Inputs : %s' % [input[0] for input in fn.inputs]
print 'Outputs: %s' % [output[0] for output in fn.outputs]
break
x = theano.tensor.dscalar('x')
f = theano.function([x], [theano.tensor.log(x) * x],
mode=theano.compile.MonitorMode(
post_func=detect_nan))
f(0)
> now pretty print works for scaler variables too.

- theano/misc/strutil.py
- theano/tensor/nnet/ConvGrad3D.py
- theano/tensor/nnet/ConvTransp3D.py
Removing the space in front of the comma seems necessary for python's
2to3 tool to recognize that instance, no kidding.
An alternative to `theano.tensor.nnet.Conv3D` would be `.Conv3D`, but it's slightly inferior iirc; probably doesn't matter here though.
I also did `import theano` on 2.x and that "test" passed.
> Python 3.x compatibility.

- theano/gof/tests/test_graph.py
Unit tests read __count__ value instead of setting it
Note: this is just to have no side effect in the tests. No news.
> Autoname fix unit tests

- theano/gof/op.py
This PR does the following : 
-fixes false positives in the detection of old section markers
-add an error message specific for the case where no section marker has been detected in the code
-add an error message specific for the case where both types of section markers have been detected in the code
-adds to the section that processes the old syntax checks that were only present in the section for new syntax
-adds a few comments
> COp conflict between old section markers and new section markers

- theano/sandbox/cuda/nvcc_compiler.py
instead of being passed to -Xlinker.
These are necessary to compile on Windows, at least in the case
where more than one version of visual studio's cl.exe are available.
> Update the whitelist of flags passed directly to nvcc

- theano/compile/ops.py
- theano/sandbox/cuda/dnn.py
A PR introduced the shape_to_shape_i opt in the GPU opt. But this cause this opt to get called too often with the default equilibrium max_use_ratio.
We fix this. This caused tests like theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py:test_full to raise errors.
I think it is bad for opt to introduce to ugly graph as this cause too much work for the optimizer. This allow optimizer to introduce less work for futur optimizer.
> Fix equilibrium opt error recently introduced

- doc/tutorial/debug_faq.txt
- theano/compile/debugmode.py
- theano/compile/function_module.py
- theano/compile/monitormode.py
- theano/gof/link.py
- theano/gof/op.py
- theano/tensor/tests/test_basic.py
Also, do not store the stack trace on the Apply node. We already do this on the variable.
It is better to do it on only the variable then only the nodes. This allow to track the user created variables too with the same mechanism. As most op have only 1 output, we do not generate much more trace then doing the trace on node + user created var.
> Fix tests, crash and clean up

- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/basic_ops.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_opt.py
- theano/tensor/basic.py
As discussed here (towards the end):
https://groups.google.com/forum/#!searchin/theano-users/GpuSplit/theano-users/ZDuZkFvnEfI/eNe-NuZJibMJ
GpuSplit needs to be ported to the new GPU backend.  This adds the GpuSplit op and an accompanying optimization.  
I had to change the `perform` method in the Theano basic tensor `Split` class. It was calling `__getitem__` on `x` with a list argument which caused a `NotImplementedError` when `x` was a CudaNdarray.  So, I'm converting the index arg to a tuple first.  Thanks to @f0k for this.
This is my first op so please let me know if there's anything I'm doing wrong!  I got a lot of help on this from @f0k and @benanne.
> Adding GpuSplit op to cuda submodule

- theano/tensor/opt.py
`get_idx_list` is imported in tensor/opt.py, but it was sometimes called via `theano.tensor.subtensor.get_idx_list(...)`.
> Inconsistent function call of imported get_idx_list

- theano/configdefaults.py
- theano/gof/op.py
- theano/gof/type.py
- theano/gof/utils.py
- theano/tensor/basic.py
fix gh-1372
Also make sure to get the stack trace when calling theano.tensor.tensor()
Here is an example of the error message.
```
nouiz@Nouiz-lap-ub:~/src/Theano$ THEANO_FLAGS=compute_test_value=raise python test_222.py 
File "test_222.py", line 11, in <module>
T.dot(x, y)
File "/home/nouiz/src/Theano/theano/tensor/basic.py", line 4759, in dot
return _dot(a, b)
File "/home/nouiz/src/Theano/theano/gof/op.py", line 517, in __call__
storage_map[ins] = [self._get_test_value(ins)]
File "/home/nouiz/src/Theano/theano/gof/op.py", line 454, in _get_test_value
ret = v.type.filter(v.tag.test_value)
File "/home/nouiz/src/Theano/theano/tensor/type.py", line 131, in filter
raise TypeError(err_msg, data)
TypeError: For compute_test_value, one input test value do not …
```
> Better error message when the test_value do not have the right type

- theano/tensor/signal/downsample.py
- theano/tensor/signal/tests/test_downsample.py
> max_pool_2d stride support

- theano/sandbox/cuda/blas.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_blas.py
This PR adds the GpuDownsampleFactorMaxGradGrad GPU Op which is a fast version of downsample.DownsampleFactorMaxGradGrad, which currently performed in pure python. I've added optimization and a test.
Also I corrected  bug in the tests of test_blas. Some tests would fail because enabling cuDNN by default would prevent Ops like GpuDownsampleFactorMaxGrad from being inserted.
> Added GpuDownsampleFactorMaxGradGrad

- theano/gof/fg.py
- theano/gof/type.py
- theano/sandbox/cuda/type.py
- theano/sandbox/gpuarray/type.py
- theano/tensor/type.py
This should eliminate the "we discovered a broadcastable dimension during optimizations and therefore it breaks" problem.
> Add a way for almost-equal types replacements to be patched over automatically.

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
I added `AdvancedSubtensor1` support for the `local_useless_subtensor` optimization where the following cases are optimized:
* `x[[0,1,...,#rows(x) - 1]] -> x` with a constant vector
* `x[T.arange(x.shape[0])] -> x`
I'm not sure if there is an `AdvancedSubtensor` case, too. The only one I could imagine would be `x[[0,0,...,1,1,...,#rows(x),#rows(x),...], [0,1,...,#cols(x),0,1,...,#cols(x),...]].reshape((#rows(x), #cols(x))` given `x` is a matrix (could be generalized for all tensors). Is this worth the effort? It seems like a very unlikely case, but I could do it if you feel it should be included. What I'm no clear about, though, is if that's actually a case for this optimization because the `AdvancedSubtensor` op will give a vector in any case. Only combined with `reshape` will this be a …
> AdvancedSubtensor1 support for local_useless_subtensor optimization

- theano/scan_module/tests/test_scan.py
This PR modifies the test to rely on a simpler graph and avoid structures which slow down the optimization phase considerably. The new test fails in the same way as the original did before PR #1614 fixed the corresponding bug.
The original test was timed by @sebastien-j to take ~2 hours in DebugMode (don't know if it was timed with patience=3 or patience=default). It now takes ~2 minutes in DebugMode with patience=3.
> Update test_hessian_bug_grad_grad_two_scans to run faster

- theano/tensor/nnet/nnet.py
- theano/tensor/opt.py
- theano/tensor/type.py
Over at pymc-devs/pymc3#660, we're running into a pickling error during parallel sampling that is solved by moving a few Theano static methods to top-level functions.
Do these changes look OK on your end?
> Move values_eq_approx_remove* methods to functions

- doc/library/config.txt
- theano/gof/op.py
- theano/sandbox/cuda/cuda_ndarray.cu
- theano/sandbox/cuda/cuda_ndarray.cuh
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/dnn_fwd.c
The selection is currently based on a textual description of the amount of working memory that can be tolerated.
It would be possible to make it work with the cudnn 'FASTEST' and 'WORKSPACE_LIMIT', but it seem like the interface would get too confusing and hard to use.
> Enable algorithm selection in cudnn convolution

- theano/tensor/basic.py
- theano/tensor/opt.py
- theano/tensor/subtensor.py
Refactor local_useless_subtensor to allow earlier exiting of the function
Add a parameter to Subtensor.get_constant_idx() to prevent calls to get_scalar_constant_value() which can result in constant folding.
With this modification, in FAST_RUN, the optimization phase in test_scan.py:T_Scan.test_hessian_bug_grad_grad_two_scans goes from ~6 minutes to ~4 minutes.
> Speed up local useless subtensor

- theano/tensor/signal/downsample.py
- theano/tensor/signal/tests/test_downsample.py
the grad is not right now...working on it
> support max pooling with padding

- theano/gof/cmodule.py
Under python 3.0, the string is interpreted as unicode so the interpreter complains a poorly specified \uXXXX character and sees \x86 as a single character specified by its hexadecimal value.
> Escape backslashes in windows path string

- theano/scan_module/tests/test_scan.py
- theano/tensor/tests/test_subtensor.py
Those tests were passing on Travis, the first one because it is tagged "slow", the other one because it only happens with some seeds.
> Fix few tests for the nightly buildbot

- benchmark/autoencoder/aa.py
fix the import error for autoencoder benchmark
> Update aa.py, theano.sandbox.wraplinker seems not exist.

- theano/sandbox/cuda/blocksparse.py
- theano/sandbox/cuda/cudnn_helper.h
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/dnn_fwd.c
- theano/sandbox/cuda/dnn_gi.c
- theano/sandbox/cuda/dnn_gw.c
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/opt_util.py
- theano/sandbox/cuda/tests/test_blocksparse.py
- theano/sandbox/cuda/tests/test_dnn.py
Add alpha param and an inplace option.  'alpha' is not supported in cudnn v1 so we disable optimizations that would set it to something other than 1 with that version.
This may be missing a test for the merging optimizations.
> Allow dnn convolution to work inplace

- theano/sandbox/cuda/opt_util.py
`theano.sandbox.cuda.opt_util.grap_cpu_scalar` failed due to the missing `host_from_gpu` import. This caused the `local_dnn_conv*_alpha_merge` optimizers to fail.
> Add missing `host_from_gpu` import to `cuda.opt_util`

- theano/scan_module/scan_op.py
A user reported a test case not working with Scan on gpu. This is probably overkill but it fixes the bug and gives us time to investigate.
> Set borrow=False for scan inner inputs

- theano/tensor/basic.py
I added C code to the `Flatten` op. @lamblin mentioned in another PR that it is desirable to avoid multiple C code variants per op. The current implementation is parameterized by `outdim` which will cause a precompiled module per `outdim` value. There are two options: 1) `outdim` remains a constructor argument but is fed to the `Apply` node in `make_node`. Thus, `outdim` would still have to be a constant value and it could be checked in `make_node` as it's done now. 2) `outdim` could become a proper input of the `Flatten` op which means it could change during runtime. It's probably a rare case that someone actually wants to do this. Then, the sanity checks in `make_node` would not be possible anymore in the general case. Which variant do you guys prefer?
> Flatten C code

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
Fixes #2594. As far as I can tell, the bug relied is that the code relied on self.get_input_pos(), which gives indices of **inner** inputs and used the results as if they were indices of **outer** inputs.
This fixes the bug that was raised on the theano-users mailing list but I am not sure it fixes every issue that could come up with connection_pattern. I have the impression (but I'm not 100% certain) that the code relies on the number of inner outputs and outer outputs being the same to work (mainly lines 1413-1417 after my changes) which is not guaranteed. Could one of @lamblin or @abergeron have a look and tell my what you think.
> Fix connection_pattern and add test

- theano/gof/cmodule.py
This fixes the "-m32" not found error on Raspberry Pi 2, when importing
theano.
> Fixes "-m32" not found error on Raspberry Pi 2

- theano/gof/cc.py
MethodNotDefined is called from utils module in all other places in the file except here. I had my program crashing here, and when I changed it to utils.MethodNotDefined it was fixed.
> Minor fix in gof/cc.py

- theano/sandbox/cuda/tests/test_extra_ops.py
- theano/sandbox/cuda/tests/test_mlp.py
- theano/tests/unittest_tools.py
Also improves AttemptManyTimes to keep intact the name of the test in the event of a test failure.
Fixes #2047
> Apply decorator for stochastic tests on test_run_nnet

- theano/gof/compiledir.py
This has been found to help for running jobs on Helios. Multiple jobs try to create the same file at the same time, and this creates some conflicts and leads to jobs failing. This code can prevent that to a large extent.
> Fix in compiledir

- theano/scan_module/scan_op.py
Alter the method connection_pattern() in Scan to avoid calling the function grad() repeatedly. This aims to break the cycle that occurs with nested Scans where which calling scan.grad() will call connection_pattern() which will call tensor.grad() which will eventually call scan.grad() on the nested Scans.
> Scan connection pattern

- theano/sandbox/cuda/basic_ops.py
This also fixes the failure in
`theano/sandbox/cuda/tests/test_memory.py`,
which was due (somehow) to the use of perform rather than C code.
> Re-enable C code for GpuAlloc

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
The crash would occur in scan.infer_shape() when using the an until() condition as well as random number generation.
> Fix crash in scan.infer_shape() and add test case.

- theano/sandbox/cuda/extra_ops.py
- theano/sandbox/cuda/tests/test_extra_ops.py
- theano/tensor/extra_ops.py
- theano/tensor/tests/test_extra_ops.py
When a negative axis is provided to `GpuCumsumOp`, `CumsumOp` or `CumprodOp`, it will be converted to its positive equivalent (inferred from the given input array). 
Since the axis conversion happens during ~~the making of the node~~ the generation of the C code, two `cumsum` nodes created using a 2D array and respectively `axis=1` and `axis=-1` ~~will~~ won't be equivalent (their hash ~~will~~ won't be the same).~~
Closes #2715 
Edit: Saying two `cumsum` nodes with different axis may be equivalent was based on a wrong assumption.
> Added support for negative axis in GpuCumsumOp

- doc/library/tensor/signal/downsample.txt
- theano/gof/op.py
- theano/gof/opt.py
- theano/sandbox/cuda/basic_ops.py
- theano/sandbox/cuda/tests/test_basic_ops.py
This can cause optimization to be disabled as we won't be able to work in place as planned.
This also cause optimization error, as sometimes we try to merge 2 of them, but some complex reason, the new one do not have the same broadcast pattern as the original.
A few other small stuff at the same time.
> Disable GpuAllocEmpty merge

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
In `scan.connection_pattern._get_inner_outs_idx()`, the indices related to the first mitmot would get counted twice. This PR also adds a test for this crash.
> [CRASH] Fix crash in connection_pattern when there are mitmots

- doc/tutorial/python-memory-management.txt
Updates documentation about internal Python memory management as described in #2652:
* Adds `list(...)` in code example to get similar results with python3
* Add note that results may different for different python versions and platforms
* Rewrites section to make it more clear
> Updates doc about internal memory management

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
Based on the code and comments, the implementation of scan.connection_pattern appears to confuse inner and outer outputs. The method `get_input_pos()`, means to receive the index of an *inner* output is called with the indices of *outer* outputs. This means that if the scan has mitmot outputs with many output taps, some of its recurrent outputs might never be processed.
I tried to come up with a test case for this but couldn't find one where there would be a measurable, observable difference between the connection_pattern before this PR and after. I have a test case which I haven't included where the code behavior is different but the final connection_pattern is identical.
> Stop confusing inner and outer outputs in connection_pattern()

- theano/gof/op.py
One character typo: the variable is called `self.func_files`, not `self.fun_files`. Only shows up if you have a C file with an invalid section (like `#section suport_code`).
> Fix fun_files->func_files typo in error handler for COp unknown sections

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
Removed assertion for non-symbolic `reps` in `tensor.tile`,
and extended the unit test for this case.
Addresses #2695.
> Accept symbolic `reps` in `tensor.tile`

- theano/tensor/extra_ops.py
- theano/tensor/nlinalg.py
- theano/tensor/tests/test_extra_ops.py
- theano/tensor/var.py
Added `numpy.compress` to the `theano.TensorVariable` interface, including unit tests.
Ref. issue #1080
There is one problem with the implementation at the moment... which I haven't been able to resolve on my own.
Namely, it is that I cannot estimate the shape of outputs.
The input into `compress` is a vector of bools which represents whether an element/slice should be retained in the output, as well as the matrix being operated on.
I cannot retrieve the dimension of the condition vector.
Any advice/help would be appreciated.
> Add numpy.compress to theano.tensor

- theano/sandbox/gpuarray/basic_ops.py
Fixes test `test_scan.py:T_Scan.test_cuda_gibbs_chain` under the new back-end.
> Add missing arguments to GpuKernel_init

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Reported by "Peter Le Bek" in "[theano-users] Different gradient behaviour 0.6.0 vs 0.7.0"
This is a regression since Theano 0.6 that was introduced in commit 64d621b45756e6c1f1e8df5dac0a6d75a9d16b6b
> [REGRESSION] Fix nan 

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Since the node is removed, it can hide errors (like when splits[0] != x.shape[axis]), I supposed it's an acceptable behavior for optimizations.
> Add an optimization that remove Split with only 1 split. (Close #2545)

- theano/scan_module/scan_utils.py
Usage of toposort is replaced by parallel depth-first exploration of the two computational graphs. For Kratarth's use case (which admittedly uses huge scans) , it made calls to equal_computations roughly 200x faster.
I launched all the tests in scan_module/tests/, comparing the output between the old version of `equal_computations()` and the new. They agreed in all cases except in test case test_grad_multiple_outs_some_uncomputable on the graph : 
`[RandomFunction{uniform}(<RandomStateType>, TensorConstant{[]}, TensorConstant{-1.1}, TensorConstant{1.1}), Elemwise{mul,no_inplace}(TensorConstant{2}, u2[t]), RandomFunction{uniform}(<RandomStateType>, TensorConstant{[]}, TensorConstant{-1.1}, TensorConstant{1.1}), dot(u1[t], win_copy), DimShuffle{x}(RandomFunction{uniform}.1), …
> Remove dependance on io_toposort in equal_computations()

- theano/sandbox/gpuarray/opt.py
The previous implementation would crash if `node.inputs[0].owner` was None (which happened during some scan unit tests).
> [CRASH] add check to ensure that first input is HostFromGpu in gpuarray/local_assert

- theano/sandbox/gpuarray/subtensor.py
`*start` and `*stop` are `ssize_t` and `len` is `size_t`. When either `ssize_t` is below 0, is will automatically be cast to `size_t` for the comparison and will thus appear to be incredibly large, making the check pass even if it shouldn't.
> [CRASH new backend] Fix comparison between ssize_t and size_t

- theano/scan_module/tests/test_scan.py
This would make test work on cpu (and also apparently on the old gpu backend) but not on the new backend because the last node in the toposort would be a HostFromGpu.
> Fix how some tests get a reference to scan nodes in a theano function

- theano/scan_module/scan_op.py
- theano/scan_module/scan_opt.py
- theano/scan_module/tests/test_scan.py
This was found by unit tests in the Blocks framework.
The crash was caused by the save_mem optimization relying on the symbolic outputs of the scan() function being used by the user instead of of the outputs of the scan node. In blocks, they violate this assumption by taking the outputs of the scan() function and doing `x = x.owner.inputs[0]` on each of them to directly obtain the outputs of the scan node.
> [CRASH] Fix crash in save_mem when directly using outputs of the scan node

- theano/compile/function_module.py
- theano/gof/cmodule.py
I do not think we need something more complicated for now, as for the CPU tests, with that PR, we now spend only 343s in refresh instead of 1500s.
> Change cache refresh patter for speed up

- doc/library/scan.txt
Fixes #2651
Is this example enough, or shall I make something with more infos, examples, use cases,...
Cesar
> Added doc for strict flag.

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
Reported by Tariq Daouda in:
[theano-users] ERROR (theano.gof.opt): Optimization failure due to: local_argmax_pushdown
> [CRASH] Make MaxAndArgmax support NoneConst as axis.

- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
~~Those checks were added for the sake of completeness in a previous PR but they were not required for any use case known at that time.~~
~~This PR deactivates them for the time being because it appears these checks are causing issues with valid graphs (https://groups.google.com/forum/#!topic/theano-users/y7Nb8oYRUa0).~~
~~Since they are not required anywhere, they can be deactivated for the time being but we should go back eventually to figure out why.~~
Updated description:
The PR changes the way Scan handles some shared variables as recurrent outputs to make sure the associated and outputs are on the CPU. 
The current way it's implemented would mistakenly have MRG_RandomStreams with an input state on the CPU and the output state on GPU. This wasn't caught by anything but, eventually, …
> [CRASH] Improve shared variable management in Scan

- theano/gof/sched.py
- theano/gof/tests/test_link.py
- theano/sandbox/rng_mrg.py
- theano/scalar/basic.py
- theano/scalar/basic_scipy.py
- theano/sparse/basic.py
- theano/sparse/opt.py
- theano/sparse/sandbox/sp.py
- theano/sparse/sandbox/sp2.py
- theano/sparse/tests/test_basic.py
- theano/tensor/basic.py
- theano/tensor/extra_ops.py
- theano/tensor/nlinalg.py
- theano/tensor/slinalg.py
- theano/tensor/tests/test_elemwise.py
- theano/tensor/tests/test_opt.py
- theano/typed_list/basic.py
**NOTE:** Ideally #2860, #2862, #2864 and #2869 all get merged around the same time, to minimize the number of rebases. I can also consolidate them into one PR if need be.
These are removed in Python 3:
https://www.python.org/dev/peps/pep-3113/
> Respect PEP3113 (no more tuple unpacking arguments)

- theano/tensor/signal/downsample.py
- theano/tensor/signal/tests/test_downsample.py
Hi. I'd like to propose the following changes to the downsampling code:
* extend the C implementation of Downsample to support `average_inc_pad` and `average_exc_pad`,
* add a new `sum` mode to the Python and C implementations.
The C implementation for the `average_*` modes reuses most of the code from `max`. The `sum` mode is a relatively straightforward extension.
> Downsample: C implementation for average, sum

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
fix gh-2836
This is a crash in alloc grad, when the inputs have a broadcastable dimension that isn't broadcasted by the node.
reported by Dmitry Bogdanov
> Fix crash in Alloc grad

- theano/scan_module/tests/test_scan.py
With floatX=float64, rs.uniform would produce a float64 output which would prevent the Scan from being moved to the GPU.
> Fix scan test for float64

- theano/sandbox/cuda/elemwise.py
- theano/sandbox/cuda/opt.py
- theano/scalar/basic_scipy.py
- theano/tensor/basic.py
- theano/tensor/inplace.py
- theano/tensor/tests/test_basic.py
op for calculating the scaled complementary error function exp(x***2)**erfc(x) in a numerically stable way
This op is useful for calculating various things related to Gaussian distributions, such as truncated moments and expressions involving log(cdf(x)) for large negative values of x. The contributed code very closely follows that of the Erfinv op.
Tested on an EC2 GPU instance. Works for both CPU and GPU.
> Add new scalar and elemwise op erfcx

- theano/sandbox/gpuarray/opt.py
This fixes a few failing tests in Scan for the gpuarray backend
For the clone=True in gpuarray/opt.py, `FunctionGraph` was previously raising exceptions saying the graph contained cached constants and that the graph should be cloned.
> Fix tests in new backend

- theano/sandbox/gpuarray/elemwise.py
I missed one case where we need the wrapper when making reduction work with float16.
> Fix reduction in a limited case.

- theano/sandbox/gpuarray/__init__.py
- theano/sandbox/gpuarray/opt.py
- theano/scan_module/tests/test_scan.py
This PR refactors the gpu tests in test_scan.py to make them more easily usable to test both the cuda and the gpuarray backends.
The tests that can be made to work for both backends are moved to ScanGpuTests and are modified to rely on certain attributes/methods that will manage the interactions with the concrete gpu backend. The classes T_Scan_Cuda and T_Scan_Gpuarray inherit from ScanGpuTests and TestCase and implement these attributes/methods so that the tests will rely on their respective backends.
Some tests were highly cuda specific so they we moved to T_Scan_Cuda instead of ScanGpuTests.
> Move gpu tests from T_Scan to ScanGpuTests

- theano/scan_module/scan.py
- theano/scan_module/scan_utils.py
Without this modifications to traverse(), some HostFromGpu and GpuFromHost are introduced in the graph much too early in the optimization process and it prevents some Scan optimizations from doing their work.
> Scan gpuarray memory usage

- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
Fixes #2946.
The code to figure out how to cut sequences gave invalid results if, for a given sequence, the taps we all negative without being all identical.
> Fix sequence cutting in Scan

- theano/tensor/nnet/nnet.py
Very minor change to create an actual string representing the error, instead of a tuple of two strings
> Proper string representation of a ValueError on Softmax.make_node

- theano/sandbox/cuda/opt.py
- theano/tensor/blas.py
- theano/tensor/tests/test_blas.py
The previously done change from dot22->dot22scalar to dot22->gemm had the effect, under some not-fully-understood circumstances,  of duplicating certain Scan nodes and preventing certain optimizations (such as ScanSaveMem) on the duplicates. The result was a drastic increase in memory usage.
The issue should be investigated further and tests added to try and ensure this doesn't occur again but, in the mean time, this fixes this issue which is preventing from people from using the latest version.
> [Bug] Revert dot22->gemm optimization back to dot22->dot22scalar

- theano/sandbox/gpuarray/nerv.py
I just noticed that we get a bunch of error rather than just disabling.
> Disable local_dot_to_gemm16 if nervanagpu could not be imported.

- theano/misc/pkl_utils.py
- theano/misc/tests/test_pkl_utils.py
The counter that checked whether an array with that name already existed in the zip file should count the original names, not the enumerated ones, otherwise it saves them as `array`, `array_2`, `array_2`, ... instead of `array`, `array_2`, `array_3`.
Also removed a constructor which seemed useless.
> Fix error and remove unnecessary constructor

- theano/sandbox/cuda/cuda_ndarray.cu
This should fix the following errors:
```
*** Reference count error detected:
an attempt was made to deallocate 11 (f) ***
```
> Do not decref descriptor, as PyArray_View steals the reference

- theano/compile/function_module.py
- theano/gof/destroyhandler.py
- theano/gof/link.py
- theano/gof/vm.py
- theano/tensor/blas_c.py
- theano/tensor/tests/test_subtensor.py
- theano/tensor/var.py
Fix crash reported in "[theano-users] Slice indexing: tuple vs. list" and clean up
> [CRASH] Subtensor list

- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_opt.py
- theano/sandbox/gpuarray/opt.py
- theano/sandbox/gpuarray/tests/test_opt.py
- theano/tests/breakpoint.py
- theano/tests/test_breakpoint.py
This is just a small utility class to allow a user to put a conditional breakpoint, with pdb, inside the execution of a Theano function. It is implemented in a similar way to the Print() op in that it's a identity-like op with a side effect. It takes multiple inputs and the first one needs to be a 0d tensor and is interpreted as the condition that will decide the activation of the breakpoint. When, during execution, that condition is evaluated to True, the breakpoint will be activated. The subsequent inputs are interpreted as the variables the user wants to monitor and will be made available to the user when the conditional breakpoint activates.
I am not sure what the best way to test this class would be. It is easy enough to test that the breakpoint doesn't activate in a particular case …
> Add breakpoint Op to Theano

- theano/tensor/elemwise.py
- theano/tensor/tests/test_elemwise.py
PyMC3 users get cryptic errors from Theano if they use `prod` in their models. This aims to improve the situation.
> improve error message for grad of ProdWithoutZeros

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Make local_dimshuffle_lift go through many nodes by recursively calling itself. This commit is following the patch provided by Fred here ( https://github.com/Theano/Theano/issues/2971 ). 
I tested it with following code.
```
import theano                                                                                   
v = T.vector()
m = T.matrix()
out0 = (v+m).T
out = (out0 + 42).T
theano.config.optimizer_verbose = True
f = theano.function([v, m], out)
```
The output before this optimization as follows,
```
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
local_dimshuffle_lift DimShuffle{1,0}.0 Elemwise{add,no_inplace}.0
MergeOptimizer tan.0 tan.0
MergeOptimizer sqr.0 sqr.0
...... { MergeOptimizers for many times, ignored here}
MergeOptimizer …
```
> Make local_dimshuffle_lift go through many nodes

- theano/sandbox/cuda/cuda_ndarray.cu
I'm not completely sure about the incref/decref interaction with Py_BuildValue and PyArg_ParseTuple, though.
> Make sure the index array is contiguous before changing dtype

- theano/compile/debugmode.py
- theano/printing.py
- theano/tests/test_printing.py
- Fixes #2347. 
- I have tested this for 3 cases: one scan, two separate scans (added together), two nested scans.
- We need to find a good way of testing this other than looking at the debug print and making sure that references from the inner graph to the outer graph make sense.
> improving debugprint for scan ops

- theano/gof/theano_mod_helper.h
- theano/sandbox/cuda/cuda_ndarray.cuh
This is a first try, I've not been able to test it on Windows yet.
> Fix symbol visibility in cuda_ndarray on Windows

- doc/library/tensor/nnet/nnet.txt
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_nnet.py
As discussed in #2698, this adds a `theano.tensor.nnet.relu` function providing an optimized formulation of the linear rectifier and leaky linear rectifier at least for GPUs, with the potential to be extended with a different formulation for CPUs or even a ReLU Op in future.
/edit: I'm not sure about the docs, how can I test them?
> Add theano.tensor.nnet.relu function

- theano/tensor/tests/mlp_test.py
I think that it's not necessary to compute the logarithm of the whole matrix.
We can compute the logarithm only of classes from the labels array.
> small optimization of log likelihood function computation

- doc/tutorial/extending_theano.txt
Issue #2963.
Added the modifications for the __props__ attribute of theano ops.
This should override what happened in https://github.com/Theano/Theano/pull/3061 (which should now be discarded).
> a proper rebased version of the modifications for my CCW modifications

- theano/sandbox/gpuarray/__init__.py
- theano/sandbox/gpuarray/basic_ops.py
- theano/sandbox/gpuarray/comp.py
- theano/sandbox/gpuarray/cudnn_helper.h
- theano/sandbox/gpuarray/dnn.py
- theano/sandbox/gpuarray/dnn_base.c
- theano/sandbox/gpuarray/dnn_conv_base.c
- theano/sandbox/gpuarray/dnn_fwd.c
- theano/sandbox/gpuarray/dnn_gi.c
- theano/sandbox/gpuarray/dnn_gw.c
- theano/sandbox/gpuarray/gpuarray_helper.h
- theano/sandbox/gpuarray/opt.py
- theano/sandbox/gpuarray/opt_util.py
- theano/sandbox/gpuarray/tests/test_dnn.py
- theano/tensor/basic.py
This ports the current cudnn code we have for the cuda backend over to the gpuarray one.
I've made it so the first commit just copies all the code and then the subsequent ones adapt it.
Some of the surrounding code had to be fixed also so there is a bit more than just straight adapting.
All of tests/test_dnn.py passes locally.
> Port of the cudnn code for the gpuarray backend

- theano/gof/type.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/gpuarray/dnn.py
This fixes the memory leak observed at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lasagne-users/8iXu7NcAxuY/eI72oHkslGcJ and another one involving pooling descriptors.
There seems to be another leak in cuda-convnet, which this does not fix.
> Fix memory leak of descriptors in cudnn bindings.

- theano/sandbox/gpuarray/elemwise.py
- theano/sandbox/gpuarray/opt.py
- theano/sandbox/gpuarray/tests/test_elemwise.py
In the gpuarray backend, pow can only be done on inputs that are both float (producing a float output) or both double (producing a double output). Currently, some unit tests for Scan attempt to do `a_float ** an_int16` which raises a compilation error. This optimization adds  a cast to ensure that the exponent has the same dtype as the output to prevent this.
> Add opt for gpuarray.GpuElemwise so exponent of pow has same dtype as output

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
This was the cause of an error in one of Scan's optimization that was reported on the theano-dev mailing list : https://groups.google.com/forum/#!topic/theano-users/PCg5KjskuN4
> Fix broadcastable pattern of flatten output

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Optimization local_sum_prod_mul_by_scalar had behavior : 
prod(scalar * smth) -> scalar * prod(smth)
prod(-smth) -> -prod(smth)
when it should have been : 
prod(scalar * smth) -> scalar ** size(smth) * prod(smth)
prod(-smth) -> (-1) ** size(smth) * prod(smth)
> [BUG] Fix invalid optimization for product of multiplication

- theano/sandbox/cuda/cuda_ndarray.cu
- theano/sandbox/cuda/tests/test_basic_ops.py
Fixes #3175 for me.
I couldn't see any obvious problems with removing this restriction (which isn't applied by the CPU backend). But perhaps there was some cuda-specific reason for the stricter restriction here?
There was a commit (https://github.com/Theano/Theano/commit/23fa09f02d731ca0a5437772cf6118ca16c542c9) made to permit reshaping of zero-size arrays before, which looks like it fixed this issue but was partially undone again at some point in a merge.
> Remove the restriction on zero target dimensions when reshaping a CudaNdarray

- theano/compile/builders.py
- theano/compile/tests/test_builders.py
Only a draft.  Simple test pass but have many warning.
```Python
WARNING (theano.tensor.opt): Failed to infer_shape from Op <theano.compile.builders.OpFromGraph object at 0x10c5bb590>.
Input shapes: [(Shape_i{0}.0, Shape_i{1}.0), (Shape_i{0}.0, Shape_i{1}.0), (Shape_i{0}.0, Shape_i{1}.0)]
Exception encountered during infer_shape: <type 'exceptions.TypeError'>
Exception message: ('Bad input argument to theano function with name "/Users/ChienliMa/Code/Theano/theano/tensor/utils.py:87"  at index 0(0-based)', 'Expected an array-like object, but found a Variable: maybe you are trying to call a function on a (possibly shared) variable instead of a numeric array?')
Traceback: Traceback (most recent call last):
File "/Users/ChienliMa/Code/Theano/theano/tensor/opt.py", line 1079, in on_import …
```
> OpFromGraph.infer_shape()

- theano/gof/destroyhandler.py
It makes following methods inline.
- getroot
- add_impact
- get_impact
This speed up local_elemwise_inplace optimization
> Inline optimization for destroyhandler.py

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
This addresses https://groups.google.com/forum/#!topic/theano-users/AUuHNstlVYY.  It allows for this kind of stuff to work:
```Python
>>> import theano
>>> import numpy as np
>>> import theano.tensor as T
>>> x = T.tensor4('x')
>>> a, b = x.shape[:2]
>>> a.eval({x: np.zeros((5, 4, 3, 2), dtype=theano.config.floatX)})
array(5)
>>> a = x.shape[3:10]
>>> a.eval({x: np.zeros((5, 4, 3, 2), dtype=theano.config.floatX)})
array([2])
```
> Allow slicing of tensor variables to return symbolic shape refs

- theano/tensor/tests/test_var.py
- theano/tensor/var.py
This PR follows the pattern demonstrated in #3112 to allow more numpy functions to build a graph in a manner that is convenient for PyMC3 users. 
This includes everything listed in https://github.com/Theano/Theano/issues/3040#issuecomment-114097347 except for the following: `degrees, fabs, radians, rint`.  I suspect that these will not be missed, since they all have simple alternatives.
I think that this can close issue #3040.
> ENH: allow numpy.*(theano_var) to build a graph

- theano/sandbox/cuda/opt_util.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/sandbox/gpuarray/opt_util.py
Also apply output_merge in the case when the new output has to be broadcasted.
This may help speed up some graphs by not duplicating heavy nodes in the graph.
> Don't apply alpha_merge and output_merge when the proc node has more than one client.

- theano/scan_module/scan_opt.py
@lamblin @carriepl @nouiz 
I have done some easy optimizations in the scan_opt.py. Most of the operations that can be done in constant time by using set or dictionary, previously was being done in linear time inside the loop. It was a bit slow because of that. 
There are a few other changes that I want to do as well. 
These changes speedup by more than 100 secs for a computational graph that was taking more than 900 secs to compile.
> Speed up Scan optimizations

- theano/sandbox/cuda/cnmem.cpp
- theano/sandbox/cuda/cnmem.h
This version comes with two fixes.
1/ Fix a warning due to the visibility attribute needed by Theano.
We changed const char* CNMEM_API to const char CNMEM_API* in the
declaration of cnmemGetErrorString to have the attribute between
char and star. It fixes the warning.
2/ Fix a compilation issue with CUDA 5.0 due to the missing
cudaStreamGetFlags function. It is #defined out when the Runtime
is less than 5.5 (5050 version).
> Integrate the latest version of CNMEM

- theano/compile/sharedvalue.py
I was using this function for a while for myself. It is very similar to what torch.tensor:zero function does:
https://github.com/torch/torch7/blob/master/doc/tensor.md#self-zero
This is just a syntactic sugar. I find this more readable than doing get_value and then set_value to reset a shared variable to zero in my code. 
If that PR gets through, I have a few other functions like that which I can make PR for too.
> added the shared variable zero fn.

- theano/configparser.py
- theano/scan_module/scan_opt.py
- theano/scan_module/tests/test_scan.py
This fixes the optimization issue raised recently raised on the theano-users mailing list :
https://groups.google.com/forum/#!topic/theano-users/_GKQXt-WPOk
This make an opt applied more frequently and remove useless warning shown to the user.
> [ENH] Scan PushOutSeqScan

- theano/gof/opt.py
The convolution meta-optimizer currently fails for cuDNN with: `theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: <CudaNdarrayType(float32, 4D)>.`
That's because it collects required inputs from the original GpuConv Op prior to applying any optimizers, and it may happen that the optimizers render one of the inputs unneeded (I haven't looked into this, but I assume it could be due to the output shape computation or something).
This PR fixes this by allowing the function compiled for timing the replaced Op to accept inputs it doesn't actually need (`on_unused_input='ignore'`).
> Fix metaoptimizer for cudnn

- theano/sandbox/cuda/dnn.py
`THEANO_FLAGS=dnn.conv.algo_bwd=time_on_shape_change` didn't work due to a copy/paste bug in `dnn.py`.
> Fix copy/paste bug for cuDNN time_on_shape_change mode

- theano/printing.py
Very minor, but I was puzzled by the error message since I had `pydot` installed, but not `graphviz`.
> Clearer error message for missing pydot/graphviz.

- theano/configparser.py
Config parameters in CUDNN v3 have more than one hierarchy level
(i.e. dnn.conv.algo_fwd). At the moment these values cannot by changed by .theanorc.
This patch corrects these issue.
> enable dots in section names

- theano/compile/nanguardmode.py
NanGuardMode applies np.ndarray operations on RandomState, which causes a crash.
Traceback:
File "/home/cvangysel/Theano/theano/compile/nanguardmode.py", line 59, in contains_nan return np.isnan(np.min(arr))
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
> Exempt np.random.mtrand.RandomState from NaN/inf/big_number checking in NanGuardMode.

- theano/printing.py
This is necessary to work on Windows, and for Python 3
> Make pydotprint work with pydot_ng

- theano/sandbox/cuda/dnn.py
In python 3, map returns a map object iterator rather than a list, which here gets consumed by min, leaving pad_desc empty.
This bug was just introduced with the update to cudnn v3.
> python 3 fix in dnn.py

- theano/scan_module/scan_opt.py
- theano/scan_module/tests/test_scan.py
After discussion with @lamblin and @abergeron, we agreed on the fix being to prevent ScanSaveMem to reduce below 1 the number of steps a Scan will run. 
The alternative was making Scan support having 0 steps at execution time but that would still involve running the Scan for at least one iteration so that the output shapes would be known : even if the scan is supposed to run 0 steps and return empty outputs, these outputs still need to have the right shape. For recurrent states, the shape can be obtained from the initial states but for non-recurrent states, the inner function has to be executed at least once to know their shapes.
> Prevent ScanSaveMem from creating 0-steps scans.

- doc/library/config.txt
It's a trivial change, but the CNMeM configuration option was named `lib.cnmem` instead of `config.lib.cnmem` in the documentation. As I hadn't heard about the `lib` prefix before, I thought it should mean `config.cnmem` and thus my first attempt was to use `THEANO_FLAGS=cnmem=.3`, which didn't work. This PR makes it unambiguous.
> Correct config.lib.cnmem name in documentation

- theano/sandbox/cuda/dnn_base.c
Allocating the strides array dynamically lets it also compile on Windows. See https://groups.google.com/forum/#!topic/theano-users/fex4OpL9hB0 for code that errors on Windows without this.
> Update sandbox/cuda/dnn_base.c to work on Windows

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> theano.tensor.constant reshape fix

- theano/gof/cutils.py
This fixes #3291 after a clean-up of the existing cutils_ext.
Is there a way to force its recompilation?
> Do not read infinite value from output in advanced setsubtensor1

- theano/sandbox/gpuarray/basic_ops.py
- theano/sandbox/gpuarray/conv.cu
- theano/sandbox/gpuarray/conv.py
- theano/sandbox/gpuarray/conv_full_kernel.cu
- theano/sandbox/gpuarray/conv_kernel.cu
- theano/sandbox/gpuarray/elemwise.py
- theano/sandbox/gpuarray/kernel_codegen.py
- theano/sandbox/gpuarray/neighbours.py
- theano/sandbox/gpuarray/nnet.py
- theano/sandbox/gpuarray/subtensor.py
Currently, the gpuarray back end of Theano uses a mixture of libgpuarray and nvcc, which is slow for online compilation.  We can speed up the GPU code compilation using libgpuarray API alone without nvcc, especially when libgpuarray is built with the nvrtc support (see https://github.com/Theano/libgpuarray/pull/72).
This hopefully helps managing GPU related code in Theano and libgpuarray by having vendor specific implementation only in libgpuarray.
> Use the libgpuarray APIs to manage GPU code compilation, execution, etc.

- theano/tests/test_flake8.py
Apparently the python on travis doesn't care, but my version of python complains about this.
> Fix a non-ascii character in a comment in test_flake8.py.

- doc/extending/theano_vs_c.txt
It screwed up the [rendered formatting](http://deeplearning.net/software/theano/extending/theano_vs_c.html).
> Whitespace needed in theano_vs_c.txt

- theano/tensor/basic.py
- theano/tensor/tests/test_var.py
- theano/tensor/var.py
> Add a 'name' argument to '.copy' method of Theano variables

- theano/tensor/opt.py
These Shape_i nodes will not always be optimized away otherwise, and
they prevent local_shape_to_shape_i from being applied.
Instead, we manually apply the equivalent of local_shape_to_shape_i,
by using shape_of[...] directly.
A test is still missing.
@aalmah, this should fix the last remaining convolution in your case.
> Use shape_of instead of explicitly inserting Shape_i

- theano/scan_module/scan_opt.py
This is work in progress to attempt to speed up the ScanInplaceOptimizer() since some users have been reporting a lot of time being spent in this optimization.
Instead of trying to make the scan compute every output inplace one by one, this starts by attempting to make scan compute all its outputs inplace. It is doesn't work then it goes back to trying every output one by one.
> Scan inplace opt

- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/cuda_ndarray.cu
- fixing an issue introduced with CUDA-TK 7.0, when automatic selection
of free gpu by os / library no longer works. Library always selects '0',
which leads to crash in case of 'exclusive mode' when '0' is taken and 
other gpus are free.
- this fix is inspired by Dan Povey's fix for Kaldi:
kaldi-asr/kaldi@6548565
- it does a loop over gpus until a free gpu is taken.
- pycuda initialization was also affected by the bug from CUDA 7.0, so it is better to disable it.
> automatic gpu selection no longer works in CUDA-TK 7.0

- doc/install.txt
This pull request adds an alternative way of running Theano to the docs. These Docker images have been in use successfully for some time for not just using Theano, but also as the basis for other libraries that build on top of Theano.
Closes https://github.com/Theano/Theano/issues/3388.
> Add Docker images to the installation docs

- doc/install.txt
Fixes an error in the markup (spacing for links in reStructuredText) introduced in pull https://github.com/Theano/Theano/pull/3399.
> Fix Sphinx markup in docs

- theano/sandbox/gpuarray/nnet.py
- theano/sandbox/gpuarray/tests/test_nnet.py
- theano/sandbox/gpuarray/type.py
- theano/tensor/basic.py
- theano/tensor/nnet/nnet.py
- theano/tests/unittest_tools.py
This fixes a bug which causes crashes in float16 and wrong results in float64.
> Fix GpuSoftmax and GpuSoftmaxWithBias for non-float32 operation.

- theano/sparse/sandbox/sp.py
- theano/tensor/nnet/neighbours.py
- theano/tensor/signal/conv.py
- theano/tensor/tests/test_opt.py
Tests with theano-nose are filled with DeprecationWarning messages because or PR #3318 
```/home/dpln/deep-learning-suite/theano/theano/tensor/nnet/neighbours.py:109: DeprecationWarning: stack(*tensors) interface is deprecated, use stack(tensors, axis=0) instead.  return [neibs2images(gz, neib_shape, x.shape, mode=self.mode),/home/dpln/deep-learning-suite/theano/theano/tensor/nnet/neighbours.py:109: DeprecationWarning: stack(*tensors) interface is deprecated, use stack(tensors, axis=0) instead.  return [neibs2images(gz, neib_shape, x.shape, mode=self.mode),/home/dpln/deep-learning-suite/theano/theano/tensor/nnet/neighbours.py:109: DeprecationWarning: stack(*tensors) interface is deprecated, use stack(tensors, axis=0) instead.  return [neibs2images(gz, neib_shape, x.shape, …
```
> Fix stack interface use

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
@carriepl can you review this?
Can you also check the other sum/prod opt changed at the same time if they have this problem? Just in case.
the opt local_op_of_op was merging 2 consecutive sum or prod. But it was also merging 1 sum followed by a prod (or the reverse)
fix gh-3451
> [BUG] in opt local_op_of_op

- theano/gradient.py
- theano/scan_module/scan_op.py
NOTE : I'm still in the process of testing this change but it might still be good to start getting feedback. Since this changes the graphs that result from taking gradients of Scan nodes, it may mean that new optimizations that were previously not needed would now be more useful/important.
This PR modifies the way Scan takes the gradient of it's inner function. Instead of doing nb_inputs * nb_outputs calls to grad to get the gradient of its inner function, it now does only one such call. This makes grad() generally faster but even more so in the case of taking the gradient of nested scans in which the number of calls to grad() would increase exponentially with the number of levels of nested scans. Because of the reduced number of calls to grad() the resulting scan grads have simple graphs …
> Scan grad speedup

- theano/sandbox/cuda/nnet.py
After a bit of profiling this op turned out to be a massive bottleneck in training a smaller feedforward network with a large-ish (10000 class) softmax output layer, taking 40 to 60% of the total time, much more than any of the dot22 / gemm linear algebra ops which really should be the bottleneck.
On investigation it turned out the GPU kernel for this op was only using a single thread, with a TODO to fix it. This commit implements that TODO. This op now only takes around 6% of the total time for me. It could probably be optimised further (e.g. via hierarchical / multi-stage reductions) but I think this is worth submitting.
Tagging @jaberg as it looks like this was your code originally. It's my first theano contribution and I'm relatively new to CUDA so let me know if you notice anything …
> Performance improvement for GpuCrossentropySoftmaxArgmax1HotWithBias

- doc/library/tensor/basic.txt
- theano/tensor/basic.py
Fix #3446.
The deprecation warning message was under the new stack() interface while it should be under the old stack() interface. 
I also added examples.
> Fix stack(tensors, axis=0) documentation

- theano/scalar/basic.py
To be tested as I don't have a case to reproduce it.
Also, this case should only be triggered when both input and output of the cast have the same dtype, so maybe this node should be removed altogether earlier on.
> Use make_new_inplace mechanism to fix optimization with cast

- theano/sandbox/cuda/dnn.py
Wrong argument name. This made dnn stuff crash.
> Fix crash introduced by gh-3476

- theano/scan_module/scan_op.py
- theano/scan_module/scan_opt.py
1 - Speed up ScanInplaceOptimizer by prefiltering the list of outputs to attempt to compute inplace.
2 - Give In() variables with updates a default value (to avoid warnings with mode=DebugMode)
> Scan fixes and speedup

- theano/sandbox/gpuarray/basic_ops.py
When trying to run a simple Theano example with latest theano / libgpuarray using OpenCL, I ran into the following errors
```python
import theano
x = T.dmatrix('x')
s = 1 / (1 + T.exp(-x))
logistic = theano.function([x], s)
logistic([[0, 1], [-1, -2]])
```
```
/home/julien.rebetez/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.7-Final-x86_64-2.7.10-64/tmpAYEbvH/mod.cpp: In member function ‘int<unnamed>::__struct_compiled_op_1e445e5da5a62eeb42cc430a1d702612::run()’:
/home/julien.rebetez/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.7-Final-x86_64-2.7.10-64/tmpAYEbvH/mod.cpp:200: error: cannot convert ‘PyArrayObject*’ to ‘PyGpuArrayObject*’ in assignment
/home/julien.rebetez/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.7- …
```
> Fix GpuFromHost compilation error using libgpuarray

- theano/sandbox/cuda/cuda_ndarray.cu
Changed all `printf()` calls formatting `size_t` variables with the `%zd` format specifier to `%llu` and corresponding `unsigned long long` casts, for compatibility with Visual Studio 2013 and before.
In some of these strings `%d` was used to print `size_t`; those were also changed.
Fixes #3514 on my machine when one of the error messages was triggered (have not tried other compilers).
> Changed printf with %zd specifier to %llu for portability (MSVC2013)

- doc/extending/optimization.txt
- theano/compile/function_module.py
It took me some time to figure out why `config.profile_optimizer` wasn't working (config.profile was False). This adds a small note about this in the optimization doc page and shows a warning if the user forgets to set config.profile to True as well.
> Add warning if profile_optimizer=True but profile=False

- theano/gradient.py
This `assert` statement does not provide any error message making debugging this case hard. Moreover, `assert` is eliminated when using optimized python code (https://docs.python.org/2.7/reference/simple_stmts.html#the-assert-statement), introducing a potential bug into the system. Explicitly checking and raising an AssertionError addresses both issues.
> changing `assert` to `AssertionError`

- doc/library/tensor/nnet/conv.txt
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/corr_gemm.c
- theano/tensor/nnet/tests/test_corr.py
First PR was in strange state. Local commit history was different than github history and I couldn't reconcile them. Trying again...
CPU implementation of the CorrMM style convolutions for #3026.
General
C code
Theano
Later PRs
- Write optimization to swap conv ops (waiting on #2665)
> [WIP] CpuCorrMM closes #3026 - redux

- theano/gof/cmodule.py
The check in cmodule.py (line 2016) fails to detect ARM 64-bit processors (since platform.machine() returns 'aarch64'). This is a fix for all 32- and 64-bit ARM arch.
> fix for aarch64 (ARM 64-bit arch)

- theano/sandbox/cuda/dnn_fwd.c
- theano/sandbox/cuda/dnn_gi.c
- theano/sandbox/cuda/dnn_gw.c
- theano/sandbox/gpuarray/dnn_fwd.c
- theano/sandbox/gpuarray/dnn_gi.c
- theano/sandbox/gpuarray/dnn_gw.c
In all 6 modified files, the code was supposed to look at the spatial dimensions of the inputs and the filters in the case of 2d convolution.
These should be dimensions with 2 and 3 since the input dimensions are (batch, channel, 0, 1) and the filter dimensions are (filter, channel, 0, 1). However, in both backends, the indices were wrong. This meant that the FFT implementation was not used in many cases where it could have been used.
> Fix index errors

- doc/extending/cop.txt
- doc/extending/index.txt
- doc/extending/using_params.txt
- doc/tutorial/extending_theano_c.txt
- theano/gof/cc.py
- theano/gof/graph.py
- theano/gof/op.py
- theano/sandbox/gpuarray/basic_ops.py
- theano/sandbox/gpuarray/conv.py
- theano/sandbox/gpuarray/dnn.py
- theano/sandbox/gpuarray/dnn_base.c
- theano/sandbox/gpuarray/elemwise.py
- theano/sandbox/gpuarray/gemm16.c
- theano/sandbox/gpuarray/neighbours.py
- theano/sandbox/gpuarray/nerv.py
- theano/sandbox/gpuarray/nnet.py
- theano/sandbox/gpuarray/subtensor.py
- theano/sandbox/rng_mrg.py
This renames op context to op params and adds a small tutorial for it.
I felt the rename was warranted beause it's not used much right now and params is a much better name for the new generic usage we are thinking about.
Testing with a couple of simple multi-gpu programs assures me that the rename went well.
> Small tutorial for op params

- theano/gof/tests/test_destroyhandler.py
- theano/gof/toolbox.py
This is a follow up from quick discussion with @abergeron some time ago. He found in one use case that we used 2g of ram after one function compilation. He found that it was mostly checkpoint.
> [ENH] Keep an history of only 1 checkpoint of FunctionGraph

- theano/printing.py
The main problem is that `zip` function in Python 3 is an iterator and `reversed` function doesn't work with an iterators. 
Previously I got `TypeError` exception: 
```
File "theano/printing.py", line 847, in pydotprint
fct.maker.fgraph.inputs)):
TypeError: argument to reversed() must be a sequence
```
That fix works fine for me in Python 3.4
> Fix pydotprint issue for Python 3

- theano/sandbox/cuda/dnn.py
On Windows, in `theano.sandbox.cuda.dnn.dnn_available()`, `comp`, `out` and `err` evaluate to:
```python
False
b"nvcc fatal   : Cannot find compiler 'cl.exe' in PATH\r\n"
b''
```
So I found it necessary to add the `--compiler-bindir` flag to the source, in order to actually use CuDNN.
> Fixes cl.exe not being seen on Windows

- theano/sandbox/cuda/dnn.py
- theano/tensor/nnet/conv.py
Continuation of [this PR](https://github.com/Theano/Theano/pull/3644/files#r45815210).
Factoring the inference of convolution output shape in sandbox/cuda and fixing the deprecated getOutputShape method.
> Factoring inference of convolution output shape (continuation)

- theano/tensor/nnet/abstract_conv2d.py
Fixes #3699 for me. This removes a call to `list` on a symbolic shape vector, which was breaking dnn_conv.
@laurent-dinh was there was a reason for this call to list in cases of non-symbolic input? I may leave it to your travis build to find out :)
> Fix get_conv_output_shape for symbolic input

- theano/misc/check_multi_gpu.py
- theano/sandbox/gpuarray/basic_ops.py
Also update the timing to show more cases. Example of result when using this libgpuarray PR:
https://github.com/Theano/libgpuarray/pull/117
one ctx async 3.349727
two ctx async 1.713157
two ctx, 2 fct async 1.717468
two ctx, 2 fct with transfer 3.635517
two ctx, 2 fct async, 2 threads 1.731599
two ctx, 2 fct with transfer, 2 threads 2.071597
This mean that one function with 2 gemm, if we put them on 2 GPUs, we have a 1.95x speed up.
If we split the 2 gemm each in a function, we kepp the 1.95x speed up.
If we add one gpu to cpu transfer after the gemm and keep 2 function each with 1 gemm and 1 transer, we loose the speed up. We get a speed up (slowdown) of 0.92x again the version without tranfers and ONE GPU.
If we use 2 threads, each with its function without transfer, go drop to 1.93x …
> Release the GIL in the new back-end to allow multi-threads computation.

- theano/tensor/nnet/conv.py
Modified check for datatype of image and filter shape. Now it allows for int and uint both.
fix gh-3329
> conv2d support uint

- doc/tutorial/extending_theano.txt
- theano/compile/tests/test_ops.py
because as_op does not support operation that returns a view.
> Use np.cumprod instead of np.diag in OpDecoratorTests

- doc/library/config.txt
- theano/compile/debugmode.py
- theano/configdefaults.py
- theano/gof/graph.py
- theano/sandbox/cuda/var.py
- theano/sandbox/gpuarray/type.py
Add a configuration option to override `Variable.__str__` and print the `tag.test_value` after the variable name by default. By default the option is disabled.
@lamblin Thank you very much for the assistance!
> Add print_test_value_by_default option

- theano/tensor/tests/test_slinalg.py
This fixes a test when run with a recent version of scipy.
We still support the old cases, even if scipy dropped them.
> Update test for recent scipy.

- doc/library/config.txt
- theano/__init__.py
- theano/configdefaults.py
Performing module tests on import causes a small overhead. It seems that running these tests is not required for Theano to properly initialize on systems where the tests would have passed. I added a configuration option to disable these tests which cuts import time by 20-30% for small test cases.
> Added config variable to disable initial testing of nvidia drivers

- theano/d3viz/__init__.py
- theano/d3viz/formatting.py
- theano/d3viz/tests/test_d3viz.py
- theano/d3viz/tests/test_formatting.py
- theano/printing.py
Added support for importing `pydot-ng` with `pydot` as fallback everywhere, shortened and standardized handling of this.
> Import pydot-ng with pydot as fallback.

- theano/sandbox/cuda/cula.py
Fixed the cula runtime error by adding "RuntimeError" in the except line.
fix gh-3785
> fixed cula runtime error (libcula.so not found)

- theano/configdefaults.py
- theano/sandbox/gpuarray/__init__.py
- theano/sandbox/gpuarray/dnn_base.c
This adds an option to preallocate some memory on gpuarray devices.
It also fixes a leak of the handle for all cudnn ops.  This was causing out of memory error in the tests on smaller GPUs since each handle uses about 1M of GPU memory.
> Gpuarray prealloc

- theano/sandbox/gpuarray/__init__.py
To address the comment on #3792, this caps the maximum reservation to 0.98.
> Cap memory preallocation to 98% of the total.

- theano/tensor/blas.py
Fixes broken implementation of #3654.
Before, it would try `"-lblas f i r s t / d i r e c t o r y - L s e c o n d / d i r e c t o r y"`.
With this fix, it will try `"-lblas -Lfirst/directory -Lsecond/directory"`.
Should work better as a fallback...
> Fix fallback in BLAS detection

- theano/printing.py
In Python3 ``map`` returns a map-object (and not a list). This makes the check
introduced in #3057 fail with "TypeError: unorderable types: map() < list()"
> Fix Python3 regression in ``pydotprint``

- doc/developer/compat.txt
In Python 2.x encode/decode on incorrect type is not no-op - Python 2 tries to convert data implicitly first. E.g. if you call `b'hello'.encode('utf8')`, Python 2 will first convert `b'hello'` to unicode by decoding it using `sys.getdefaultencoding()`, and then encode the result to utf8. It is almost always a wrong thing to do.
> DOC removed incorrect statement from compatibility docs

- theano/compile/ops.py
Changed it to accept both bool and numpy.bool_ as broadcastability values. It already accepts both ints and numpy.integers as broadcast axes.
> fixed too-stringent typecheck in Rebroadcast.__init__()

- theano/gof/compiledir.py
I ran Theano on a distributed environment. On worker nodes, it might possibly we don't have writing permission for the returned dir of `get_home_dir`. In this case, the running will be failed. I think we can assign it to temporary directory in this case.
> Check home_dir writing permission and assign temporary directory

- theano/tensor/var.py
I was using lasagne.utils.one_hot like this:
```python
from lasagne.utils import one_hot
from theano import function
VOCAB_SIZE = 2500
X = T.matrix('X', dtype='int32')
encode = function([X], one_hot(X, m=VOCAB_SIZE))
```
This code took about 0.47s to process, 0.34s of which were spent sorting numpy arrays:
```
80002 function calls (79665 primitive calls) in 0.472 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000    0.472    0.472 {built-in method builtins.exec}
1    0.000    0.000    0.472    0.472 <string>:2(<module>)
1    0.000    0.000    0.464    0.464 function.py:73(function)
1    0.000    0.000    0.464    0.464 pfunc.py:329(pfunc)
1    0.000    0.000    0.464    0.464 …
```
> optimize TensorConstant constructor

- doc/tutorial/using_gpu.txt
- theano/sandbox/gpuarray/opt.py
This was not the old behavior so it introduces new and exciting failures.
I left a way to force an input on the CPU/GPU if you really want to.
I also renamed tag.context_name to tag.target and documented it for inputs.
> Don't transfer int inputs to the GPU by default

- theano/gof/link.py
`raise_with_op` function stores total size in 3rd element of `storage_map_item` list and then sorts records by total size. For some records total size is not available; in this case the current code puts None to the 3rd list element. But in Python 3 comparing a number or None with None raises a ValueError, so in Python 3 `raise_with_op` fails:
```
<...snip...>
During handling of the above exception, another exception occurred:
TypeError                                 Traceback (most recent call last)
<ipython-input-25-98e36ee02392> in <module>()
----> 1 cell.step(x0)
/Users/kmike/envs/dl/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
869                     node=self.fn.nodes[self.fn.position_of_error],
870 …
```
> fixed theano.gof.link.raise_with_op in Python 3

- theano/scan_module/scan.py
A PR for #3333. Just faced this issue today and spent some time debugging, thinking something is wrong with my code.
An objection was that error message is not clear enough without this warning. This is the error message:
```
MissingInputError: A variable that is an input to the graph was 
neither provided as an input to the function nor given a value. 
A chain of variables leading from this input to an output is 
[b_output, HostFromGpu.0, Elemwise{add,no_inplace}.0, DimShuffle{x,0}.0, Softmax.0]. 
This chain may not be unique
Backtrace when the variable is created:
File "<ipython-input-22-04b2f3ee6772>", line 19, in __init__
self.b_output = shared(init_ones(out_dim), 'b_output')
```
for me (a Theano novice) it looks clear enough - strict=True must be set explicitly, so I've read Theano …
> scan: remove unconditional warning when strict=True is used

- setup.py
this replace https://github.com/Theano/Theano/pull/3860 and close gh-3854
Use postfix .dev0 and bump to 0.8.0.dev0. This follow this new pep: https://www.python.org/dev/peps/pep-0440/#developmental-releases
> Bump version to 0.8.0.dev0

- theano/tensor/nnet/conv3d2d.py
- theano/tensor/nnet/tests/test_corr.py
This should remove about 50% of the remaining warning messages in the tests.
The rest is a case of 80% of the effort for 20% of results.  I still might get to it at some point.
> Remove more warnings from the buildbot

- theano/tensor/signal/downsample.py
`pool` is a local submodule, so it should be imported as `from . import pool` instead of `import pool`. This fixes a bug when importing the `downsample` module (at least on Python 3).
fix gh-3894
> Fixed import of local pool submodule

- theano/d3viz/d3viz.py
Came across this bug when trying to output visualizations to the current directory. Previous code enforced that all visualizations be contained in a subdirectory, as the directory was never checked before calling os.mkdirs().
```
File "main.py", line 88, in <module>
main()
File "main.py", line 85, in main
output_viz(nn_step, 'step.html')
File "main.py", line 79, in output_viz
V.d3viz(fn, name)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/d3viz/d3viz.py", line 85, in d3viz
os.makedirs(outdir)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''"
```
> Bug fix: don't try to os.mkdirs on an empty directory

- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_abstractconv.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/tests/unittest_tools.py
The new `conv2d()` interface supports `border_mode="half"` for same convolutions. However, the cudnn convolution interface in Theano does not support it. `local_abstractconv_cudnn()` does not take care of this. Thus, the following fails when cuDNN is available:
```python
In [1]: import theano
Using gpu device 0: Tesla K40c (CNMeM is enabled)
In [2]: x, w = theano.tensor.tensor4s('xw')
In [3]: c = theano.tensor.nnet.conv2d(x, w, border_mode='half')
In [4]: f = theano.function([x, w], c)
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_abstractconv_cudnn,local_conv_dnn,local_abstractconv_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv_gradweight_gemm,local_conv_gemm)
ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='half', subsample=(1, 1), …
```
> Add border_mode="half" to cuDNN convolutions

- theano/sandbox/cuda/basic_ops.py
Add missing `return` to the `R_op` for `GpuFromHost`.
> add missing return to GpuFromHost R_op

- theano/gof/cmodule.py
fixes #3556: more robust determination of python library name and directory in function std_lib_dirs_and_libs(), now works on private python installations on Linux
> fixes #3556: more robust determination of python library name 

- theano/sandbox/cuda/nvcc_compiler.py
We can't just stuff them in -Xcompiler since this splits the -Wl and the following arg.  I just rewrite them as -Xlinker.
> Fix args with -Wl to nvcc

- theano/tensor/elemwise.py
The workaround with signatures should also be applied for unsigned integers.
> Fix the thunk differences in DebugMode

- theano/sandbox/gpuarray/dnn.py
- theano/sandbox/gpuarray/opt.py
- theano/tensor/nnet/abstract_conv.py
This fixes a number of problems.
The main one is that the lifter for Pool was removing operations from the graph in certain circumstances.
Others are:
- The lifter for Print was mostly broken
- AbstractConv could stay unoptimized in certain cases of mixed input types.
There is now code in the AbstractConv ops to convert all inputs to be of the same type as the first one, which avoids the second problem.
> Fix last DLT problem(s) with the new backend.

- theano/tensor/basic.py
Fixing Issue #3985 ,
Temporarily setting the 'warn_float64' flag to 'ignore' in  Arange.infer_shape()
> Temp disable warn64

- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_nnet.py
cf #3752, thanks @shawnjhenry!
In h_softmax, replace sparse_block_dot with tensor_block when full output is requested.
> Speed up h_softmax when full output is requested.

- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/gpuarray/__init__.py
- theano/sandbox/gpuarray/dnn.py
This PR do a few things about the cudnn version.
- It finish gh-3901(so fix gh-3876), print the cudnn version when we init the back-end.
- It fix gh-3996 by warning user if there cudnn version is too recent
- It make cudnn mandatory in the new back-end.
> Cudnn version, print it, warn when too new, make mandatory in the new back-end.

- theano/gof/cmodule.py
Small change to resolve problems when LDLIBRARY points to a *.a file instead of *.so.
> (#4024) cutting the *.a extension in ldlibrary file

- theano/gof/cmodule.py
- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/nvcc_compiler.py
This is a proposed fix #4082.
The PR causes  `config.dnn.include_path` and `config.dnn.library_path` to be included in the compile commands for CUDA backend cuDNN ops by adding them to the lists returned by the `c_header_dirs` and `c_lib_dirs` methods of the cuDNN related ops in `sandbox/cuda/__init__.py` and `sandbox/cuda/dnn.py`.
To make sure the user specified library paths are given greater precedence by the compiler it also switches the order in which the `lib_dirs` list is constructed in `NVCC_compiler.compile_str` in `sandbox/cuda/nvcc_compiler`, with the user specified library paths put at the start of the list (rather than being added after the standard libraries returned by `std_lib_dirs()` as currently). This is already the behaviour for the `include_dirs`. For consistency I …
> cuDNN header / library paths fix

- theano/sandbox/rng_mrg.py
This change fixes issue #4098 , in which rng_mrg.py was no longer using CUDA at all due to a stale import of `cuda_enabled`. Apparently, a recent commit (adb02ac) changed the timing of some imports, which exposed this existing "import of a mutable variable" bug.
Testing: ran the minimal test case in #4098 and ran `theano/sandbox/test_rng_mrg.py`.
fix gh-4098
> Fix stale import of cuda_enabled in rng_mrg.py (#4098)

- bin/theano-cache
I don't know when that changed, but it is now necessary.
> We need to import gof.compiledir in theano-cache.

- theano/sandbox/cuda/blocksparse.py
- theano/sandbox/cuda/tests/test_blocksparse.py
- theano/tensor/nnet/blocksparse.py
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_blocksparse.py
I couldn't fix the direct problem with #3978, but I noticed that there was no infer_shape or proper equality functions.
In addition I changed the subtensors in h_softmax to dimshuffles since they are lighter to perform.
I also fixed the broadcastable handling in CPU ops since that was needed for the dimshuffle change.
With all these changes the problem goes away and the graph looks leaner, so I would say that it's a fix.
> Fix blocksparse

- theano/tensor/nnet/opt.py
With https://github.com/Theano/Theano/pull/4045, Windows users without BLAS don't get an `undefined reference to _dgemm` any more, but another error message that's not too useful either: https://groups.google.com/forum/#!topic/lasagne-users/LrP3YGzh8f0
This adds a hint about installing a BLAS library.
/disclaimer: I did this in the github web interface, hope I didn't introduce any syntax error.
> More hints for failed AbstractConv2d optimization

- doc/library/config.txt
Fixed the typo noted in #4182, and improved the documentation of the `config.dnn.enabled` (cuDNN) flag.
fix gh-4182
> Fix typo and clarify cuDNN config documentation

- theano/sandbox/cuda/blas.py
- theano/sandbox/cuda/tests/test_blas.py
Fixes #3512. I switch between the two implementations based on the number of multiplications per `cublasSgemm` call; if that is large then the streams implementation is used. The next step would be to tweak the threshold according to measurements.
> GpuBatchedDot: streams implementation (WIP)

- theano/sandbox/cuda/tests/test_abstractconv.py
- theano/sandbox/gpuarray/tests/test_abstractconv.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/tests/test_abstract_conv.py
Otherwise, if they are symbolic variables, they could be
used during shape inference, which could introduce dependencies
on variables outside of the graph.
I'm not sure what the best way of raising the exception again with a different error message should be.
> Make sure imshp and kshp are constant

- doc/library/config.txt
Fixed the typo noted in #4183, and improved the documentation of the `config.lib.cnmem` (CNMeM) flag.
> Fix typo and clarify CNMeM config documentation

- theano/tensor/tests/test_gc.py
Increased the tolerance of the test, due to reported false positives.
fix gh-4196
> (#4196) increase the tolerance of test_gc_never_pickles

- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/nvcc_compiler.py
Fixes compilation failure introduced in #4208, mentioned in https://github.com/Theano/Theano/pull/4208#issuecomment-195521755.
Warning: This does not address the changes in the new backend. Let me know if I can easily extend this PR, or feel free to create your own PR based on mine.
> Pass -rpath to linker only, not to compiler

- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/nvcc_compiler.py
- theano/sandbox/gpuarray/dnn.py
This completely fixes the -rpath problem and it works on mac and linux, with or without cudnn present.
I might add a few fixes for windows onto this later (if it isnt merged yet).
> Fix the last problems identified for the release.

- theano/sandbox/cuda/tests/test_opt.py
Erfinv on the CPU need scipy. It isn't in numpy.
> Fix test for release when scipy isn't there.

- theano/sandbox/cuda/type.py
Python 3 does not necessarily set `__file__` when importing (See [Python documentation](https://docs.python.org/3/reference/import.html#__file__)), and it happens that it is not set on my system (Windows 10, Python 3.4) and causes an exception.
> Manually set cuda_ndarray.__file__ if it is absent

- theano/sandbox/cuda/nvcc_compiler.py
Due to the '-rpath,' option is not understood by the Microsoft linker, I add an judgement to ignore this linker option when running in Windows System. Please see the code for details.
Best wishes,
Mang
> Repair the -rpath linker option in Windows System

- theano/compat/__init__.py
- theano/sandbox/cuda/nvcc_compiler.py
`nvcc` calls `cl` (Visula Studio C/C++ compiler), and `cl` outputs are in "current ANSI console codepage" (see [Visual Studio Documentation](https://msdn.microsoft.com/en-us/library/xwy0e8f2%28v=vs.120%29.aspx)). If the encoding is not UTF8 and the output contains non-ASCII characters (very likely to happen if the VS installation is in Asian languages), the default `decode()` will result in an exception.
There had been an issue #3551 that reported the problem, but remained untreated for long.
This pull request fixed the problem by adding a function that can decode in specified encoding and compatible with both Python 2 and 3, and detecting encodings of stdout and stderr.
> Decoding nvcc outputs in correct encoding.

- theano/sandbox/cuda/corr3d_gemm.cu
- theano/sandbox/cuda/corr_gemm.cu
This patch fixes some `UnicodeDecodeError` exceptions due to accents in Cuda files. 
I encountered this issue on a fresh Python 3.5 install.
> [MRG] UnicodeDecodeError exceptions due to accents

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
This adds an optimizer merging switch(c, a, b) + switch(c, x, y) into switch(c, a+x, b+y), for all elemwise Ops of two inputs I could think of. Probably many of them are not practically relevant, but do you see any potential performance problems from implementing it this way? I.e., should we reduce this to a few relevant Ops, or implement it such that it looks for a `T.switch` first?
Closes #3742.
> Add optimizer merging two switches of same condition

- theano/tensor/nnet/tests/test_nnet.py
- theano/tensor/opt.py
Add a test that this is enough to solve the binary_crossentropy(reshape) case.
Follow-up to #4216, finally fixes #4086.
> Add local_zero_div to specialize phase

- bin/theano-test
- doc/dev_start_guide.txt
- doc/extending/unittest.txt
- doc/install.txt
- doc/install_windows.txt
- doc/links.txt
It was referring to some pharma website, not the nosetest homepage
> fixed nosetest doc

- theano/gof/cmodule.py
This PR is related to the issue https://github.com/Theano/Theano/issues/4307.
> Adding clang-omp++ as an alternative compiler to clang++ as it suppots OpenMP

- theano/sandbox/cuda/basic_ops.py
This could cause bad value at other time. It currently crash when sA0 is negative. If you understand why this fail, it would be great to know. Maybe we should make ths work around elsewhere.
The new GPU back-end use this code and don't have this problem. But it use g++ to compile instead of nvcc.
> Fix crashes probably due to nvcc not handling unsigned int as we expect

- theano/sandbox/cuda/basic_ops.py
- theano/tensor/tests/test_subtensor.py
It fail in GpuArray on my computer and I don't understand the error:
```
E
======================================================================
ERROR: test_adv_sub1_broadcast (theano.sandbox.gpuarray.tests.test_subtensor.G_subtensor)
----------------------------------------------------------------------
File "/u/bastienf/repos/Theano/theano/tensor/tests/test_subtensor.py", line 543, in test_adv_sub1_broadcast
g_0 = g([0])
File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 871, in __call__
storage_map=getattr(self.fn, 'storage_map', None))
File "/u/bastienf/repos/Theano/theano/gof/link.py", line 314, in raise_with_op
reraise(exc_type, exc_value, exc_trace)
File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 859, …
```
> Fix crash in GpuAdvanvedIncSubtensor1 when unbroadcasting the value.

- theano/sandbox/gpuarray/blas.py
- theano/sandbox/gpuarray/opt.py
- theano/sandbox/gpuarray/tests/test_blas.py
- theano/tensor/blas.py
Add GpuGemmBatch op in the gpuarray backend. Includes optimizations and tests. Depends on Theano/libgpuarray#142, solves #3946.
Please double-check the `perform` implementation.
> gpuarray GpuGemmBatch op

- theano/gof/opt.py
- theano/tensor/tests/test_opt.py
Modified test_opt.py to use check_stack_trace and modified check_stack_trace to loop over outputs for ops_to_check=last and some refactoring
fix #4379
> Make stack trace tests in `tensor/tests/test_opt.py` use `check_stack_trace`.

- theano/tensor/basic.py
- theano/tensor/extra_ops.py
- theano/tensor/tests/test_extra_ops.py
- theano/tensor/var.py
Includes:  
* A `SearchsortedOp`, which includes `perform` and `c_code`
* A `searchsorted` function with numpy-equivalent call
* A method in tensor's basic methods which redirects to `searchsorted` with numpy-equivalent call to ndarray's method
* Unit tests for `SearchsortedOp`'s functionalities
Currently, `side` string argument is being given to SearchSortedOp as an init argument. A param version is not implemented in this patch.
> Develop SearchsortedOp to wrap numpy's searchsorted function

- theano/compile/function_module.py
This patch is intended to resolve #4445.
The added code basically adds argument name to the error message and removes weird trailing space in function name for the same error message.
The example traceback is as follows:
```
File "script.py", line 28, in <module>
y = predict(X)  # y = T.dot(X, W) work fine
File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/compile/function_module.py", line 821, in __call__
allow_downcast=s.allow_downcast)
File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/tensor/type.py", line 87, in filter
'Expected an array-like object, but found a Variable: '
TypeError: ('Bad input argument with name "X" to theano function with name "script.py:26" at index 0(0-based)', …
```
> adding variable name in error messages raised by calling a function

- theano/d3viz/d3viz.py
- theano/d3viz/html/template.html
This fixes #4510 for me. The issue is hard to reproduce - the example from #4510 worked on another machine with CNMeM disabled and a different CuDNN version. But I think using JSON instead of hand-rolled escaping is better anyways. The only tricky part is `<` escaping; it is copied from https://github.com/scrapinghub/splash/pull/386.
> d3viz: fix escaping of dot graph

- theano/compile/sharedvalue.py
The container is checked not None for twice
> remove redundant container checking.

- theano/sandbox/cuda/opt.py
add 'assert_no_cpu_op' as a tag instead
Fix #4531.
> Change name of assert_no_cpu_op in old back-end as well

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> In get_scalar_constant_value, do not return internal memory of constant

- theano/tensor/slinalg.py
The existing `CholeskyGrad` implementation is implemented with triply nested Python loops which is very slow as noted in #2058, #207 and #208. It also does not have a `grad` method specified meaning it is not possible to differentiate through a `Cholesky` op multiple times. Given it is an atomic op defined directly in python it will also not be optimised to run on the GPU.
There has recently been a [note put on arXiv](http://arxiv.org/abs/1602.07527) giving a simple symbolic expression for the reverse-mode gradient updates for the Cholesky decomposition, which has been used to update the Cholesky gradient implementations in [autograd](https://github.com/HIPS/autograd/commit/024909c58f53b84f5a1c1ab60488c4668284898c#diff-580a144ef545fa15f38dd963feb9aa80) (just for full disclosure, the …
> Symbolic Cholesky gradient implementation

- doc/library/tensor/basic.txt
> [nit] Fix typo in tensor/basic.txt: lacks a space

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Progress on issue #4421:
fix #4421
> keep stack trace: fix optimizations or tests (tensor/tests/test_opt.py)

- theano/tensor/slinalg.py
- theano/tensor/tests/test_slinalg.py
Current `tensor.slinalg.Solve` has no `grad` method implemented as noted in #1567 and #4148. This in particular in response to #4148 as implementing the reverse-mode gradient updates for `Solve` is needed to allow arbitrary order differentiation through the `Cholesky` op as noted there.
This implements the reverse-mode gradient updates for the `Solve` op using the symbolic expressions given in [Giles (2008)](http://eprints.maths.ox.ac.uk/1079/). It exploits triangular structure in the input matrix (first input) if specified by the `A_structure` argument, or defaults to a general dense implementation for other `A_structure` values.
A unit test performing a series of `verify_grad` checks for different input dimensions and matrix structures is also defined.
> Gradient implementation for Solve op

- theano/tensor/basic.py
As found out with @lamblin and @abergeron in the magic night before NIPS's deadline, Theano does not propagate the error message correctly when something fails in max or argmax. This PR fixes it.
> Do not hide errors in max and argmax

- doc/install.txt
The CUDA Docker images are moving to use the NVIDIA Docker program, so I've updated the docs appropriately.
> Update Docker instructions

- doc/extending/extending_theano.txt
There was a repetition there and I removed it. I don't think this is being covered in any of the on-going documentation work.
> Removed repetition

- doc/library/config.txt
Load `.theanorc` configuration file in the current working directory similar to [matplotlib](http://matplotlib.org/users/customizing.html#the-matplotlibrc-file).
> Support .theanorc files in the current working directory

- theano/sandbox/cuda/tests/test_dnn.py
cuda/test_dnn now takes up to one hour instead of days on a GTX 680/750.
> Set cuda/test_dnn to run conv references in fast run

- doc/LICENSE.txt
Numpy has changed copyright dates to 2005-2016. [Numpy License](https://github.com/numpy/numpy/blob/master/LICENSE.txt)
> Updated Numpy copyright dates

- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/tests/unittest_tools.py
Follow-up of #4237. Took the patch by @lachlants (https://github.com/Theano/Theano/pull/4237#issuecomment-223466380) and cleaned up / rewrote most of the code so I could understand what it was doing. I guess it was originally derived from the softmax Ops, using `if`s in the base class were inheritance would have made it much easier (so I changed it accordingly).
As per @lachlants idea, this does not cope with updating the running average statistics in the training forward pass, but just hands out the current mini-batch statistics so the user can do whatever she or he pleases. This makes it much easier for the initial version.
Still misses tests, but I've written a small test script to verify that it does the correct thing for all three Ops (will still add tests, of course). Also misses a …
> cuDNN v5 Batch Normalization

- theano/gof/op.py
the types were printed in the wrong order before.
> fixed error message in op.py

- theano/gpuarray/dnn.py
- theano/sandbox/cuda/blas.py
- theano/sandbox/cuda/corr_gemm.cu
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_abstractconv.py
- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/corr_gemm.c
- theano/tensor/nnet/opt.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
Comments:
- For some reason when tensor.nnet.conv2d is called then convop is implemented with the debug slow version in abstract_conv.py. Modified already opt.py (both cpu and gpu versions) and dnn.py (both gpuarray and cuda). The idea is that whenever tensor.nnet.conv2d is called we need to check wether there is dilation and if there is the call conv_gemm implementation. 
- Following the previous point, the TestDnnConv2d in test_sandbox/cuda/tests/abstractconv.py fails. The reason is the use of cuDNN implementation of dilated architectures in tests (should we skip them or adapt with the abstract iface?)
> Implementation of 2D dilated convolution/correlation.

- theano/gof/cmodule.py
- theano/tensor/blas_headers.py
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/corr_gemm.c
Hi experts,
This PR is to optimize current corr_gemm Ops (including corrMM, corrMM_gradWeights and corrMM_gradInputs), which uses openmp to unroll the first loop (batch size level), and it turns out 5.2x (count all these three Ops in) speedup compared than original version.
Thanks.
Ciyong
> corr_gemm optimization to improve CNN performance

- theano/misc/elemwise_openmp_speedup.py
The current elemwise_openmp_speedup.py will output the following error when used with Python 3.5.1:
```
File "lib/python3.5/site-packages/theano/misc/elemwise_openmp_speedup.py", line 35, in <module>
(cheapTime, costlyTime) = runScript(N=options.N)
File "lib/python3.5/site-packages/theano/misc/elemwise_openmp_speedup.py", line 26, in runScript
return list(map(float, out.split(" ")))
TypeError: a bytes-like object is required, not 'str'
```
Quick testing shows this to be the expected exception when calling split() on a bytes object. Calling decode() on the bytes object fixes this for Python 3, and seems to still work fine in my Python 2.7.11 install.
> Decode bytes to string before split

- theano/gpuarray/tests/test_basic_ops.py
> gpuarray tests should pass when floatX=float32 and add this to the daily buildbot

- theano/gpuarray/neighbours.py
This commit adds OpenCL support for Images2Neibs class. The original Images2Neibs 
kernel was CUDA only, and this patch modifies the kernel so that it is 
compatible with both OpenCL and CUDA with the help of libgpuarray backend.
Also the originally hard-code max threads per block (512) was replaced by
reading the actual max threads per block from the device. On modern Nvidia cards
this number is 1024, so performance should actually improve a little bit.
All modifications shouldn't adversely affect the performance of the original kernel in any ways.
During the development of this OpenCL kernel, a bug of libgpuarray was found and 
was fixed in commit f8b8e156c. So you will need the latest libgpuarray to test the code.
I have tested my code on a AMD R9 280X and a Nvidia Tesla K40c. On the …
> OpenCL support for Image2Neibs kernels

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
This pull request addresses issue #4662 by taking the desired shift modulo the axis size. It also adds tests to verify the correct behavior.
> Use shift modulo axis size to handle large shifts in theano.tensor.roll

- theano/sandbox/cuda/__init__.py
There are no functional changes. I simply fixed a few linting errors.
Several lines in this file were over or under indented. I fixed these 
without moving lines over the 80 character limit. 
There was trailing whitespace. I simply removed it.
I fixed quote consistency. There seems to be a convention that message strings use double quotes and key/flag strings use single quotes. I changed a logging message that used single quotes to use double quotes. 
The biggest change is that there were a few multiline strings of C code defined within functions. 
The multiline strings were indented all the way to the left, which breaks visual nesting of 
python indentations. I used the builtin textwrap.dedent function to indent these 
lines of code while still preserving the original string …
> Linting: Pep8 indentation, consistent quotes

- theano/tensor/nnet/conv3d2d.py
- theano/tensor/nnet/tests/test_conv3d2d.py
This patch adds support for `border_mode='full'` to the 3D convolution in `tensor.nnet.conv3d2d`.
`tensor.nnet.conv2d` already provides full convolution for the H and W dimensions, so the code only has to be changed to support full convolution in the time dimension. I've implemented this by padding the stacked 2D output with zeros using `set_subtensor`. Summing over the output of `DiagonalSubtensor` then provides the result of a full convolution. This approach, unfortunately, requires an additional, temporary array for `set_subtensor`.
> Full 3D convolution for conv3d2d

- .travis.yml
- theano/tensor/tests/test_subtensor.py
- theano/tensor/var.py
Ellipsis is automatically replaced by an appropriate number of newaxis constants up to the number of dimensions of the argument.
This is a rebase of @NeilGirdhar's PR #4840, but skipping a case instead of bumping the required version of numpy.
> Allow indexing using Ellipsis.

- theano/scan_module/scan_op.py
This was probably causing a different order of operation
during gradient computation in scan for each run. With this
fix I'm able to finally reproduce results on my RNN system.
Can be related to #4770 as well.
> scan/scan_op: Convert known_grads to OrderedDict

- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/tests/test_abstract_conv.py
I think there are a few bugs in commit bbc749ab516 (e.g., lines [1116-L1119 of abstract_conv.py](https://github.com/ballasn/Theano/blob/bbc749ab516a1242d5eb359d1d34cf5fbd031167/theano/tensor/nnet/abstract_conv.py#L1116-L1119), see also #4846), which would give problems with non-symmetric filter dilations for border_modes full or half and with custom padding (which should not be multiplied with the dilation factor).
These errors would have been visible only in the debug mode, if the test had worked. It seems that the test only used the default `border_mode = 'valid'`, but the errors occur with `full` and `half`. This commit should fix that.
Finally, this commit adds `border_mode = "half"` to the tests.
> Fix abstractconv_grad dilation and enable border_mode tests

- doc/dev_start_guide.txt
Plugins will not load without calling `vundle#end()`
> Modified Developer Start Guide VIM instructions

- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_nnet.py
Fixes issue #3637. This is simply a rebase of #4100 plus updated example to match sklearn.confusion_matrix very closely. API signature is the same as sklearn.confusion_matrix:
`def confusion_matrix(actual, pred)`
> Confusion matrix 

- theano/sparse/tests/test_basic.py
- theano/sparse/tests/test_sp2.py
- theano/tensor/raw_random.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_extra_ops.py
- theano/tensor/tests/test_raw_random.py
- theano/tensor/tests/test_shared_randomstreams.py
- theano/typed_list/tests/test_basic.py
This should be a comprehensive for the warnings in numpy 1.11.
> Use randint() instead of random_integers() in the tests.

- doc/extending/extending_theano_gpu.txt
- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/tstgpueye.c
This comes with tests and docs changes.  This also updates GpuEye to use it so that we have a real-world example.
I did this in preparation of the CorrMM port but this is a worthwhile improvement regardless.
> Add a wrapper function for kernels to simplify calling.

- theano/d3viz/formatting.py
I tried to visualize a Theano computation graph build with Keras by accessing it through `model.train_function.function`. I am not exactly sure what happens, but instead of a single trace tuple a list of tuples gets returned (each one containing a path, line, module, src). This results in the following exception.
```
File "./train.py", line 203, in <module>
d3v.d3viz(model.train_function.function, 'd3v_model.html')
File "/usr/local/lib/python2.7/dist-packages/theano/d3viz/d3viz.py", line 79, in d3viz
graph = formatter(fct)
File "/usr/local/lib/python2.7/dist-packages/theano/d3viz/formatting.py", line 199, in __call__
vparams['tag'] = var_tag(var)
File "/usr/local/lib/python2.7/dist-packages/theano/d3viz/formatting.py", line 311, in var_tag
path = …
```
> Fix d3viz multi-level/inheritance tags

- .travis.yml
We can't do the reverse. conda don't have more recent NumPy and SciPy version for python 3.3
> Test min version and more recent version of NumPy and SciPy.

- doc/tutorial/examples.txt
Creating `null_accumulator` raises an error because it does not use `inc`. The `on_unused_input='ignore'` argument fixes the error (see issue [here](https://github.com/Theano/Theano/issues/4980)). This is fixed after Theano 0.8.2.
> Fixed UnusedInputError in Tutorial

- theano/compile/debugmode.py
- theano/gof/cc.py
- theano/gof/op.py
- theano/printing.py
- theano/scalar/basic.py
- theano/tensor/elemwise.py
- theano/tensor/opt.py
Fix some compilation getting killed.
I does this. The error was related to the elemwise fusion. I postpone some work from Composite.__init__ to later when we use it as all the stack trace we got when doing CTRL-C during the execution was there. This should speed up compilation, but it also fixed the crashes.
> Postpone Composite name creating

- theano/tensor/nnet/conv3d2d.py
- theano/tensor/nnet/tests/test_conv3d2d.py
This adds support for `border_mode = 'half'` to the `conv3d2d.conv3d` method. `border_mode = 'half'` is already supported by `nnet.conv2d`.
This pull request also adds a number of test cases for the method. The existing tests only evaluate odd-sized filters, so I borrowed some code from `sandbox.cuda.test_dnn` to test with even filters as well.
> Half 3D convolution for conv3d2d

- theano/sandbox/cuda/cuda_ndarray.cu
I had this happen one too many times to me (not counting that even when it doesn't segfault it pollutes the output of cuda-memcheck with a bunch of fake errors.  Anyway here is a long explanation of why it happened from the commit:
The problem is that the old backend assumes it is alone in the
universe and even when not in use will interact with the gpu.  Most
notably in this case it will forcibly destroy any primary context on
exit.  The only problem is that we are also using the primary context
and our cleanup handlers run after those of the old backend.
This is a major problem because cublas uses the runtime api which will
create a context whenever it thinks it needs one (like for cudaFree).
However all the allocations are from the old context that the old
backend destroyed.  So when …
> Fix random segfault on exit when the new backend is in use.

- theano/gradient.py
Fix Lop to comply with new requirement that theano.grad's known_grad argument be an OrderedDict.
> Fix crash in Lop

- theano/gpuarray/dnn.py
This is one way to fix #4978. It works for me, at least, and it seems logical if the OpenCL library is less dependent on a specific GCC version.
> gpuarray: Do not pass config.nvcc.compiler-bindir to g++

- theano/gof/destroyhandler.py
Change datastructure to a deque that is faster. Queue is for multi-thread communication with automatic locking (so slow down execution for feature we don't need)
> Faster compilation: use a deque instead of Queue.

- .jenkins/jenkins_buildbot_python2_32bit.sh
- theano/gof/cmodule.py
- theano/sandbox/cuda/nvcc_compiler.py
Compiler._try_compile_tmp did not use compile_args. The -m32 flag was missing in the gcc args for 32 bit platforms, preventing the correct BLAS from being linked.
> Add compile_args to Compiler._try_compile_tmp

- theano/misc/windows.py
Fix #4832.
Removes redundant code in `output_subprocess_Popen` and properly closes os.devnull in `subprocess_Popen`.
> Close os.devnull if opened

- .jenkins/jenkins_buildbot_python2.sh
Nose doc says it's an option, but nosetests gives a option doesn't exist error, same version.
> remove nose testsuite prefix option

- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_32bit.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- .jenkins/jenkins_buildbot_python3.sh
With Ubuntu 16, jenkins no longer seems to source the bashrc properly for CUDA paths.
> buildbot explicit cuda path

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
Here's a little patch that would add 5d support to the GPU batch normalization ops (see #4931).
The tests pass now, but I'm not really sure about the tolerances used in the tests. Some tests would fail with what seemed to be relatively small differences. Using larger input values and changing some of the atol/rtol values fixed that.
> GpuDnnBatchNorm with 5d inputs

- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/sandbox/cuda/tests/test_gemmcorr3d.py
- theano/tests/test_gradient.py
This removes a number of unnecessary calls to the old Conv3D implementation from the tests, replacing them with calls to Corr3dMM instead. Could be part of #5079.
> Replace Conv3D references in tests with Corr3dMM

- theano/gof/fg.py
In the new gpu back-end, we move the full graph at once to the GPU. So the recursion during the removal of the full graph was hitting python recursion limit. Change the logic to recur manually.
Also, simplify the logic. This also change when on_change_input is called. It was called after the node was changed, but remove all the useless nodes/var where removed from the graph. Now we call it after all the nodes are removed from the graph. This make the logic simpler. I don't see any problems with that change of logic and hopefully the subset of tests I ran was enough.
> Fix recursion limit that happen in the new gpu back-end

- theano/gpuarray/blas.py
- theano/gpuarray/corr3d_gemm.c
- theano/gpuarray/corr_gemm.c
- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_abstractconv.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/gpuarray/tests/test_gemmcorr3d.py
This adds the GpuCorrMM and GpuCorr3dMM ops from sandbox.cuda to the new gpuarray backend. It also applies the nnet.conv2d to dnn_conv / GpuCorrMM and nnet.conv3d to dnn_conv / GpuCorr3dMM optimizations.
This pull request uses code from the AbstractConv3d pull request #4862, so that should be merged first. (The very last patch in this long list adds the GpuCorrMM ops, all the other patches are from #4862.)
> GpuCorrMM and GpuCorr3dMM in new backend

- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr3d.py
This makes the 3d convolution/correlation test examples somewhat smaller. Especially reducing the very large input for verify_gradient in the corr3d tests saves a lot of time.
> Somewhat smaller/faster 3d convolution tests

- theano/tensor/opt_uncanonicalize.py
- theano/tensor/tests/test_opt_uncanonicalize.py
PR for new optimization dealing with 
`dimshuffle{x, 0, 1}(alloc([3 4], 3, 2) => alloc([3 4], 1, 3, 2)` 
in uncanonicalize phase
gh-5024
> New optimization: DimShuffle(Alloc(...)) -> Alloc(..., use dims of 1 for new dimensions) #5024

- theano/sandbox/cuda/opt.py
The `local_gpu_solve` optimizer inserted `GpuSolve` even if `GpuSolve` was not usable due to a missing CULA library, causing an exception later on. This PR adds a check to insert `GpuSolve` only if it can be used.
> Insert GpuSolve only when CULA is available

- doc/library/config.txt
Doc had two nan_is_error attributes. One of them should be big_is_error.
> Fixed typo in config doc

- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
This should rename the following pooling parameters for `pool_2d`, `pool_3d` and `Pool` (see #4933):
- `ds` to `ws`
- `st` to `stride`
- `padding` to `pad`
It keeps the old named parameters for backwards compatibility, but these will produce a warning.
> Deprecate ds, st, padding parameters in pooling

- theano/gpuarray/blas.py
- theano/gpuarray/corr3d_gemm.c
- theano/gpuarray/corr_gemm.c
- theano/gpuarray/tests/test_gemmcorr.py
- theano/gpuarray/tests/test_gemmcorr3d.py
@aam-at noticed that the number of threads and the number of blocks were swapped in the kernel calls for `corr3d_gemm.c` and `corr_gemm.c`. This PR corrects this. It also adds two tests with larger inputs to check the correction. (The tests don't really take a lot of time, they are just a little bit too large.)
> Correct blocks/threads for gpuarray CorrMM and Corr3DMM

- theano/sandbox/cuda/opt.py
It was using the one from GpuFromHost instead of AdvancedIncSubtensor1.
This was caught by tests in DebugMode.
This issue was introduced on Sept. 19th by d0d006f44f3b857e160ffd60d45cce2f7cd8838e, should we add a warning?
> [REG,BUG] Use _props_dict() from the right Op.

- theano/compile/profiling.py
- theano/gof/vm.py
This will help user find the strange profiling information themself without asking questions.
> warn when profiling.ignore_first_call isn't used.

- theano/tensor/basic.py
- theano/tensor/nnet/tests/test_nnet.py
- theano/tensor/opt_uncanonicalize.py
Is it a good idea to try to access the already computed indices instead of calculating the max in the case of `eval_max=True` and `eval_argmax=True`?
Fixes #5147.
> Option to evaluate part of the max-and-argmax on cpu

- theano/misc/tests/test_pycuda_theano_simple.py
Update test function test_pycuda_memory_to_theano() to fix Python 3 error.
The refcount of a variable seems to be different between Python 2 and Python 3. So it seems better to stock an initial refcount in a variable and then do the checkings with that variable instead of directly using comparing to constant values.
Tests passed with Python 3 (Anaconda):
```
$ nosetests --verbose --nocapture theano/misc/tests/test_pycuda_theano_simple.py
Run pycuda only example to test that pycuda works. ... ok
Simple example with pycuda function and Theano CudaNdarray object. ... ok
theano.misc.tests.test_pycuda_theano_simple.test_pycuda_memory_to_theano ... 4
gpuarray ref count before creating a CudaNdarray 4
strides (20, 5, 1)
gpuarray ref count after creating a CudaNdarray 5
gpuarray ref count after …
```
> Update to fix python 3 error

- theano/gpuarray/__init__.py
This update allows Theano to print PCI bus ID for the GPU card (related to issue #5176 ).
This will works with CUDA devices and with the last version of libgpuarray ( see this pull request: https://github.com/Theano/libgpuarray/pull/283 ).
OpenCL devices are currently not supported (an "unsupported" message should be printed).
Tested on both Python 2 and Python 3. On my computer:
NVIDIA infos:
```nvidia-smi```:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 370.28                 Driver Version: 370.28                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | …
```
> Pci bus ID now printed for GPU cards

- doc/install_others.txt
Added small section on AWS Marketplace AMI for Theano by Bitfusion. This was okayed by nouiz a couple months ago in the google group: https://groups.google.com/forum/#!searchin/theano-users/AMI%7Csort:relevance/theano-users/bZczMYoqdFU/gXEdvohhBAAJ
> AWS Marketplace AMI install doc section

- theano/gpuarray/opt.py
Since gpu_elemwise_alloc is reused from tensor, I've ported it
I've looked at local_gpu_extract_diagonal, but since we don't have extract_diag, there is little point for now.
> Port opt from the old backend.

- .travis.yml
Trying to add miniconda.sh to TRAVIS cache.
The goal is to avoid re-downloading of this resource for every build.
Inspired from https://github.com/travis-ci/travis-ci/issues/1510#issuecomment-26274388
Need to be tested.
@nouiz
> Add miniconda.sh to TRAVIS cache

- requirement-rtd.txt
The idea is to bypass the dependency on scipy that is in setup.py, by
- providing it explicitly in the requirement file, and
- explicitly installing theano, telling setup.py to ignore "install_requirements"
This is needed because the version of scipy on readthedocs is older than
the required one, but it is not an issue for building the doc itself.
> Fix master build on readthedocs

- theano/tensor/blas.py
(see PR #5207 and https://github.com/Theano/Theano/pull/5207#issuecomment-260430352).
In Windows there are some issues with
os.listdir(path) when path is surrounded
with quotes. So it's better to remove
quotes (if present) at the start and the end
of paths passed to this function.
Checking of ldflags parts is also modified
to better handle quotes around "-L" args.
@nouiz @mingwandroid
> Fix Windows issue related to PR #5207

- theano/sandbox/cuda/cuda_ndarray.cu
Added call to `cublasSdot` in GPU gemv code.
This is proposed solution for the 1st issue in #1168. Despite not solving all the problem, I'm getting 4x speedup on my GPU.
> GPU gemv speedup

- theano/tensor/opt_uncanonicalize.py
- theano/tensor/tests/test_opt_uncanonicalize.py
Note: I also fixed some things I found were not good on my previous gh-4647 tickets. I mistakenly used the same name twice for a test.
This does crash into an error but I don't know how to fix it. I tried to give back a new Subtensor object then realized that this could not be done as it would lack the inputs! So I tried to modify directly the Subtensor.idx_list and then replace the dimshuffle with its Subtensor.idx_list changed input, but it throws an error...almost there!
gh-4647
> Dimshuffle{0,2}(Subtensor[i:j, :, k:l]) => Subtensor[i:j, 0, k:l] #4647

- doc/faq.txt
- doc/library/config.txt
- doc/troubleshooting.txt
- doc/tutorial/using_gpu.txt
Comments in the theano documentation that config.lib.cnmem affects only the old back-end, and that config.gpuarray.preallocate is its new-backend equivalent.
fix gh-5186
> Clarify GPU memory pre-allocation in new and old backend

- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
Moved the make_node() from the base class "mrg_uniform_base" to the derived classes ( CPU, old GPU and new GPU backend) to avoid incorrect dtype settings for "rstate"
fix gh-4916
> fix crash in MRG_RandomStreams with the new backend

- theano/gpuarray/blas.py
Similar to #5257, this PR applies to the new backend.
~~**ONLY merge this after libgpuarray-294 is merged.**~~
To test this, newer `libgpuarray` with [this PR](https://github.com/Theano/libgpuarray/pull/294) merged is needed.
Results of running [this](https://gist.github.com/khaotik/9c7c72e562a919e241c9a09522fc4df5) test script on my laptop (GeForce GT 650m):
(time used in seconds, lower is better)
Before:
```
scan with dot  |  scan with sum   |  full unrolled
3.502193689346  |  0.411211490631  |  0.089465141296  
1.447018623352  |  0.412187576294  |  0.086945295334  
1.446414470673  |  0.411444425583  |  0.089369773865  
1.447574138641  |  0.413084506989  |  0.091281890869  
1.452363491058  |  0.412972927094  |  0.088017463684  
...
```
After:
```
scan with dot  |  scan with sum   | …
```
> GPU gemv->dot speedup for new backend

- theano/gof/opt.py
- theano/gof/tests/test_opt.py
At the moment `Assert`s are not being merged at all. This seems to be deliberate (#3344) because the fancy condition-merging logic caused problems. However, and this may be incorrect, it seems to me that merging identical Asserts shouldn't be a problem.
This patch re-enables merging of Asserts if they are identical, by temporarily disabling their special treatment. Since they're currently not being merged on a condition level, they should be treated like any other node.
Does that make sense? It seems to solve my problem in #5267.
> Still merge identical Asserts while Assert merging is disabled

- theano/gpuarray/elemwise.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_elemwise.py
Create GpuErfinv and GpuErfcinv in `theano.gpuarray.elemwise`. These ops currently only works with CUDA (OpenCL does not currently provide `erfinv` and `erfcinv` functions).
Make sure these GPU ops return the same values as CPU (`scipy.special`) equivalent ops. Currently:
* erfinv is defined in `]-1;1[`. CUDA returns `-inf` and `+inf` if input is -1 and 1, and NaN for any other input outside the domain of definition. Scipy returns `-inf` if `input <= -1` and `+inf` if `input >= 1`.
* erfcinv is defined in `]0;2[`. CUDA returns `+inf` and `-inf` if input is 0 and 2, and NaN for any other input outside the domain of definition. Scipy returns `+inf` if `input <= 0` and `-inf` if `input >= 2`.
So, the code adds checkings to ensure that both GPU and CPU ops return the same values, that is …
> Port erfinv and erfcinv to new backend.

- doc/conf.py
- doc/library/tensor/basic.txt
- theano/gpuarray/dnn.py
- theano/gradient.py
- theano/printing.py
- theano/sandbox/cuda/dnn.py
- theano/tensor/extra_ops.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/nnet.py
- theano/tensor/slinalg.py
- theano/tensor/var.py
Travis fails with this error:
```
$ if [[ $DOC == "1" ]]; then python doc/scripts/docgen.py --nopdf --check; fi
Running Sphinx v1.5
Warning, treated as error:
WARNING: latex_font_size is deprecated. Use latex_elements['pointsize'] instead.
```
> Sphinx doc/conf: latex_font_size is deprecated

- theano/gpuarray/dnn_softmax.c
- theano/gpuarray/dnn_softmax_grad.c
- theano/gpuarray/tests/test_dnn.py
This directly returns the zero-length output to avoid a cuDNN error. (See also #5341.)
fix gh-5341
> Handle zero-length dimensions in GpuDnnSoftmax

- theano/compile/ops.py
- theano/gpuarray/fft.py
- theano/gpuarray/neighbours.py
- theano/gpuarray/pool.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/type.py
- theano/sandbox/cuda/basic_ops.py
- theano/sandbox/cuda/neighbours.py
- theano/scan_module/scan.py
- theano/scan_module/scan_op.py
- theano/sparse/basic.py
- theano/sparse/tests/test_basic.py
- theano/tensor/basic.py
- theano/tensor/blas.py
- theano/tensor/elemwise.py
- theano/tensor/extra_ops.py
- theano/tensor/fft.py
- theano/tensor/fourier.py
- theano/tensor/opt.py
- theano/tensor/raw_random.py
- theano/tensor/signal/pool.py
- theano/tensor/subtensor.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_elemwise.py
- theano/tensor/tests/test_opt.py
- theano/tensor/type_other.py
- theano/typed_list/tests/test_basic.py
This fixes #5274.
For integer types, any string-based type-checking (like `'int' in dtype`) is now replaced with a list-based type-checking (like `dtype in list`) using the types lists provided in `theano.tensor` (int_dtypes, uint_dtypes, integer_dtypes and discrete_dtypes).
Remarks:
* Module `theano.sparse` have its own types lists, so they are used in that module instead of `theano.tensor` lists.
* The `discrete_dtypes` list (integer types + `bool` type) is the list to use to fix issue #5274 . When replacing string-based checkings I have tried to use that list where it seems relevant (for e.g. in some `grad()` functions) to prevent other future bugs, but I think it should be discussed.
@lamblin @nouiz !
> Update checking of integer types. 

- theano/gpuarray/extra_ops.py
- theano/gpuarray/tests/test_extra_ops.py
- theano/sandbox/cuda/extra_ops.py
- theano/sandbox/cuda/tests/test_extra_ops.py
- theano/tensor/extra_ops.py
- theano/tensor/tests/test_extra_ops.py
Changes:
- Merged `CumsumOp` and `CumprodOp` into `CumOp`
- Changed `GpuCumsum` into `GpuCumOp`, now `cumprod` is available on new GPU backend
Notes:
- `cumsum` and `cumprod` convenience functions remain syntactically same
- Should we change the name of this Op? (If you get it)
> Merge CumsumOp/CumprodOp into CumOp

- theano/tensor/opt_uncanonicalize.py
- theano/tensor/tests/test_opt_uncanonicalize.py
fix gh-5334.
We where skipping an optimization with a warning when it should have applied.
> Remove opt warning from local_dimshuffle_subtensor

- theano/tensor/blas.py
- theano/tensor/tests/test_basic.py
fix gh-4476. It is fixed by modifying contiguousity checking in the c_code of BatchedDot. Now the code uses `(PyArray_IS_C_CONTIGUOUS || PyArray_IS_F_CONTIGUOUS)` to do the checking.
Previously the code checked if every stride of the inputs is relevant (strictly positive and multiple of type size) and if at least one of the strides has the size of the type. I think the bug comes from the latter condition, as an array can be not-contiguous even if one stride has the size of the type (for example, a Fortran array in which the first dimension is contiguous but not the last ones).
Remarks:
* I put the test in `test_basic` even if `BatchedDot` is in `blas.py` because the `batched_dot` tests are also in `test_basic`.
* It seems some other codes check the contiguity using the previous …
> Fix issue #4476 related to BatchedDot.

- theano/gpuarray/dnn.py
These two patches revert two changes introduced by c6ffa46:
1. The cuDNN version check should use the correct variable name (reported in #5369). This removes an incorrect warning.
2. The `--compiler-bindir` option for `nvcc` should not be passed to the `g++` compiler. This problem was already fixed once in #4978 but reintroduced by the recent merging of #5357.
> gpuarray: Revert part of c6ffa46

- theano/ifelse.py
- theano/tests/test_ifelse.py
There is a problem with the `IfElse` gradient when the inputs are on the GPU. There's a small example below. If you compute the gradient of such an `IfElse`, the [`grad` method](https://github.com/Theano/Theano/blob/master/theano/ifelse.py#L220-L227) will construct two new `IfElse` nodes. For these new nodes, one branch will get the gradient (a GPU tensor), while the other branch gets a new variable created with `tensor.zeros_like`. Because that is not a GPU tensor, the `IfElse` will complain that the types of the return values are not the same:
```
TypeError: ('IfElse requires same types for true and false return values',
GpuFromHost<None>.0, Elemwise{second,no_inplace}.0,
GpuArrayType<None>(float32, (False,)), TensorType(float32, vector))
```
Partial example script:
```python
x = …
```
> Bug: gradient of ifelse with gpu inputs

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
When I use `T.roll(x, 1, axis=-2)` for a tensor `x` of rank `2`, it raised an error as follows:
> ValueError: The index list is longer (size 5) than the number of dimensions of the tensor(namely 3).   You are asking for a dimension of the tensor that does not exist!   You might need to use dimshuffle to add extra dimension to your tensor.
> compatible when axis < 0 in tensor.roll(x, shift, axis=None)

- theano/gpuarray/type.py
This is to fix issue #5345 . The c_code_cache_version() of GpuArrayType now depends on gpuarray ABI version instead of API version, so that cached files linked with an old gpuarray shared library will be recompiled every time the gpuarray ABI version changes. See gpuarray PR https://github.com/Theano/libgpuarray/pull/323 for new ABI methods added.
The fix works on my computer.
@abergeron @nouiz
> Change caching method of GpuarrayType to fix issue #5345

- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/test_basic_ops.py
- theano/tensor/basic.py
Hi @nouiz ,
fix #5253 , I tried to apply the same logic for GPU. I fixed the perform function and it seems to work as expected but I can not do the test as before. The reason is that we were checking if the same object is passed to the output. Since the numerical values are converted to ```<type 'pygpu.gpuarray.GpuArray'>```, it can not be compered with a ```numpy array```.  I tried to to give the input as a gpuarray by defining it as a ```shared``` variable but its type is ```<class 'theano.gpuarray.type.GpuArraySharedVariable'>```. I tried to get the ```container``` of the shared variable but : 
```
-> x.container.type 
GpuArrayType<None>(float32, (False,))
```
How do you think we should test it?
Thanks
> unstable commit-fixed perform on gpujoin

- theano/sparse/sandbox/sp2.py
- theano/sparse/tests/test_sp2.py
Fix for TypeError: Cannot cast array data from dtype('float32') to dtype('int64') according to the rule 'safe' can be fixed by making the cast explicit, casting="unsafe".
related to [5396](https://github.com/Theano/Theano/issues/5396)
> numpy 1.12.0rc2 compatibility fix related to variable typecasting

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_basic_ops.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_basic_ops.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
fix #4897 , join function is added so that we can check the number of tensors that are to concatenate. The test is also added which tests two cases. One where there are several tensors for concatenation and the other with only one tensor.
> make tensor.join() return the input when there is only 1 variable to join.

- theano/scalar/basic.py
Performances are better, as expected:
Without c code:
`THEANO_FLAGS=profile=true,cxx= nosetests -vs theano/tensor/tests/test_basic.py:RoundHalfToEvenTester`
```
Ops
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Op name>
81.0%    81.0%       0.007s       5.31e-04s     Py      14        1   Elemwise{Composite{(i0 * RoundHalfToEven(i1))}}
12.2%    93.2%       0.001s       7.98e-05s     Py      14        1   Sum{acc_dtype=float64}
5.4%    98.6%       0.000s       9.91e-05s     Py       5        5   Elemwise{round_half_to_even,no_inplace}
0.5%    99.2%       0.000s       2.50e-05s     Py       2        1   Shape_i{1}
0.5%    99.7%       0.000s       2.41e-05s     Py       2        1   Alloc
0.3%   100.0%       0.000s       1.35e-05s     Py       2        1 …
```
> Add C code to RoundHalfToEven op.

- theano/gpuarray/linalg.py
- theano/gpuarray/tests/test_linalg.py
@slefrancois 
I had to add a function similar to the one provided by scikit-cuda to wrap the call to cusolverDnSpotrs from libcusolver.
Maybe @abergeron should also take a look at this ?
For reference here are some timings for 2000 calls to solve with A with shape (150, 150) and b with shape (150, 5) (time in seconds)
('symmetric', 1.2224421501159668)
('general', 3.972813129425049)
> Cusolver using Cholesky decomposition for symmetric matrices

- theano/gpuarray/opt.py
- theano/gpuarray/pool.py
- theano/gpuarray/pool_max_rop.c
- theano/gpuarray/tests/test_pool.py
- theano/tensor/signal/pool.py
- theano/tests/test_rop.py
Continuation of #4781 and all work which was done before.
I updated max pool rop implementation which now supports arbitrary ndim for pure python and cpu openmp implementation. I also dropped support for old backend and instead added support only for new backend.
Also as a sidenote, there is a large overlap between max pooling and max pooling rop. Max pooling reduces to max pooling rop if eval point is equal to the input. For now, I didn't do any refactoring and just duplicated code for max pooling with minor changes for rop.
fix gh-4387
> Pooling rop

- .jenkins/jenkins_test1.sh
- .jenkins/jenkins_test2.sh
- theano/configdefaults.py
- theano/gof/opt.py
- theano/gof/tests/test_opt.py
Regarding issue #4734 , the default value for  `optdb.max_use_ratio`  is changed from 5 to 6 to prevent errors for some tests. For example this test:
```theano.tensor.tests.test_opt.test_local_subtensor_merge```
generated this error:
```ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_add_canonizer'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'. ```
> changed optdb.max_use_ratio to 6

- bin/theano_cache.py
On Windows, if the theano flag `device` is set to `cuda`, then the new backend raises a RuntimeError when `theano-cache` script is executed:
```
(python2) C:\Users\HPPC>set THEANO_FLAGS=device=cuda
(python2) C:\Users\HPPC>theano-cache
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
File "c:\users\hppc\mila\dev\git\theano\theano\gpuarray\__init__.py", line 164, in <module>
use(config.device)
File "c:\users\hppc\mila\dev\git\theano\theano\gpuarray\__init__.py", line 151, in use
init_dev(device)
File "c:\users\hppc\mila\dev\git\theano\theano\gpuarray\__init__.py", line 47, in init_dev
raise RuntimeError("The new gpu-backend need a c++ compiler.")
RuntimeError: The new gpu-backend need a c++ compiler. …
```
> (small fix) Update `theano-cache` to prevent an error message printed when `device=cuda` on Windows.

- doc/library/tensor/nnet/bn.txt
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_batchnorm.c
- theano/gpuarray/dnn_batchnorm_inf.c
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/tensor/nnet/bn.py
- theano/tensor/nnet/tests/test_bn.py
This is a project to define abstract batch normalization Ops that can get optimized to use the cuDNN Ops, while providing an alternative pure Theano implementation that can run on CPUs and on GPUs if cuDNN is not available.
I've started by copying the interface from the gpuarray backend, but this might also be an opportunity to improve some things.
See also issue #5187.
> Abstract Ops for batch normalization

- theano/gof/compiledir.py
Not sure if this is wanted, but one of the purposes of `theano-cache list` is to see how many Ops have been compiled for a particular function and identify opportunities for reducing the number of compilations (https://github.com/Theano/Theano/issues/1681#issuecomment-276746167). This PR adds the compilation time (the difference between finishing writing the `mod.cpp` or `mod.cu` file and finishing writing the `.so` file) to the list to make it even more useful for that purpose.
> Have "theano-cache list" include compilation times

- theano/compile/sharedvalue.py
Regarding issue #4973 , as .value raised error, part of doc string was removed.
> minor changes in doc string as .value raises error

- doc/library/config.txt
- theano/configdefaults.py
- theano/sandbox/cuda/nvcc_compiler.py
Currently the old backend is imported sometimes just to do some type checking, but when imported, it will try to compile some C code if it finds `nvcc`, and the compilation in old backend also needs the Microsoft Visual C++ compiler (`cl.exe`).
On Windows, the CUDA_ROOT contains both `nvcc` and CUDA DLL files that are required for the new backend, so that `nvcc` will be always visible in the environment, but `cl.exe` will not be always installed or visible (and the new Windows Installation documentation will not tell to install Visual C++).
Then, on Windows, this can lead to an useless compilation error, which is non-blocking, but prints about 5000 lines of C code + some annoying error messages.
This PR suggests a new flag `cuda.disable` which may be used to disable compilation in old …
> (small fix) Add new internal config flag `cuda.disable` to help disable compilation in old backend

- theano/gof/cmodule.py
- theano/gpuarray/type.py
( this is related to windows documentation PR #5433 )
Theano uses `distutils.sysconfig.get_python_inc()` to get Python headers folder (and a similar function for libraries folder), and on Windows it returns the `include` folder located inside the environment folder (e.g. `C:\donnees\programmes\Anaconda3\envs\python2\include` (PS: same value is returned when calling ` distutils.sysconfig.get_python_inc(plat_specific=True)`)).
But conda installs the `libgpuarray` package under a folder named `Library` inside the environment folder (e.g. `C:\donnees\programmes\Anaconda3\envs\python2\Library\include\gpuarray`). It seems this `Library` folder is specific to Windows, so that it is impossible to get it directly from Python.
This fix ensures that the `Library` folder on Windows is used to find …
> (small fix) Ensure Theano finds libgpuarray folders automatically in Windows with conda package

- theano/scan_module/scan_op.py
- theano/tensor/opt.py
This fix crash during execution as the cython scan was expecting a CPU value. We need it on the CPU anyway, so force that value to be always on the CPU.
> Force scan n_steps on the CPU.

- theano/__init__.py
- theano/compile/builders.py
- theano/compile/tests/test_builders.py
- theano/d3viz/formatting.py
- theano/gof/graph.py
- theano/gof/tests/test_graph.py
- theano/gradient.py
- theano/tests/unittest_tools.py
For #5225. Allowing inlined `OpFromGraph` at compile time and overriding gradient.
- ~~Refactored `OpFromGraph` into `OpFromGraphBase` (abstract) and subclass `OpFromGraphPrecompiled`,  `OpFromGraphInline`~~
- ~~`OpFromGraph = OpFromGraphPrecompiled` for compatibility~~
- OpFromGraph `__init__` method now have `inline` argument
- Can now override gradient/Rop for `OpFromGraph*` by supplying `grad_overrides` or `rop_overrides`  parameters respectively.
- Added an graph optimizer to expand inlined `OpFromGraph` at compile time.
- ~~new convenient function `op_from_graph(inputs, outputs, inline=False, grad_overrides=None, rop_overrides=None, **kwargs)`~~
- new tests for `compile/tests/test_builders.py`: `nested`, `grad_override` and `rop_override`
- tests in `compile/tests/test_builders.py` …
> Upgraded OpFromGraph with inline support and gradient override

- theano/compile/sharedvalue.py
Came across a typo in sharedvalue.py, constructor not contructor
> Typo in sharedvalue.py

- .travis.yml
- .travis/travis_install.sh
- doc/library/tensor/fft.txt
- theano/gof/cc.py
- theano/gpuarray/elemwise.py
- theano/scalar/basic.py
- theano/tensor/basic.py
- theano/tensor/elemwise.py
- theano/tensor/tests/test_elemwise.py
This is just a rebase of #5461 to see if the issue happens with the main cache.
> validate numpy1.12 compatibility changes

- theano/gof/opt.py
Regarding issue #5319 , I changed the broadcastable pattern in case of TypeError exception. In an a special case that ```dtypes, ndims``` match but the broadcastable pattern doesn't, we will try to change the broadcastable pattern of one of them to be compatible with the other one. We first check for these conditions and then call the ```fgraph.replace_all_validate``` function.
> Merge optimizer 5319

- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_multinomial_wo_replacement.py
First part of #5408, @nouiz.
I copied the same signature as the choice method in tensor/raw_random.py , which is not the same as the choice signature of the numpy function (order of a, size reversed).
Also, should I replace multinomial_wo_replacement in the tests now?
> replace multinomial_wo_replacement by choice

- doc/library/scan.txt
Change the example illustrating the effect of strict=True in the scan() doc to actually trigger the proper error. Existing example triggers a different one (non_sequences not aligned with the arguments of OneStep) if one simply omits some of the [W, bvis, bhid] from non_sequences.
> Improve the example for strict=True in the scan() doc.

- theano/gof/op.py
All generated C code uses `\n` line separators, except some in `gof/op.py` when on Windows. This fixes it.
Strangely, this also fixes the issue I described in [#5463](/Theano/Theano/issues/5463#issuecomment-279826487).
> Consistently use '\n' in outputted code

- theano/gpuarray/reduction.py
- theano/tensor/basic.py
Do not decref borrowed references.
This should close #5535.
> Fix crash due to excessive decref of 1

- theano/sparse/opt.py
- theano/sparse/tests/test_basic.py
SamplingDotCsr is [broken on negative-stride arrays](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855102) because it passes a first-in-index-order pointer to a BLAS interface that expects first-in-memory-order.  Fix this and add a negative stride test case.
Both it and UsmmCscDense also cast npy_intp* (usually int64*) to int32*, which is a strict aliasing violation (i.e. technically undefined behaviour: it currently appears to work, but might not in future compilers).  (It's also broken on big-endian systems, which is [how Debian discovered the problem](https://bugs.debian.org/831541), but those are now rare.)  Fix this by casting values instead of pointers.
(These have been tested by running sparse/tests/test_basic.py from the source tree, but *not* in a full build.)
> Fix invalid pointer casts and negative stride handling in sparse

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
In new back-end, method `GpuDnnConvDesc.make_node()` expects its input `kern_shape` to be an int64 1D tensor, but on Windows machines it seems that integers are created as int32 by default. This kind of error has already been encountered, for example here: https://github.com/pymc-devs/pymc3/pull/1550 .
On Windows it make crash this test:
```
nosetests -vs theano/gpuarray/tests/test_dnn.py:TestDnnInferShapes.test_conv_gradw_full_conv
```
For the moment, I suggest to:
* modify a line in `test_dnn` so that kern_shape is always casted to `int64`,
* clarify error message in GpuDnnConvDesc.
> Clarify error message related to expected kern_shape specs (1D, int64) in GpuDnnConvDesc

- .mailmap
- NEWS.txt
- NEWS_DEV.txt
- doc/conf.py
- doc/index.txt
- doc/introduction.txt
- setup.py
- theano/gpuarray/__init__.py
This PR prepares the release `0.9.0rc1`.
Missing: update of `Vision / State` section in `Theano/doc/introduction.txt`, and a general re-reading.
PS: For `.mailmap`, there are still few duplicated names (when running `git log --format="%aN <%aE>" | sort -u`), but it is difficult to choose the right email for these people (e.g., some of them use either `gmail` email or an email from France or other country [probably an university email]).
@nouiz @lamblin .
> Prepare release 0.9.0rc1.

- theano/sparse/opt.py
Passes PYTHONPATH=. nosetests3 -v '/home/rnpalmer/Debian/theano/theano/sparse/tests' run in the source tree, but I don't have enough RAM to test the array sizes it's supposed to fix.
There is no easily-detectable speed penalty (tested on 2048x2048 with 5% and 100% nonzero), but that might be hardware-dependent.
Note that as the out-of-bounds operation is a write, this is potentially a security issue.
Speed test was done with:
import theano
import theano.sparse
import theano.tensor
import numpy as np
import scipy.sparse
import time
n=2048
p=0.05 #also tried p=1
m1=np.random.rand(n,n)
m2=scipy.sparse.csr_matrix(np.random.rand(n,n)*(np.random.rand(n,n)<p))
x=theano.shared(m1)
y=theano.sparse.csr_matrix()
f=theano.function([y],x,updates=[(x,x+y)])
t=time.time()
z1=f(m2)
print(time.time()-t) …
> Use 64-bit indices in sparse.AddSD where necessary (fix #5525)

- theano/misc/pkl_utils.py
As a stop gap for pickling large recursive structures - this should allow the user to set higher sys recursion limits outside of the library.
> Prevent pkl_utils from stomping higher sys recursion limits

- theano/gpuarray/dnn_pool.c
- theano/gpuarray/dnn_pool_grad.c
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
Similarly to #3715 allowing size-zero batches to be sent through cuDNN conv (essentially bypassing the call to cuDNN and allocating a size-zero batch output of the correct size), this allows size-zero batches to be sent through cuDNN pooling.
Comes with unit-tests and I have used this change in a real-world application for a couple weeks already.
> Allow for pooling of empty batch (like for conv in #3715).

- theano/gpuarray/pool.c
- theano/gpuarray/pool.py
- theano/gpuarray/pool_ave_grad.c
- theano/gpuarray/pool_grad_grad.c
- theano/gpuarray/pool_max_grad.c
- theano/gpuarray/pool_max_rop.c
fix #5582 . On Windows the test:
```
nosetests -vs theano/gpuarray/tests/test_pool.py:test_pool2d
```
fails with the following output:
```
Using cuDNN version 5110 on context None
Mapped name None to device cuda: GeForce 840M (0000:0A:00.0)
theano.gpuarray.tests.test_pool.test_pool2d ... FAIL
======================================================================
FAIL: theano.gpuarray.tests.test_pool.test_pool2d
----------------------------------------------------------------------
File "C:\donnees\programmes\Anaconda3\envs\python2\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\HPPC\mila\dev\git\theano\theano\gpuarray\tests\test_pool.py", line 116, in test_pool2d
assert np.allclose(f(), f2()), (shp, ws, st, pad, …
```
> Fix GPU test_pool on Windows.

- theano/gpuarray/reduction.py
- theano/gpuarray/tests/test_reduction.py
- theano/tensor/tests/test_subtensor.py
This PR fixes some unit tests that fail on GPU on Windows.
___
I resolved it by reducing the size of test values from 10 000 000 to 10 000. We initially use a big size to check if GPU is faster than CPU on big data, but I think it is not really useful for simple unit testing.
PS: But it is quite strange, as this test does not fail on my Ubuntu partition.
___
This test;
```
nosetests -vs theano/gpuarray/tests/test_subtensor.py:G_subtensor.test_noncontiguous_idx
```
fails with this output:
```
Using cuDNN version 5110 on context None
Mapped name None to device cuda: GeForce 840M (0000:0A:00.0)
test_noncontiguous_idx (theano.gpuarray.tests.test_subtensor.G_subtensor) ... FAIL
======================================================================
FAIL: test_noncontiguous_idx …
```
> Fix various GPU unit tests on Windows

- theano/tensor/nnet/neighbours.py
- theano/tensor/nnet/tests/test_neighbours.py
The whole code expects the shape to be of length 4, and the output to be
4D already.
Fixes #5613.
> Explicitly specify the output ndim in reshape

- theano/scan_module/tests/test_scan.py
- theano/tensor/tests/test_nlinalg.py
- theano/tensor/tests/test_slinalg.py
Some failures are not addressed:
- ModTester.test_grad will fail if the two inputs are really close to one another because then you wrap around and numeric_grad is super large.  This happens pretty rarely.
- test_dnn_batchnorm_train in the old backend failed once.  It seems to be a random fluke and we are about to delete the backend so I didn't want to investigate further.
> Fix problems in daily buildbot (debug mode)

- theano/configdefaults.py
- theano/sandbox/cuda/nvcc_compiler.py
This partly solves the problem identified in https://github.com/Theano/Theano/issues/1681#issuecomment-283022286 of GPU Ops taking much longer to compile than CPU Ops.
The problem is that a `mod.cu` file goes through `cudafe` and `cudafe++`, which takes a whopping 1.5 seconds of compile time even for an empty file. Many GPU Ops don't actually need that: If an Op doesn't require compiling any kernels, there's no point in calling `cudafe`. The simple solution is to rename such files to `mod.cpp` instead, and manually add the `cuda.h` and `cuda_runtime_api.h` headers.
This PR is a proof of concept. I'm not sure the distinction code catches all cases, but it works for me.
On my machine, `import theano` takes 2.5s before this PR, and 0.7s after (with an existing compile directory, not from …
> Faster compilation and import with cuda backend

- doc/library/config.txt
- theano/configdefaults.py
- theano/configparser.py
- theano/gpuarray/opt.py
- theano/tensor/nnet/tests/test_abstract_conv.py
This happen in corner cases with scan from 20m to 1m.
@f0k How bad you think that we don't assert user shape by default? @abergeron point of view is that this is more for debugging purpose. We won't generate bad results. It would just put back the user shape as compiler hint as it was done in some of the ops (while others was enforcing it). We will be consistent between all ops.
see gh-5642
> Change the default of conv.assert_shape flags to speed up compilation time

- NEWS.txt
- NEWS_DEV.txt
- doc/conf.py
- doc/index.txt
- doc/introduction.txt
- setup.py
PR to prepare release `0.9.0rc3`.
**NB**: I have not added one of the last PRs ( about old backend: https://github.com/Theano/Theano/pull/5631 ) into the highlights, as we don't want anymore to put old backend forth. But I have added it into `NEWS_DEV.txt`.
I'll update the PR if needed.
@nouiz
> Prepare release 0.9.0rc3.

- doc/library/config.txt
- openmp has been disabled by default since https://github.com/Theano/Theano/commit/f1f06bb960f63e098a7ce32de50c8547d2fb7713.
- grammar improvements
> docs: Fix openmp config section

- theano/scalar/basic_scipy.py
- theano/tensor/basic.py
- theano/tensor/inplace.py
- theano/tensor/tests/test_basic.py
Adding scalar and elemwise ops for modified Bessel function of order 0 and 1 from `scipy.special`. I've tried to follow the format and naming conventions as used for the Bessel function of first kind ops added in #3883.
> Adding scipy.special modified Bessel function ops

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
- theano/tests/test_printing.py
When the inner of scan is big, this should give good speed up.
We remove useless clone in the L_op and R_op. It also remove useless clone during the Scan.__init__() method. So this should also speed up opt that create new Scan node.
> Scan compile/grad speed up

- theano/compile/function_module.py
- theano/gof/opt.py
- theano/gof/tests/test_graph.py
- theano/scan_module/scan_utils.py
- theano/scan_module/tests/test_scan_opt.py
- theano/tensor/basic.py
- theano/tensor/opt.py
- MergeOptimizer don't call validate when merging constant
- SequenceOptimizer still print the partial profile.
- tensor.constant() don't create intermediate TensorConstant when it won't be used. (code clean up and help find where in the code constant are created)
> Speed merge optimizer and allow partial optimizer profile

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
fix #949
I've made a list of pairs of data types that would constitute an upcast, in **opt.py** in the function _upcast_
Function _local_cast_cast_ has been updated accordingly.
> Optimization to remove upcast in local_cast_cast

- theano/tests/test_flake8.py
Removed filenames from flake8 test whitelist:
- `sandbox/tests/test_theano_object.py`
- `sandbox/tests/test_scan.py`
#5743  @ReyhaneAskari
> #5743  Removed files from flake8 test whitelist

- theano/__init__.py
- Add has_handlers method to detect when a log handler has already been
added (e.g. root log handler);
- Add disable_log_handler method to disable theano_logger's default log
handler.
Signed-off-by: João Victor Tozatti Risso <joaovictor.risso@gmail.com>
> Add automatic detection of log handlers

- doc/tutorial/debug_faq.txt
Extended the debugging tutorial with information and an examples on test value printing.
fix gh-4111
> print_test_value in debugging tutorial

- theano/gof/cmodule.py
For printing compilation errors, a NamedTemporaryFile object is opened in the default mode ('w+b'), and strings are written to it. This is not an issue in Python 2, but in Python 3, strings cannot be implicitly converted to bytes so a TypeError occurs on line 2310 (previously 2309). This commit explicitly opens the NamedTemporaryFile in mode 'w'.
Here's a minimal example to reproduce the error (on Python 3):
```
>>> import tempfile
>>> tf = tempfile.TemporaryFile()
>>> tf.write('=\n')
...
TypeError: a bytes-like object is required, not 'str'
> Open tempfile in mode 'w' to prevent TypeError

- doc/library/tensor/nnet/conv.txt
Fix #5663 
I have added a line to doc/library/tensor/nnet/conv.txt in order to generate documentation for conv2d_transpose.
> Add conv2d transpose2doc

- theano/gpuarray/blas.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_basic_ops.py
- theano/gpuarray/tests/test_blas.py
- theano/gpuarray/tests/test_opt.py
- theano/gpuarray/type.py
- theano/tensor/blas.py
- theano/tensor/tests/test_blas.py
was found while investigating:
https://github.com/Theano/Theano/issues/5764
- also stop introducing useless float64 cast in the graph. fix gh-5764
> Don't move scalar float* elemwise unless the result is needed on the GPU.

- doc/introduction.txt
I just noticed that the current link to `sympy` in the docs is pointing to a dead Google Code site. This just updates the link to the current webpage.
Feel free to close this if you have some other way you prefer to make documentation updates.
> Fix out-of-date link to sympy

- theano/gof/compiledir.py
- theano/gpuarray/type.py
- theano/tensor/type.py
Currently, command `theano-cache list` skips modules that contains more than 1 Op. This does not help to track variations in compilation counts when we want to reduce C code procuded by Theano.
This PR updates the printing so that the number of compilations is printed for ALL compiled Op classes, and not only for individual compiled Op classes as it is currenty.
I have also updated `repr(GpuArrayType)` so that it looks more like `repr(TensorType)` (e.g. when `(False, False)` is replace with `matrix`), to help reduce length of printed lines.
@nouiz @lamblin .
**PS**: Example of printing with this PR. I am working on `GpuImages2Neibs`. As I have reduced its C code, it does not appear anymore in list of individual Ops at top of printing (because many different Op instances are associated to …
> Print compilation count for all compiled Op classes with "theano-cache list" command

- theano/tensor/nnet/nnet.py
Just a minor optimization that @danstowell found for Lasagne: Replace `tensor.exp(x) - 1` by `tensor.expm1(x)` in the elu definition so Theano doesn't have to. (Theano has an optimization that does the same.)
> Use expm1 for elu

- theano/gof/__init__.py
- theano/gof/tests/test_types.py
- theano/gof/type.py
This PR suggests a new abstract attribute `enum` added into COp to define enumerations of constants that will be automatically converted into C macros by `COp.get_op_params()` method.
This should help to reduce C code of some C-ops, for example with GpuDnnSoftmax, as we could then define a fixed-list of constants (that won't change from an op instance to another), and then use an op param that takes a runtime value within this list of constants.
The PR also adds two functions to help create enums quickly, and a test for this new feature.
@nouiz @abergeron  @lamblin
> Implement new op param type `EnumType`

- theano/gof/cmodule.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/test_elemwise.py
- theano/gpuarray/type.py
- theano/scalar/basic.py
- theano/tensor/nnet/sigm.py
Crash issue with theano/scalar/basic.py [gh-5816](https://github.com/Theano/Theano/issues/5816#issuecomment-293435358)
The diff does not crash when unpickling the batch normalization op.
Confirming what Pascal @lamblin suggested, it should be removed.
fix https://github.com/Theano/Theano/issues/5803
fix gh-5816
fix https://github.com/Theano/libgpuarray/issues/403
> Unsigned char:  fix: theano/scalar/basic.py

- doc/library/gof/params_type.txt
- theano/gof/op.py
- theano/gof/params_type.py
- theano/gof/tests/test_params_type.py
- theano/gof/tests/test_types.py
- theano/gof/type.py
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_softmax.c
- theano/gpuarray/dnn_softmax_grad.c
Reduce C code by using op params for GpuDnnSoftmax.
This PR depends on:
* PR for Wrapper that allows to make structs: #5612
* PR for EnumType that allows to create constants: #5710 
Here I update these PRs with some fixes, improvements and adjustments, and I finally use op params for `GpuDnnSoftmaxBase`, `GpuDnnSoftmax` and `GpuDnnSoftmaxGrad`. To help see differences with the other PRs, all these changes are in one commit (the current last): https://github.com/notoraptor/Theano/commit/6b204315c85ae41fb3abbdeb8668b3560864dad2 .
*Summary of changes added by this PR*:
1) Fix conversion from integers to C enum in C code for Theano enum types.
2) Update Wrapper with new convenient methods to ease wrapping dicts and objects.
3) Update Wrapper interface to handle Theano enum types. Enum …
> Use Op params for GpuDnnSoftmax

- doc/install_centos6.txt
- doc/install_generic.inc
- doc/install_macos.txt
- doc/install_ubuntu.txt
- doc/install_windows.txt
- doc/requirements.inc
- doc/requirements.txt
This PR adds some recommendations from this discussion: https://groups.google.com/forum/#!topic/theano-dev/3VQ08whW-5Q
**Notes**:
* For Python requirements, the first sentence is now adapted to the OS. It recommends python-dev(el) packages for Linux/CentOS, and conda distribution for Windows and Mac (I don't know if python-dev(el) packages exist on Mac).
* BLAS requirements now recommend `mkl-service` conda package, but OpenBLAS "dev" packages are still mentionned for all OS. I currently don't know how to add/remove conditionnally a list entry in a reST file.
* "sudo" terms are still present. It may be hard to make them appear only in Linux documentations.
* I have added a warning about conda installation for last versions of theano and pygpu, to tell that these packages currently don't …
> Update Windows (and other generic) installation instructions

- theano/sandbox/rng_mrg.py
If theano config.warn64 is set on 'raise' or 'warn', this generates an error/warning. This should help avoid that.
> avoid creating float64 variables

- theano/gof/cc.py
- theano/scalar/basic.py
- theano/tensor/elemwise.py
This makes the code compile, but crash gracefully when intdiv / mod by zero, when using openmp in elemwise.
Fixes #5875.
Counter-proposal for #5876.
> Remove goto in OpenMP Elemwise fail code

- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- theano/gof/tests/test_types.py
I suspect the issues regarding [the bool / int8 mismatch](http://darjeeling.iro.umontreal.ca:8080/job/Theano_buildbot_python2_debug/153/testReport/theano.tensor.tests.test_opt/Test_local_useless_elemwise_comparison/test_equality_shapes/) are due to old cached module, since I cannot reproduce locally.
> Fix tests in debugmode

- theano/gpuarray/linalg.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
This addresses some comments in #5754 :
- fixed the destroy map
- added an optimization for inplace (for A) in gpuarray/opt.py
- added A_structure and trans in the op lifter
For the op lifter, as only 2 cases are implemented in gpu_solve (general using LU decomposition and symmetric using cholesky) I considered that if the user requires a solve op for another case, it would be more efficient to keep it on the cpu, than to move it to the gpu using the general LU case.
@notoraptor
> Added an optimization for inplace gpu_cusolver_solve and tests

- doc/install_generic.inc
as Theano 0.9 work with it and it contain a bug fix.
https://github.com/fchollet/keras/issues/6400
when merged, it should be ported to 0.9 branch.
> Update libgpuarray version in the doc

- theano/tensor/nnet/tests/test_nnet.py
Noticed that Travis [failed](https://travis-ci.org/Theano/Theano/builds/227725922) after @lamblin merged my PR #5758, as I wrote the tests added to `test_nnet.py` when the import was done as `import numpy`, but it's apparently since been changed to `import numpy as np`.  This updates `test_nnet.py` accordingly and should fix the Travis failures.
> minor fix to test_nnet.py

- theano/gpuarray/tests/test_type.py
- theano/gpuarray/type.py
This was reported by:
[theano-users] Destination GpuArray is not contiguous
> Fix crash of set_value when the destination isn't contiguous

- doc/extending/cop.txt
- doc/extending/ctype.txt
- doc/extending/extending_theano_c.txt
- theano/gof/cc.py
- theano/gof/op.py
- theano/gof/params_type.py
This PR adds a small part of work done in #5866 , to help reduce the size of that (big) PR, and prevent some future problems:
- Allow c_support_code() implementations to return a string or a list of strings, to help avoid duplicated support codes into final module code.
- Make ParamsType.c_support_code() return a list of strings instead of a string.
- Add utility functions and methods implementations into ParamsType.
@nouiz @lamblin
> Allow c_support_code() to support list of strings and update ParamsType

- theano/gpuarray/basic_ops.py
- theano/gpuarray/blas.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/extra_ops.py
- theano/gpuarray/neighbours.py
- theano/gpuarray/nnet.py
- theano/gpuarray/pool.py
- theano/gpuarray/rng_mrg.py
This PR adds a part of work done in #5866 , to help reduce the size of that (big) PR, prevent some future problems with ParamsType, and reduce size of Theano code:
- Add default `GpuKernelBase.get_params()` that retrieves GPU context from first node input type, and then factorize `get_params()` for all sub-classes that retrieve context by this way. Method `get_params()` must be overridden for any subclass that gets context by different way. This proposal helps remove some lines of Theno Python code.
- Extend GpuKernelBase interface to allow sub-classes to use parameters types other than `gpu_context_type` (especially `ParamsType`). This helps prevent problems when some subclasses of GpuKernelBase will be rewritten with a ParamsType as params type (done in #5866 ).
@lamblin @nouiz
> Partially factorize GpuKernelBase.get_params() and configure it to use ParamsType.

- theano/tensor/nnet/corr3d.py
This PR adds a part of work done in #5866 , to help reduce the size of that (big) PR. Also, corr3d classes are compiled many times when running gpuarray DNN tests, so it could be useful to reduce C code variations for these classes.
Wrap Op params for **`theano.tensor.nnet.corr3d.BaseCorr3dMM`**:
- direction (enum list)
- dH, dW, dD: int64
- dilH, dilW, dilD: int64
- padH, padW, padD: int64
This influences all sub-classes:
- theano.tensor.nnet.corr3d.Corr3dMM
- theano.tensor.nnet.corr3d.Corr3dMM_gradWeights
- theano.tensor.nnet.corr3d.Corr3dMM_gradInputs
@nouiz @lamblin
> Wrap Op params for theano.tensor.nnet.corr3d.BaseCorr3dMM and subclasses.

- theano/configdefaults.py
- theano/gof/op.py
- theano/gof/type.py
- theano/gpuarray/conv_desc.c
- theano/gpuarray/cudnn_defs.py
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_batchnorm_grad.c
- theano/gpuarray/dnn_batchnorm_inf.c
- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
- theano/gpuarray/dnn_pool.c
- theano/gpuarray/dnn_pool_grad.c
- theano/gpuarray/tests/test_dnn.py
- theano/tensor/signal/pool.py
This PR adds and extends a lot of work done in #5866 . ParamsType is now used for many gpuarray DNN ops, and cuDNN v6 integration is extended.
Ops currently rewritten in this PR:
- GpuDnnConvDesc
- GpuDnnConv
- GpuDnnConvGradW
- GpuDnnConvGradI
- GpuDnnPool
- GpuDnnPoolGrad
- GpuDnnBatchNormInference
- GpuDnnBatchNormGrad
cuDNN v6 integration:
- Support MAX DETERMINISTIC algorithm for GpuDnnPool with cuDNN v6.
- Update pooling tests for DNN module so that they use the available algorithms depending on runtime cuDNN version.
- Allow CPU Pool and PoolGrad ops to use MAX_DETERMINISTIC algo when cuDNN v6 is used with GPU counterparts.
- Encapsulate cuDNN constants used in DNN module, to help choose the right cuDNN definitions depending on the runtime cuDNN version. Currently supported cuDNN …
> Wrap Op params for many gpuarray DNN Ops and add cuDNN v6 integration.

- theano/gpuarray/cudnn_defs.py
Update cuDNN definitions: one not-implemented BWD_FILTER algorithm is available in v6 but commented in v5 code.
There are no such other cases, @abergeron .
@slefrancois, buildbot should compile well after this PR be merged!
> (crash fix) Fix availability of cuDNN enumerations in v5 vs v6.

- theano/gpuarray/__init__.py
- theano/gpuarray/dnn.py
Make dnn_present() always return a Boolean, and move checking of `dnn.enabled=="True"` into init_dev().
A code that calls either `dnn_present()`, `dnn_available()` or `version()` is now responsible for raising an exception if these functions fail and if `dnn.enabled` is `"True"`.
> (small fix) update usage of `dnn.enabled`

- doc/dev_start_guide.txt
- doc/library/compile/debugmode.txt
- doc/library/compile/nanguardmode.txt
- doc/library/compile/opfromgraph.txt
- doc/library/config.txt
- doc/library/d3viz/index.txt
- doc/library/gpuarray/extra.txt
- doc/library/gpuarray/op.txt
- doc/library/printing.txt
- doc/library/scan.txt
- doc/library/sparse/index.txt
- doc/library/tensor/basic.txt
- doc/library/tensor/nnet/index.txt
- doc/optimizations.txt
- doc/tutorial/debug_faq.txt
- doc/tutorial/examples.txt
- doc/tutorial/faq_tutorial.txt
- doc/tutorial/gradients.txt
- doc/tutorial/multi_cores.txt
- doc/tutorial/nan_tutorial.txt
- doc/tutorial/numpy.txt
- doc/tutorial/shape_info.txt
- doc/tutorial/sparse.txt
- doc/tutorial/using_gpu.txt
- doc/tutorial/using_multi_gpu.txt
"Optimise" (and its derived words) only occurred twice, while "optimize" was overwhelmingly popular. I also saw a fairly even mixture of "behavior" and "behaviour", so I hesitate to change these for lack of guidance on adopting U.S./Canadian/British spelling.
> Fix doc typos and spelling errors. Make spelling of "optimize" consistent.

- theano/gpuarray/dnn.py
When updating lists of algorithms, I had forgotten to add runtime algos to conv3d allowed algos.
@abergeron @lamblin
> (small fix) Re-allow runtime algorithms for conv3d Ops.

- doc/library/config.txt
It seems these two Theano flags are not in the documentation: http://deeplearning.net/software/theano_versions/dev/library/config.html
> (small fix) Add doc for `dnn.include_path` and `dnn.library_path`.

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
Fix #5036.
Unfortunately, there is no easy way of introducing the GPU Ops for subtensor and inc_subtensor directly, so they have to be cleaned up in a later pass.
I did not see GpuAdvancedSubtensor or even AdvancedIncSubtensor to be an issue in practice, it did not even register in the profile. It could be different on other models.
> Add lifter for CrossentropyCategorical1Hot and grad

- theano/tensor/elemwise_cgen.py
This is a tiny fix to the `Elemwise` "Input dimension mis-match" exception (on cpu). It tries to format `long long` values with `%lli`, but this format character [does not exist](https://docs.python.org/2/c-api/string.html#c.PyString_FromFormat). The error message then looks like this:
```
ValueError: Input dimension mis-match. (input[1].shape[1] = %lli, input[%i].shape[%i] = %lli)
```
`%lld` works better.
> Fix elemwise ValueError message (printf formatting)

- theano/gpuarray/dnn.py
Otherwise, the RuntimeError will skip the other optimizations, including the one inserting GpuCorrMM
> Allow fallback on GpuCorrMM if cuDNN is not there

- theano/compile/debugmode.py
@nouiz found a problem in ```_optcheck_fgraph``` when reviewing https://github.com/Theano/Theano/pull/6000 . This function should be the same as ```std_fgraph``` but the code was just copied and not updated properly. So this PR removes the duplicate code and just calls the ```std_fgraph``` directly.
> removed part of _optcheck_fgraph and called std_fgraph instead

- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/tests/test_dnn.py
A PR to help fix #5985 and fix #6020 .
Currently, I have added two tests to reproduce the problem: one with 10 000 as batch size, and another with 70 000 as batch size (all other parameters are identical). Then the test with 70 000 inputs fails (see console output below).
Currently, I don't think that the problem is about strides or dimensions, as all these values for current tested inputs may be handled by a system integer (`int`). Still investigating.
@abergeron @lamblin @nouiz 
```
$ nosetests -xvs theano/gpuarray/tests/test_dnn.py:test_batched_conv_success
Using cuDNN version 6020 on context None
Mapped name None to device cuda: GeForce GTX TITAN X (0000:02:00.0)
theano.gpuarray.tests.test_dnn.test_batched_conv_success((10000, 4, 32, 32), (1, 4, 16, 16), 25, (3, 3)) ... Input size: …
```
> Work around erroneous dnn_conv results with algo small an large batches

- theano/scalar/basic_scipy.py
- theano/tensor/basic.py
- theano/tensor/inplace.py
- theano/tensor/tests/test_basic.py
I've added the Tri-gamma function, which can be run on the GPU as well in comparison to #5963.
Note that I'm not too sure how you guys want to keep the name as the digamma function in Theano is named psi. 
As a note I'm aware of some efforts of doing the more general poly-gamma function, however, this requires a lot more effort and debugging of CUDA kernels as in #4198 which I can not do.
The implementation C code was taken from http://people.sc.fsu.edu/~jburkardt/cpp_src/asa121/asa121.html
As a side note if the `polygamma` makes it into to Theano you might want for `k=0` and `k=1` the Theano interface to return the `Psi` and `TriGamma` Ops, this might simplify the interface significantly.
> Added the tri-gamma function.

- theano/compile/ops.py
- theano/gpuarray/extra_ops.py
- theano/gpuarray/neighbours.py
- theano/gpuarray/rng_mrg.py
- theano/gpuarray/subtensor.py
- theano/tensor/nnet/neighbours.py
- theano/tensor/subtensor.py
Continues #5866 (cannot reopen that PR). Rebased and re-read. Adding op params for:
- GpuCumOp
- GPUA_mrg_uniform
- AdvancedIncSubtensor1 (+ set `check_input=False` for AdvancedSubtensor1)
- GpuAdvancedIncSubtensor1
- GpuAdvancedIncSubtensor1_dev20
- Images2Neibs
- GpuImages2Neibs
- compile.ops.Shape_i
I think it will not speed up TRAVIS so much, as changes are mainly in gpuarray module, but now we can end with this big old PR!
@nouiz @lamblin @abergeron
> Params for other ops

- doc/library/config.txt
- theano/configdefaults.py
- theano/gof/cc.py
- theano/gof/type.py
- theano/gpuarray/dnn_gw.c
Discussed here: https://github.com/Theano/Theano/pull/5932#issuecomment-310209926
This PR adds a boolean Theano flag `cmodule.debug` (default `false`) used to activate a DEBUG mode for C code by adding a `DEBUG` macro at the top of any generated C code. The PR also uses this new option in an example to print runtime chosen algorithm for cuDNN backward filter convolution.
@lamblin @abergeron  @nouiz .
> Add a DEBUG option for C code

- theano/gof/cc.py
- theano/gof/op.py
- theano/gof/tests/test_vm.py
- theano/gof/vm.py
This fix the long standing issue (for the VM only) about multiple compilation due to re_recycling.
Mostly, Theano was compiling different c code if one node was the output of a graph or not. I suspect that for the tests, this cause much extra c code compiled then needed.
on my travis, I deleted Theano cache to see the travis time in that case: https://travis-ci.org/nouiz/Theano/builds/250125948
On Theano travis, we will see how it behave with an empty cache.
When running the tests included in this PR on the master with an empty cache, we have this in the cache after the test
```
===============================================================================================================
Theano cache: /home/nouiz/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64- …
```
> Compile less C code

- doc/extending/extending_theano_c.txt
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_batchnorm.c
When working on DNN module I had not parameterized GpuDnnBatchNorm because its inputs and outputs lengths depended on a macro param. But this op has a maximum inputs length and outputs length, and then `_cop_num_inputs` and `_cop_num_outputs` allow to handle this case for COps.
This PR adds params type to GpuDnnBatchNorm. Now DNN module does not contain `get_op_params()` implementations anymore.
@abergeron @nouiz @lamblin 
**NB**: I think the last op that may be rewritten into this module is `theano.gpuarray.dnn._RNNSplitParams`. This op does not have parameters, but it also has a variable outputs length, C code here is a little more complicated, and it is not currently a real COp (`c_code()` is redefined).
> Wrap Op params for theano.gpuarray.dnn.GpuDnnBatchNorm

- theano/gof/params_type.py
- theano/gpuarray/tests/test_elemwise.py
- theano/tensor/elemwise.py
- theano/tensor/elemwise_cgen.py
- theano/tensor/tests/test_elemwise.py
This also fixes:
- minor memory leak in the elemwise alloc code
-  compile of ParamsType with CLinker of more than one op.
> Make the CAReduce tests faster

- .travis.yml
This should guarantee that even with the launch / sync overhead (3-6 minutes), and even on slower workers, on an empty Theano cache, we are under the 50 minute limits.
There is one more split, so 2 more jobs in total (python 2 and 3).
> Reorganize Travis

- theano/gpuarray/tests/test_linalg.py
- theano/tests/unittest_tools.py
About this error: http://earlgrey.iro.umontreal.ca:8080/job/Theano_buildbot_python3/203/testReport/theano.gpuarray.tests.test_linalg/TestMagma/test_gpu_matrix_inverse_2/
I can not reproduce the problem (with Python 3), maybe because test values are randomly chosen, but I think increasing the rtol to 1e-3 should help tests to pass, as results compare `matrix * matrix inverse` with `np.eye()`.
@slefrancois @lamblin @nouiz .
> (small fix) Increase error tolerance for magma matrix_inverse tests.

- theano/tensor/nnet/nnet.py
I found a typo in make_node function. We should correct it otherwise some potential wired bugs may occur.
> Correct a typo in make_node function (tensore.nnet.SoftmaxWithBias)

- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
I need it for tests script, but it's better to add it separately so that other people can start debugging too.
This PR adds a code to print algorithm chosen at runtime for fwd and gradinput cuDNN convolutions (already done for gradweight) when theano flag `cmodule.debug` is set to `True`.
This may be useful for @olimastro to help debug cuDNN convolutions with `time_once` !
NB: About `cmodule.debug`, should we modify how this flag is used ? Or is it currently right enough ? I had done an old comment about that here: https://github.com/Theano/Theano/pull/6102#issuecomment-312936201 . @abergeron @lamblin .
> Add debug code to print algo chosen at runtime for cuDNN convolutions.

- theano/sparse/tests/test_basic.py
Yes, this may leave some cases where it won't check and the test would pass, but I don't expect that we promise it to be faster in all cases (like for example FAST_COMPILE).
> Only compare to scipy timing in FAST_RUN.

- theano/gof/opt.py
- theano/gof/unify.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/subtensor.py
- theano/scan_module/scan_utils.py
- theano/sparse/basic.py
- theano/sparse/opt.py
- theano/sparse/sandbox/sp2.py
- theano/tensor/tests/test_basic.py
- theano/tensor/var.py
This PR fixes some alerts flagged by lgtm.com code queries. Most are minor improvements suggestions but a few some should fix unintentional code behaviour (e.g. correct call to `copy()`). 
The standard lgtm engineering analytics highlights dependencies, vulnerabilities and tracks introduced and fixed alerts as the code changes (and shows that [Theano keeps getting better](https://lgtm.com/projects/g/Theano/Theano/)). There are currently [295 alerts](https://lgtm.com/projects/g/Theano/Theano/alerts/) flagged, probably better investigated by someone more familiar with the code base than me, but you can also investigate further by writing [your own custom queries](https://lgtm.com/docs/ql/about-ql) to explore your code base.
I personally find lgtm alerts most useful when using [PR …
> Fix alerts found with lgtm

- theano/gof/unify.py
In #6111 I introduced the user of `super()` for class initialisation without realising that the parent class `Variable` was old-style.
This PR makes it new-style (alternatively the changes in #6111 could be reverted to use `Variable.__init__` in child classes but I believe using `super()` is more proper - and in Python 3 all classes are new-style).
> make variable class new style

- theano/gpuarray/linalg.py
- theano/gpuarray/magma_cholesky.c
- theano/gpuarray/magma_eigh.c
- theano/gpuarray/magma_inv.c
- theano/gpuarray/magma_qr.c
- theano/gpuarray/magma_svd.c
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_linalg.py
- theano/tensor/nlinalg.py
Adds a wrapper for gpu magma QR decomposition, Cholesky decomposition and Eigen decomposition for symmetric matrices. Optimization group was created for matrix ops. Cusolver is always used first when it is available. The reason is that cusolver Cholesky decomposition is faster than magma Cholesky decomposition (tested for size 1000).
> Magma gpu QR/Cholesky/Eigh

- theano/gpuarray/blas.py
#6161 and #6169 both raised the c_code_cache_version for GpuGemv to (8,) and thus the new params code may end up using old cached compiled module which doesn't work.
Fix this by raising the c_code_cache version.
> Bump c_code_cache_version for GpuGemv to ensure that new builds use the right C code.

- theano/gpuarray/c_code/dimshuffle.c
- theano/gpuarray/elemwise.py
- theano/tensor/c_code/dimshuffle.c
- theano/tensor/elemwise.py
As a quick benchmark, running:
```
nosetests -xvs
theano\tensor\tests\test_basic.py:test_batched_dot
theano\tensor\tests\test_basic.py:test_batched_dot_not_contiguous
theano\tensor\tests\test_basic.py:BatchedDotTester
```
With `master` branch (after `theano-cache purge`), 70.428s and 11 compilations for CPU DimShuffle.
With this branch (after `theano-cache purge`), 62.231s and 1 compilation for CPU DimShuffle.
@abergeron @lamblin
> Wrap op params for [Gpu]DimShuffle.

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
Fixes bug in `scan_until` shape concatenation and adds a small test for inputs with `ndim > 1`.
> Fix bug in scan_until shape concatenation

- doc/tutorial/debug_faq.txt
- theano/tests/breakpoint.py
`PdbBreakpoint` by default supports only `pdb` debugger which has limited functionality. This pull request adds support for `pudb` or `ipdb` if available.
> Support more debuggers for PdbBreakpoint

- theano/gpuarray/linalg.py
- theano/gpuarray/opt.py
This is an update of #4007 to use the gpuarray backend. This is an alternative to #6176 that separates the triangular solve into a new op, and deals with the case when the right hand side is a vector (as in #4007).
> Added GpuCublasTriangularSolve and the associated lifter optimizations

- .travis.yml
- doc/install_windows.txt
- requirement-rtd.txt
- setup.py
- theano/gpuarray/tests/test_dnn.py
- theano/tensor/nnet/tests/test_conv3d2d.py
- theano/tensor/nnet/tests/test_corr3d.py
- theano/tensor/signal/tests/test_pool.py
- theano/tests/unittest_tools.py
The former is deprecated in favor of the latter.
> Replace nose-parameterized by parameterized

- doc/install_windows.txt
- doc/requirements.inc
About #6209 , it seems that package `parameterized` is not available in conda.
On Windows:
```batch
(python2) C:\Users\notoraptor\mila\dev\git\theano>conda install parameterized
Fetching package metadata ...........
PackageNotFoundError: Package missing in current win-64 channels:
- parameterized
Close matches found; did you mean one of these?
parameterized: nose-parameterized
(python2) C:\Users\notoraptor\mila\dev\git\theano>conda search parameterized
Fetching package metadata ...........
nose-parameterized           0.5.0                    py27_0  defaults
0.5.0                    py34_0  defaults
0.5.0                    py35_0  defaults
0.5.0                    py36_0  defaults
0.6.0                    py27_0  defaults
0.6.0                    py35_0  defaults
0.6.0 …
```
> Update doc for package parameterized.

- setup.py
Fixes #6222. Closes #6223.
Reading the source code of distutils (https://github.com/python/cpython/blob/master/Lib/distutils/command/build_py.py#L97-L132), I found that a much simpler option is to make use of the `''` entry in `package_data` -- it specifies globbing patterns that are applied to every package specified in `packages`. We can just add `c_code/*` there.
> Install c_code/* files for every submodule

- theano/tensor/nnet/nnet.py
Since, for the next versions of Theano PR #6132 , we'll handle the vector case inside the softmax and logsoftmax op, we'll notify the user that the padding will be removed and that the output will be a vector instead of a matrix. @ReyhaneAskari @lamblin @nouiz
> Add deprecation warning for the softmax and logsoftmax vector case

- theano/configdefaults.py
- theano/configparser.py
- theano/gof/cc.py
- theano/gof/cmodule.py
- theano/gof/params_type.py
- theano/gof/utils.py
- theano/printing.py
- theano/sparse/utils.py
- theano/tensor/utils.py
- theano/tests/record.py
The first part (sha256) if the rebase/finish up from: https://github.com/Theano/Theano/pull/5916
As this force the recompilation of all c code, I also include in this PR gh-6068 to have only 1 PR that force the recompilation. This commit help the cache don't collide if we add props to an op but forget to bump the version number.
> Use sha256 for config hash to be FIPS compliant and make Theano cache more forward compatible

- theano/gof/tests/test_graph_opt_caching.py
> (small fix) use `os.remove` instead of system `rm` command

- theano/gpuarray/c_code/dnn_fwd.c
- theano/gpuarray/c_code/dnn_rnn_desc.c
- theano/gpuarray/cudnn_defs.py
- theano/gpuarray/dnn.py
This PR cherry-picks and adapts some commits from #6283 .
PR #6283 is currently a Work In Progress, and is not currently safe because it contains some unconditional codes for cuDNN 7 in `dnn.py` (e.g. `cudnnMathType_t`, so that cuDNN V6 can not work). So, I have only taken the minimal changes required to make cuDNN V7 work. I think we should wait for #6283 to reach a safer state before integrating more cuDNN V7 stuffs.
What do you think, @nouiz @abergeron ?
> Add support for cuDNN V7

- theano/gof/graph.py
- theano/gof/tests/test_graph.py
This PR has two effects:
- `theano.gof.graph.clone_get_equiv` now has better interface with separate options for `copy_inputs` and `copy_orphans`
- `theano.gof.graph.clone` now always copies orphans, its `copy_inputs` flag will only affect the inputs, not the orphans
This makes it possible to clone a graph including the constant but preserving the inputs.
> separate copying inputs and copying orphans

- theano/scan_module/scan_op.py
The error message here is unclear about the node causing problem. Added the `repr(var)` to be a bit more specific.
> Specifying culprit node in `MissingInputError`

- theano/configdefaults.py
- theano/gof/graph.py
A Flag is added to disable pickling test values. By default, it's False. A warning will raised by default if there are test values at pickling time.
fix gh-2655
> Flag to disable pickling test values

- theano/gpuarray/c_code/dnn_redux.c
- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_others.py
There is a problem that was reported with cuDNN reduction where it would give different results than before it was integrated.
This *may* be because there are corner cases where non-contiguous inputs are not supported, so we are tentatively reversing this.  More testing is required to determine the exact cause.
> Restrict cuDNN reduction to contiguous inputs

- theano/tensor/var.py
fix #6217 .
NumPy versions prior to 1.13 should print a `FutureWarning` when a comparaison `array == None` is done:
```
(test) C:\Users\notoraptor\mila\dev\git\theano>python -c "import numpy; print(numpy.__version__); a = numpy.arange(10); print(a == None)"
1.12.1
-c:1: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
False
```
So, as a first check, I looked for `FutureWarning` into a previous successful CI testing, in both Jenkins and Travis:
- http://earlgrey.iro.umontreal.ca:8080/job/Theano_PR/616/console
- https://travis-ci.org/Theano/Theano/builds/263080988
As results:
- There are no `FutureWarning` messages in Jenkins console output.
- There are 4 `FutureWarning` messages in Travis tests, but all come frome SciPy (not Theano), via …
> Support NumPy 1.13

- theano/gpuarray/c_code/dnn_conv_base.c
- theano/gpuarray/c_code/dnn_fwd.c
- theano/gpuarray/c_code/dnn_gi.c
- theano/gpuarray/c_code/dnn_gw.c
- theano/gpuarray/tests/test_dnn.py
While running scripts from #5932 , I discovered an error that can be reproduced with following code and master branch:
File `test12.py`
```python
from __future__ import absolute_import, print_function, division
import numpy as np
import theano.tests.unittest_tools as utt
from theano.gpuarray.tests.config import mode_with_gpu
from theano.gpuarray import dnn
import theano
utt.seed_rng()
def get_function(inputs_shape, filters_shape, dtype, precision, algo, border_mode='full'):
inputs_val = np.random.random(inputs_shape).astype(dtype)
filters_val = np.random.random(filters_shape).astype(dtype)
inputs_val /= 10
filters_val /= 10
inputs = theano.shared(inputs_val)
filters = theano.shared(filters_val)
conv = dnn.dnn_conv(img=inputs, kerns=filters, border_mode=border_mode,
algo=algo, …
```
> Add data type configuration to algorithms hash for cuDNN convolutions caching system

- theano/gpuarray/c_code/dnn_sptf_grid.c
- theano/gpuarray/tests/test_dnn.py
Hi @joaovictortr. Thanks for making the spatial transform from cuDNN available. I have a small suggestion for the size check of the `theta` parameter. The current test checks the second and third dimensions, but doesn't check if the number of rows in `theta` is the same as the number of rows in the input. This patch would change the shape check to make sure that the number of rows in `theta` matches the input shape.
---
If `theta` is shorter than the input, the cuDNN function will currently return random values for all the inputs that fall outside `theta`'s range. Here's an example:
```python
import numpy as np
import theano
import theano.gpuarray
x_val = np.ones(shape=(2, 3, 5, 5)).astype(theano.config.floatX)
theta_val = np.array([[[1, 0, 0], [0, 1, …
```
> Check shapes of spatial transform theta parameters

- theano/gpuarray/c_code/dnn_fwd.c
- theano/gpuarray/c_code/dnn_gi.c
- theano/gpuarray/c_code/dnn_gw.c
Added conditions to exclude TENSOR_OP (HMMA) convo algos when operands  are 32-bit - since they lose precision. 
Also, streamlined saving old algo and cache updates - I think there was a bug in cache update condition there, too.
> Fixing math_type for F32 and cache update

- theano/gpuarray/dnn.py
- theano/pathparse.py
Fix #6330 
Add `dnn.bin_path` to system's `PATH` environment variable on Windows only at runtime, so that user does not need to do it himself anymore. This works well on my computer (Windows 10 64 bits).
@abergeron @nouiz
> Automatically add dnn.bin_path to PATH at runtime on Windows

- theano/gpuarray/dnn.py
This PR fixes rpath for cuDNN ops by removing any quotes around paths. We should not need quotes on Windows anymore when #6356 will be merged.
NB: We should check if this PR does not break anything in buildbot. We also need Jenkins tests to pass, probably on all platforms ?
@abergeron @nouiz
> Fix rpath for cuDNN module.

- .jenkins/jenkins_buildbot_mac.sh
- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- .jenkins/jenkins_buildbot_python3.sh
- .jenkins/jenkins_buildbot_windows.bat
- .jenkins/jenkins_pr_build_cache.sh
- .jenkins/jenkins_pr_gpu.sh
- .jenkins/jenkins_pr_mac.sh
- .jenkins/jenkins_pr_win.bat
Recent changes in pygpu version parsing do not support `--depth=1` checkouts:
```
File "theano/gpuarray/__init__.py", line 49, in pygpu_parse_version
major = int(pieces[0])
ValueError: invalid literal for int() with base 10: '0+untagged'
```
> libgpuarray full checkout to parse version

- theano/gpuarray/basic_ops.py
- theano/gpuarray/elemwise.py
Related to #6162 .
I can't yet say that every memory leak is fixed, but some of them are fixed here by calling `GpuElemwise_free()` in `c_cleanup_code_struct`.
> Fix a memory leak in theano

- theano/gpuarray/blas.py
- theano/gpuarray/c_code/corr_gemm.c
- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/c_code/corr_gemm.c
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
Related to #5515. I've tried to use a similar approach as in [Keras](https://github.com/fchollet/keras/pull/5489).
This also adds asymmetric padding.
> Dilated causal convolution

- theano/tensor/blas_headers.py
- theano/tensor/c_code/alt_blas_template.c
I forgot to add an extra call to `Py_XDECREF()` after calling `PyArray_MatrixProduct2()`.
> Fix memory leak in fallback sdot

- .jenkins/jenkins_buildbot_release_extra.sh
Dockers have been modified to add a no_scipy conda env.
> buildbot release test without scipy

- theano/gpuarray/c_code/dimshuffle.c
- theano/gpuarray/elemwise.py
- theano/tensor/blas_headers.py
- theano/tensor/c_code/alt_blas_template.c
- theano/tensor/c_code/dimshuffle.c
- theano/tensor/elemwise.py
- theano/tensor/tests/test_blas.py
- theano/tensor/tests/test_blas_c.py
This should fix #6464 . Now if a tensor must be elemwise-multiplied by zero, then it is explicitly set to 0 to overwrite any previous value.
I also added unit tests for alt gemm, so that all current alternative BLAS functions are tested.
@lamblin @nouiz @abergeron
> Improve alternative BLAS code and add tests for alternative gemm function.

- theano/gpuarray/multinomial.py
- theano/gpuarray/rng_mrg.py
- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
This is an implementation of the box-muller transform for a normal distribution truncated at two standard deviations (as requested in issue #6381).
I did not quite get why there would be need to distinguish between integer and tensor sizes, given that theano optimises the graph and probably includes constant folding. Therefore, I have introduced my own interpretation of the normal code (which I personally find more readable, if I'm allowed to be smug for a second). If one of two approaches turn out to be better/faster/more readable/more whatever, quite a bit of code can be reused and a refactoring might be advisable.
> Implement truncated normal with box-muller

- theano/tensor/signal/pool.py
signal.Pool currently does
int32 = \*(int64\*)(ws,stride,pad, which may be int32 or int64 arrays)
When ws/stride/pad are int32, this is a strict aliasing violation (i.e. technically undefined behaviour; it currently appears to work [unless you're using unusual hardware](https://bugs.debian.org/878596), but might not always).
It also uses int32 indices, which is a possible index-overflow crash if the input array is very large (though I don't have enough RAM to actually test this).
This fixes both those problems.  It passes tensor/signal/tests, but I haven't tried a full test run.
Speed test - tensor/signal/tests/test_pool.py:TestDownsampleFactorMax.test_pooling_with_tensor_vars with the size increased to 10x10x500x500:
current - 88.2, 58.8, 59.0, 58.9, 90.0sec
this - 87.2, 58.1, 57.8, …
> Fix invalid casts and index overflows in signal.Pool

- theano/gof/cmodule.py
When initializing theano with cudnn, `_try_compile_tmp` is eventually run to verify compiling a test program with gcc. This function requests a temporary path for the test program from the `mkstemp` function of tempfile.py. Rarely, this can return a path that has spaces in it. If this happens, gcc cannot parse it correctly and throws an error, which will look something like:
```
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
g++.exe: error: c:\program: No such file or directory
```
The proposed change encloses the temp path in quotes, allowing gcc to parse it even if it contains spaces.
For an example case: I was running python through an ssh client which accesses the home directory through a symlink in C:\Program …
> Bugfix: spaces in temp path prevents cudnn init

- .jenkins/jenkins_buildbot_windows.bat
- .jenkins/jenkins_pr_win.bat
- theano/gpuarray/__init__.py
In the Windows buildbot, we test GPU initialization with `"import theano.gpuarray; theano.gpuarray.use('%DEVICE%')"`, But we set `THEANO_FLAGS=init_gpu_device=cuda` before (see top of file), thus `import theano.gpuarray` will automatically initialize the GPU, then the second instruction (`theano.gpuarray.use(%DEVICE%)`) will force a second initialization, that is forbidden by the @abergeron 's PR (first initialization will set OS env var `THEANO_GPU_IS_ALREADY_ACTIVE`, and second initialization will fail because that OS env var will be already set).
We must either: find a better way to distinguish mutiple initalization accross different processes vs multiiple initialization inside the same process, or update jenkins scripts to prevent multiple initialization inside the same process (I …
> Fix GPU initialization checking on buildbot.

- theano/tensor/blas.py
This might in some case where the compiler got confused and could not
infer the right type for the gemm function.
Might help for #6518
> Remove a template argument from batch_gemm

- theano/gof/lazylinker_c.py
I managed to trigger a run where 'import theano' failed to read the version number. Closing the file descriptor where the version of lazylinker is written, appeared to fix it.
> lazylinker_c: Make sure that the version number is flushed to disk

- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
This was particularly visible for float16 since they would just stop working, but it also caused a reduction in precision for all other data types which could have lead to wrong results.
This was only avoided by the fact that we use cudnn all the time so only DEBUG_MODE was able to sniff this out since it runs the intermediate graph before we switch to cudnn reductions.
91bc16c3
> Fix non-cudnn reductions that were all subtly broken by 91bc16c3.

- theano/gof/cmodule.py
- theano/gof/type.py
- theano/gof/vm.py
In trying to find an ML library to work on pypy, I figured out some hacks to get it working (at least superficially with runtime compiled cpyext modules). 
There seems to be a few problems that need to be resolved before it would work out of the box:
1. A single usage of the ctypes.pythonapi.PyCapsule_Type
2. A single usage of sys.getrefcount (to check that there isn't leaks)
3. Missing build information to runtime load the compiled .so python module
- The correct binary .so filename looks to be able to be constructed using distutils.sysconfig.get_config_var("SO") (or EXT_SUFFIX in python3)
- Expects libpython.so (or equivalent) in the distutils.sysconfig.get_config_var("LIBDIR") location which does not exist
- distutils.sysconfig.get_config_var("LDLIBRARY") does not resolve in pypy …
> Make Theano work under pypy (WIP)

- theano/sparse/tests/test_basic.py
This should help the buildbot not fail as often as it does.
> Make the csm_unsorted matrix a bit bigger to avoid accidentaly sorted indices

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
The Sub class do not allow this. So raise an error if we would need the "-" operator.
> Fix gh-6609. Do not do bool-bool when not needed anymore.

- theano/gpuarray/basic_ops.py
- theano/gpuarray/linalg.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_basic_ops.py
- theano/gpuarray/tests/test_linalg.py
* Add float64 support for GpuCholesky, GpuCusolverSolve, GpuCublasTriangularSolve
* Add L_op to GpuCholesky, GpuCusolverSolve, GpuCublasTriangularSolve based on the implementation in slinalg.py
* Add GpuTri op so that the whole thing run on GPU
Tested with my own GPU on both float64, float32 using 
```
$ nosetests test_linalg.py
$ nosetests test_basic_ops.py
```
under theano/gpuarray/tests and my own code that needs gradient of cholesky factorization and triangular solve.
> float64 support for GpuCholesky, GpuCusolverSolve, GpuCublasTriangularSolve and their L_op

- theano/gof/cmodule.py
This should remove the annoying deprecation warning on Python 3 where the configuration variable has been renamed to `EXT_SUFFIX` from `SO`. Feel free to ignore if this is wrong or not a good fit.
> Update extension suffix config var name

- theano/gpuarray/multinomial.py
I got this error on master when using a multinomial op:
```
~/.local/lib/python3.7/site-packages/Theano-1.0.3+21.g813faf6a9.dirty-py3.7.egg/theano/gpuarray/multinomial.py in c_code(self, node, name, inp, outputs, sub)
226 
227     } // END NESTED SCOPE
--> 228         """ % locals()
229 
230         return s
TypeError: ('The following error happened while compiling the node', GPUAMultinomialFromUniform{odtype='int64'}(GpuAdvancedSubtensor.0, GPUA_mrg_uniform{GpuArrayType<None>(float32, vector),inplace}.1), '\n', 'not enough arguments for format string')
```
The change fixes it for me.
> Fix syntax error in format string in gpuarray/multinomial.py

- theano/compat/__init__.py
- theano/misc/ordered_set.py
In Py37 importing from `collections` is a DeprecationWarning and will become an Exception in Py38.
```
/Users/anz/miniconda3/envs/dev3/lib/python3.7/site-packages/theano/compat/__init__.py:79: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
not isinstance(default_factory, collections.Callable)):
```
> MAINT: collections import is deprecated

- theano/gof/cc.py
Since Debian unstable moved to Numpy 1.16, all compiles have been failing with "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'":
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918090
https://ci.debian.net/data/autopkgtest/unstable/amd64/t/theano/1576998/log.gz
Probably because that function was moved by this Numpy commit:
https://github.com/numpy/numpy/commit/31df302656b88df2937c5ac338c96b1a0ec6d687
I do **not** yet know whether this is the only incompatibility, as I have not yet tried the full set of tests with Numpy 1.16; I will report any others I find.
> Be compatible with Numpy 1.16

- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/tests/test_abstract_conv.py
I added a test to check the output shape error [here](https://github.com/Theano/Theano/pull/6673#issuecomment-453591187). Also, fractions.gcd is deprecated so I changed to math.gcd as its suggestion.
> added test for output shape of frac bilinear upsampling

- theano/tensor/basic.py
Currently, running the following code
```python
x = T.as_tensor_variable([1., 2., 3.])
mat = T.AllocDiag()(x)
print(mat.eval())
```
runs as expected but triggers a `FutureWarning` from `numpy`:
```
/anaconda3/lib/python3.7/site-packages/theano/tensor/basic.py:6611: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
result[diagonal_slice] = x
[[1. 0. 0.]
[0. 2. 0.]
[0. 0. 3.]]
```
Simply casting `diagonal_slice` to `tuple` returns the correct output but eliminates the warning.
> Eliminate FutureWarning from numpy

- theano/tensor/subtensor.py
This PR is very similar to #6703. Currently, running the following code
```python
x = T.as_tensor_variable([1., 2., 3.])
print(x[x > 1].eval())
```
runs as expected but triggers a `FutureWarning` from `numpy`:
```
/anaconda3/lib/python3.7/site-packages/theano/tensor/basic.py:6611: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
rval = inputs[0].__getitem__(inputs[1:])
[2. 3.]
```
Casting `inputs[1:]` to `tuple` returns the correct output but eliminates the warning.
> Eliminate FutureWarning

- theano/tensor/var.py
Change the import of `Iterable` from `collections.Iterable` to `collections.abc.Iterable` to future-proof against Python 3.7.8.
Caught this warning when running the PyMC3 tests.
> Fix deprecation warning.

- theano/sandbox/rng_mrg.py
Using Theano 1.0.4 via Keras 2.2.5 under Python 2.7.12, calling `keras.model.model_from_json()` for model deserialization fails at this assertion in theano at `get_substream_rstates` because `json.loads()` as called by Keras is returning a dict with unicode objects as values. This PR fixes the problem.
> use string_types instead of str in get_substream_rstates dtype assertion

- theano/compile/mode.py
- theano/gof/op.py
- theano/gof/opt.py
- theano/gof/tests/test_link.py
- theano/tensor/nnet/bn.py
- theano/tensor/nnet/tests/test_conv.py
- theano/tests/test_determinism.py
get_io_macros is still broken after this (it doesn't return its results),
but as nobody else seems to have noticed it's probably unused
The "is vs ==" ones don't seem to be a problem in practice,
but let's not scare the user unnecessarily
https://bugs.debian.org/950463
> MAINT: Avoid SyntaxWarnings on import in Python 3.8

- doc/scripts/docgen.py
Needed as build_main is no longer top-level:
https://www.sphinx-doc.org/en/master/extdev/deprecated.html
https://bugs.debian.org/955065
> DOC: Allow building with Sphinx >= 2.0

- theano/scalar/basic_scipy.py
There was a typo in the `GammaIncC` where the injected C code referenced an undefined `gammaQ` function. The function should be called `GammaQ`.
> Fixing typo in GammaIncC Op

- doc/library/tensor/basic.txt
- theano/gof/tests/test_compute_test_value.py
- theano/sparse/tests/test_basic.py
- theano/tensor/sort.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_raw_random.py
- theano/tensor/tests/test_shared_randomstreams.py
- theano/tensor/var.py
Fixes #6715 and most of #6719 (= [Debian 955471](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955471)).  Includes and supersedes #6721.
Tested (affected tests, not a full run) in:
- Debian unstable (Python 3.8, numpy 1.17, scipy 1.3)
- Debian stable (Python 3.7, numpy 1.16, scipy 1.1)
ClipTester: As noted in #6715, numpy changed its behaviour when min > max, but theano didn't.  Removed the test of this case, but not warning for it because clip is a scalar op and we don't want a warning for every entry of a large matrix.
random test_vector_args (both instances): numpy, and hence theano, now accepts size=(1,) even if low/high aren't scalars.  Removed test cases that assume it doesn't.
sparse (both instances): Only a problem with the test setup - the method it used to use for producing …
> MAINT: Be compatible with numpy 1.17 and scipy 1.3

- .gitignore
- bin/theano_nose.py
- requirements.txt
- setup.py
- theano/compat/__init__.py
- theano/compile/builders.py
- theano/compile/debugmode.py
- theano/compile/function.py
- theano/configdefaults.py
- theano/gof/cmodule.py
- theano/gof/op.py
- theano/gof/unify.py
- theano/gof/utils.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/nlinalg.py
- theano/tensor/nnet/conv.py
- theano/tensor/nnet/nnet.py
- theano/tensor/opt.py
- theano/tensor/subtensor.py
- theano/tensor/tests/mlp_test.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_subtensor.py
Fixes the scary deprecation warnings that clients see, as mentioned in #6755, and some of the other warnings in the code.
* The `compat/__init__.py` DeprecationWarning about 'collections' was already fixed in 1b9804b65ecd008cfb424752e65aced92b63ff92, not yet on PyPI.
* The `misc/frozendict.py` DeprecationWarning about 'collections' just needed to add `'Callable'` to `__all__` in that module.
For a speedy way to test this fix, make a pyenv virtualenv, use this `requirements.txt` file (my best guess on it) to install pips, and run a limited nose test:
```bash
pip install --upgrade pip setuptools virtualenv virtualenvwrapper virtualenv-clone wheel
pip install -r requirements.txt && pyenv rehash
bin/theano-nose theano/tests/test_config.py
```
I ran the limited and the full `bin/theano-nose` …
> Fix collections warnings

- README.rst
deeplearning.net is down, So update alternative web urls for install the package.
> Solving #6784 deeplearning.net is DOWN
