Theano/Theano

theano/tensor/opt.py
=> Parameterized local_elemwise_alloc_opt for GPU support

theano/sandbox/cuda/dnn.py
Added an import statement to avoid "undefined name" errors when throwing ShapeErrors.
=> Added missing import for ShapeError exception.

theano/scan_module/scan_op.py
This do what gh-2385 should have done.
=> Disable Theano gc in scan by default.

theano/sandbox/cuda/cuda_ndarray.cu
Fix gh-2374 made by @bloodmage
=> Fix truncated gpu dev pointer on windows 64 bits.

theano/sandbox/cuda/dnn.py
reported by @ziyuang. fix gh-2387
=> Fix compilation crash with cudnn on python3

theano/sandbox/cuda/cuda_ndarray.cuh
=> [FIX] Add define for PyInt_FromSize_t for Python3.

theano/gradient.py, theano/tensor/opt.py, theano/tests/test_gradient.py
The user interface is theano.gradient.grad_clip(x, lower_bound, upper_bound)
=> add GradClip op

theano/compile/profiling.py
This should fix #2402 if it is what I think it is.  Otherwise it still fixes a problem.
=> Use key to avoid comparing Apply nodes.

theano/sparse/basic.py
I also run all tests on CPU and GPU, now all warning of this type are fixed.
=> Fixed one more possible comparison with None

theano/gof/graph.py, theano/gof/tests/test_graph.py
Automatically generate a name for the different graph nodes
=> Add autoname

theano/gof/cmodule.py
I didn't test it myself, it was reported on the mailing list. I'm guessing that maybe this would work.
=> fix compilation with cygwin

theano/compile/profiling.py
This should fix the remaining problems for #2402
=> Fix all the sorts so that they will work on python 3.

theano/scan_module/scan_op.py, theano/scan_module/tests/test_scan.py
Add test case that was reported on theano-users.
=> Fix gradient of scan when some outputs are disconnected

theano/gof/cmodule.py, theano/sandbox/cuda/blas.py
This is caused by ourself and it probably happen in real use case.
=> remove warning during tests

theano/printing.py, theano/scalar/basic.py
=> Typo fixed

theano/gof/cmodule.py, theano/misc/do_nightly_build, theano/sandbox/cuda/blas.py
This is the follow up from gh-2432 to maybe get it merged faster by having travis run now and maybe someone else review it.
=> Fix lock, try to fix buildbot

theano/gof/cmodule.py, theano/misc/do_nightly_build, theano/sandbox/cuda/blas.py
These changes seem to fix the problems we have on the daily buildbot.  Especially the lock_dir change.
=> Fix buildbot

theano/tensor/nnet/neighbours.py, theano/tensor/nnet/tests/test_neighbours.py
implemented infer_shape for image2neibs op
=> Image2neibs infer shape

theano/sandbox/cuda/tests/test_fftconv.py, theano/sandbox/cuda/tests/test_gemmcorr3d.py, theano/sandbox/test_rng_mrg.py
@nouiz , @abergeron ,
Unfinished work.
I tried the changes proposed by @nouiz. Unfortunately, they did not make the tests faster.
=> Faster tests

theano/sandbox/cuda/dnn.py
see: [theano-users] cudnn R2 throws a nondescript error
I wait for confirmation that this do the good fix.
=> [WIP] Do not run cudnn available on the default GPU.

theano/sandbox/cuda/tests/test_fftconv.py, theano/sandbox/cuda/tests/test_gemmcorr3d.py
@nouiz, @abergeron,
Faster fft tests (when running them in mode "FAST_COMPILE").
=> Faster fft tests

theano/compile/debugmode.py
This make the DebugMode interface more in-line with what external clients expect.  (.linker should be an instance, not a class and have a .clone method).
I've verified that it fixes the DebugMode error in the buildbot for the scan tests.
=> Fix DebugMode error introduced by recent changes in Scan

theano/compile/function_module.py, theano/compile/profiling.py, theano/gof/cmodule.py, theano/gof/link.py, theano/gof/utils.py, theano/misc/check_blas.py, theano/sandbox/cuda/dnn.py
=> Profile import and crash fix

theano/gof/opt.py, theano/sandbox/cuda/blas.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py
Fix broadcast problems that make the meta_conv not able to time some cases.
reported by Eelke Spaak in [theano-users] Exception "Incompatible broadcastable dimensions" during meta-optimization of GpuConv
=> Conv and meta_conv

doc/extending/cop.txt, theano/compile/debugmode.py, theano/gof/cc.py, theano/gof/graph.py, theano/gof/op.py
This allows nodes to request a context to run in that will be passed in to C code and perform().
Part of the multi-gpu changes (#2182)
=> Add support for node context

theano/gof/link.py
=> Fix error message to have the right thunk. fix gh-2452

theano/compile/ops.py
In the past, we where not causing all the graph to be optimized by the shape feature. We need to add the node in the toposort order. We add only the nodes that aren't already in the shape feature.
=> Good implementation of shape_i() optimized function

theano/gof/type.py, theano/tensor/tests/test_type_other.py, theano/tensor/type_other.py
fix gh-2516
Reported by Dmitry Bogdanov
=> Crash unpickle

theano/sandbox/cuda/opt.py
Pickle can't serialize nested functions, so this stopped graphs with convolutions from being pickled. This change fixes the problem in my case.
=> Move values_eq_approx outside of function to allow pickling

theano/gof/cmodule.py, theano/misc/do_nightly_build, theano/sandbox/cuda/opt.py, theano/tensor/signal/downsample.py
This make the graph smaller, so it could speed it up too.
=> Crash fix and simpler graph

theano/scan_module/tests/test_scan.py
@nouiz, @abergeron,
`test_grad_multiple_outs_some_disconnected` was taking multiple hours in DEBUG_MODE. As the test fails in that mode, I had not seen it in the logs.
=> Speed up scan test

theano/gof/null_type.py, theano/tensor/subtensor.py
Sum gradient over dimensions where the increment was broadcasted
=> Fix advincsubtensor grad crash

theano/tensor/subtensor.py, theano/tensor/tests/test_subtensor.py
=> [CRASH] Fix crash with broadcasted increment in AdvancedIncSubtensor1 and added test

theano/gof/cmodule.py
This is a test fix for gh-1791
wait for confirmation by user that this fix the problem.
=> Canopy win

theano/scan_module/scan_op.py
This is a first step towards trying to solve the problem described by Bitton Tenessi at https://groups.google.com/d/msg/theano-users/qgsifuG78KI/rm-oIN_fUbMJ
Still missing:
=> [WIP] Detect Null gradient wrt non-sequences in scan

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/dnn.py
First commit to get feedback from @abergeron
=> Check negative strides in gpu_contiguous

theano/sandbox/cuda/blas.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py
This is an extension of #2510.
This should finish the work on optimizing max pooling with padding from CPU to GPU (CuDNN), when ignore_border is True.
=> Dnn pool support of pad

theano/tensor/tests/test_nlinalg.py, theano/tests/unittest_tools.py
This PR defines a new decorator to achieve the objective named in the title and applies it on two tests that are known to randomly go over the accepted tolerance depending on the random seed they use.
Remaining in this PR is to identify and modify the other unit tests which need such a mechanism.
Also, for now, I parametrized the decorator so that it attempts 3 times and needs at least 2 successes. These might not be the best parameters and I'm open to opinions regarding how they should be set.
=> [WIP] Mechanism for running a test multiple times with different random seeds

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py
=> do not try cudnn opt when it isn't available

theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
This PR fix a bug in the new feature added last week. We where using the C code when it was not supporting it.
Added test for that case too.
As this is for a new feature that was done last week and not publicized, we do not need to make a big deal of this. The output would have been of the wrong size too.
=> [BUG] pool with padding

theano/tensor/signal/downsample.py
Fixes bug reported by Geert Litjens at https://groups.google.com/d/topic/theano-users/tyitrWOwrMU/discussion
=> Convert inputs of maxpool to tensor

theano/gof/cc.py
=> Add missing import

.travis.yml, theano/tests/test_flake8.py
This file only considers flake8 check for theano.
=> Include pep8 autocheck test + while list (from blocks) #2503

theano/tensor/basic.py, theano/tensor/tests/test_basic.py
=> Fix the broadcastable pattern of tensordot's output

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_dnn.py
Do not merge yet. We need confirmation that it fix the problem.
=> [WIP] Disable some optimization that could cause problem with cudnn v2 rc3.

theano/compile/debugmode.py, theano/gof/type.py, theano/scan_module/scan_op.py
This fixes two problems with the buildbot in DebugMode.
=> Fix problems in the buildbot

theano/sandbox/cuda/dnn.py
It seems cudnn has some dark corners when dealing with non-contiguous data so disable that for now.
=> Disable non-contiguous input for cudnn.

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/opt.py
This bring back some lost speed up.
=> Cleanup dnn conv stuff.

theano/sandbox/cuda/blocksparse.py, theano/sandbox/cuda/cudnn_helper.h, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/dnn_fwd.c, theano/sandbox/cuda/dnn_gi.c, theano/sandbox/cuda/dnn_gw.c, theano/sandbox/cuda/opt_util.py, theano/sandbox/cuda/tests/test_blocksparse.py, theano/sandbox/cuda/tests/test_dnn.py
This should fix the bad output from #2607.
=> Fix alpha_merge and cudnn conv gradient

theano/scan_module/scan_op.py, theano/scan_module/tests/test_scan.py
=> [CRASH] Fix crash with scan grad and add unit test

doc/library/config.txt, theano/printing.py, theano/sandbox/cuda/opt.py
Some minor fixes that are accumulated in my local tree
=> Minor fixes

theano/sandbox/cuda/dnn_base.c
It's just a small typo I guess. [Official reference](https://docs.python.org/3.1/howto/cporting.html#conditional-compilation).
=> Python3 compatibility.

theano/gradient.py, theano/tests/test_gradient.py
=> Add connection_pattern

doc/tutorial/debug_faq.txt
- fixed the order of arguments in an isinstance() function call
- changes the expected output of a command to match the actual output
=> fix code samples in debug_faq docs

theano/scan_module/scan_op.py, theano/scan_module/tests/test_scan.py
Fix a crash when taking the gradient of a scan due to scan.connection_pattern() falsely reporting that some inputs where not used to compute any outputs. The underlying issue was the function _get_inner_inps, used to get the inner inputs corresponding to some outer input which produces the wrong results. This problem only occurred when certain numbers of mitmots, mitsots, sitsots and nitsots were used.
=> [CRASH] Fix scan_op.connection_pattern and add test

theano/tensor/nnet/conv.py, theano/tests/test_rop.py
Partial cherry-pick of https://github.com/Theano/Theano/pull/622
=> R op for Conv2d

doc/dev_start_guide.txt, doc/index.txt, doc/install.txt, doc/sandbox/index2.txt
This mainly cleans up the Mac install instructions but there are some other fixes.
Closes #2547.
=> Doc update

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/sandbox/cuda/cuda_ndarray.cuh, theano/tensor/nnet/conv.py, theano/tensor/nnet/tests/test_conv.py
=> Conv2d test

theano/sandbox/rng_mrg.py, theano/tensor/shared_randomstreams.py
=> Allow MRG RNG shared variables to be recognised as such

theano/scan_module/tests/test_scan.py, theano/tests/test_rop.py
FIxes two tests which would fail in float32 in the daily buildbot.
Also fixes 3 minor pep8 issues on orthogonal tests.
=> Fix buildbot tests

theano/tensor/basic.py, theano/tensor/tests/test_basic.py, theano/tensor/var.py
To deal with Theano/Theano#927
=> Added support for __divmod__ and __rdivmod__, with a basic unit test.

theano/sandbox/rng_mrg.py, theano/tensor/shared_randomstreams.py
=> Remove weak references, which aren't picklable

theano/sandbox/cuda/opt.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/tests/test_scan.py, theano/scan_module/scan_op.py, theano/scan_module/scan_opt.py, theano/scan_module/scan_utils.py
We need to test it more before merge.
=> Partial Revert 5ed8d9232d217ec73da28b2f9dbeb410bb9c208f

theano/sandbox/cuda/cula.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_cula.py, theano/sandbox/cuda/tests/test_opt.py
@lamblin This is incomplete, changes need to be done:
* Tests need to be added
* Optimization is need to be added
* Move cula_gpu_solve function inside make_thunk
=> Theano solve GPU Cula Op

doc/internal/how_to_release.txt, theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/sandbox/cuda/cuda_ndarray.cuh, theano/tensor/nnet/conv.py
- make CudaNdarray_SIZE return a size_t
- more informative error messages for shape mismatches in Conv2D
This fixes #2669
=> Small fixes after the release

theano/sandbox/cuda/cula.py
@lamblin @nouiz please check my PR for the cula availabilty.
=> Fix for Raise cula error

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
@abergeron,
Want to check in to see if I am doing the right thing. I based what I was doing to create [out] on local_subtensor_merge.
=> CCW remove useless slice

theano/scan_module/tests/test_scan.py
Also doing some pep8 and un-reverting a line in the tests for scan.
=> Add test for gpu memory usage

theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
Discussed here: https://groups.google.com/forum/#!topic/theano-users/rKF07NUfSRQ
=> implements max_pool_2d_same_size + test

theano/printing.py
Slightly extends the documentation of `pydotprint()`
=> Update documentation of printing.py

theano/tensor/extra_ops.py, theano/tensor/tests/test_extra_ops.py
Instead of a wrapping the numpy function bincount, I am creating a theano graph that implements exactly the same functionality. I am also deprecating the Op as it shouldn't be used anymore.
=> fixes #2580: theano function for bincount

theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/blas.py, theano/sandbox/gpuarray/conv.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/gpuarray/kernel_codegen.py, theano/sandbox/gpuarray/neighbours.py, theano/sandbox/gpuarray/nnet.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/subtensor.py, theano/sandbox/gpuarray/tests/test_basic_ops.py, theano/sandbox/gpuarray/tests/test_blas.py, theano/sandbox/gpuarray/tests/test_conv_cuda_ndarray.py, theano/sandbox/gpuarray/tests/test_elemwise.py, theano/sandbox/gpuarray/tests/test_neighbours.py, theano/sandbox/gpuarray/tests/test_nnet.py, theano/sandbox/gpuarray/tests/test_opt.py, theano/sandbox/gpuarray/tests/test_scan.py, theano/sandbox/gpuarray/tests/test_subtensor.py, theano/sandbox/gpuarray/tests/test_type.py
Use relative import in sandbox/gpuarray to allow for easier moving later.
=> Relative import

theano/sandbox/cuda/tests/test_basic_ops.py, theano/sandbox/gpuarray/tests/test_basic_ops.py, theano/sandbox/gpuarray/tests/test_conv_cuda_ndarray.py, theano/sandbox/gpuarray/tests/test_neighbours.py, theano/sandbox/gpuarray/tests/test_subtensor.py, theano/tensor/basic.py, theano/tensor/opt.py, theano/tensor/subtensor.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_blas.py, theano/tensor/tests/test_elemwise.py, theano/tensor/tests/test_subtensor.py
These are most of the test fixes that I will need for multi-gpu for code that is outside sandbox/gpuarray/
=> Merge test fixes

theano/gof/lazylinker_c.py
This helps when running jobs on Helios.
=> Lazylinker c problem

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
fix gh-2585 ?
not ready to merge. Not tested
=> Better same_shape implementation

theano/tensor/extra_ops.py
Replace RepeatOp with Theano graph using tensor.tile
=> Replace RepeatOp with Theano graph, using tensor.tile

theano/compile/debugmode.py
This should fix the compilation of `cuda_convnet`, and maybe also `cuda_ndarray`.
Fixes https://github.com/lisa-lab/pylearn2/issues/1463
=> Call `Op.make_thunk` before generating the C code.

theano/compile/debugmode.py
=> Remove dead code and comments.

theano/compile/debugmode.py, theano/gof/graph.py, theano/gof/opt.py, theano/gof/type.py, theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/tests/test_dnn.py
This makes the custom values_eq_approx for DebugMode work.
=> Fix allocempty

theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
Help needed in C code. 
In line 386, z[0] is always 0 no matter the value of the var 'maximum'.
I don't understand why.
=> c code of maxpool

doc/tutorial/faq.txt, doc/tutorial/faq_tutorial.txt, doc/tutorial/index.txt
=> Tutorial for when a subset of the weight matrix should get updated

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
See:
https://github.com/Theano/Theano/issues/864
Was curious about best practices for inverse pairs like Log and Exp, because Log will return a NaN if the input is less than 0.
=> Remove consecutive functional inverses to optimize

theano/scalar/tests/test_basic.py, theano/tensor/basic.py, theano/tensor/tests/test_basic.py
Also move tests to theano/tensor.
=> Update documentation for gradient of clip

theano/sandbox/gpuarray/basic_ops.py
Handle case where v has 0 dimensions.
=> [CRASH with Scan in new backend]

theano/sandbox/cuda/nnet.py, theano/sandbox/cuda/tests/test_nnet.py, theano/sandbox/gpuarray/nnet.py
=> [REGRESSION, CRASH]Fix crash gpu

doc/faq.txt, doc/optimizations.txt, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/tests/test_opt.py, theano/tensor/opt.py, theano/tensor/tests/test_opt.py
Initial version for local_remove_all_assert optimization with tests, for CCW ticket [#TH-2495](https://github.com/Theano/Theano/issues/2495) currently **without** documentation.
=> Register local_remove_all_assert

theano/sandbox/gpuarray/opt.py
I fucked up when merging #2809 and this introduced a syntax error in master.  This fixes it.
=> Fix syntax error.

theano/scan_module/scan_utils.py
Adresses the comment raise by @lamblin  in #2769 about tests failing in #2815.
=> Fix condition in equal_computations

theano/gof/graph.py, theano/scan_module/tests/test_scan.py, theano/sparse/sandbox/test_sp.py, theano/sparse/tests/test_basic.py, theano/tensor/tests/test_elemwise.py, theano/tensor/tests/test_extra_ops.py, theano/tensor/tests/test_opt.py, theano/tensor/tests/test_slinalg.py, theano/tensor/tests/test_subtensor.py, theano/tests/test_tutorial.py
Do not merge now, more to come. I want travis to test one of the change.
NEWS.txt:
- This PR change how we handle mode optimizer. If it is a query object, we cache the query the first time we need it. This allow to speed up tests. But this change the interface. If some optimization get registered after, the mode won't requery it, so it won't find the new registered optimization.
=> [MRG] Faster test

theano/gof/graph.py, theano/tensor/tests/test_opt.py
I closed the other PR to early by mistake.
=> finish gh-2768

theano/gof/op.py, theano/gof/opt.py, theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py
This PR replace gh-2815 as it have a better way to fix it.
=> Merge conv2

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_dnn.py, theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
I added some follow up in gh-2792
fix gh-2774
=> Average pool CPU with python code

doc/library/index.txt, doc/library/misc/pkl_utils.txt, doc/tutorial/loading_and_saving.txt, theano/misc/pkl_utils.py, theano/misc/tests/test_pkl_utils.py
I started work on a custom pickler for shared variables. It is supposed to get values from shared variables and save it as npz file during pickling and create shared variables back during unpickling. The work is based on bartvm/blocks#579 and https://code.google.com/p/pynnet/source/browse/trunk/pynnet/base.py.
CC
@bartvm
=> WIP: Custom pickler for shared variables

theano/scalar/basic.py
See: https://github.com/Theano/Theano/pull/2750/files#diff-3a81c280f7c4d50677c682af9ee70240R1171
This would be better with a test, but I don't have the time.
=> Fix nit spotted by @dwf

theano/tensor/opt.py
=> Change the elemwise input fusion limit to 32.

theano/configdefaults.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py
@lamblin I have added a new optimization for the issue #2471. Especially I am not sure how to do the test for this function.
=> Assert no CPU op for #2471

theano/tensor/signal/downsample.py
all test passed with DebugMode
=> Maxpool c code

theano/sandbox/cuda/basic_ops.py, theano/tensor/basic.py, theano/tensor/tests/test_basic.py
(#2613, #2747)
Negative axis were automatically handled by numpy implementation inside
Join.{perform,c_code}. However, both Join.grad and
GpuJoin.{perform,c_code,grad} implementations were not thought to take care of
negative axis.
This commit adds convertion of axis when negative such that it is always
positive. Fixing it in Join._make_node_internal also fix GpuJoin at the
same time. Symbolic axis need to be taken care of by adding a
tensor.switch to increment axis when necessary. However, assert_op can
be removed by some optimizer modes and thus exceeding negative axis can
be undetected. Another option is to hardcode asserts in
{Gpu}Join.{perform, c_code} but that means maintaining a similar code
4 times...
=> (#2613, #2747) Add handling of negative axis for Join and GpuJoin

theano/sandbox/gpuarray/blas.py, theano/sandbox/gpuarray/gpuarray_helper.h, theano/sandbox/gpuarray/tests/test_elemwise.py, theano/sandbox/gpuarray/type.py
This fixes the memory leak in the DLT LSTM example and allows training to complete in float32 with the new backend.
=> Lstm fixes

theano/scan_module/scan_utils.py
=> first commit to Make equal_computations more efficient

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> Prod opts [WIP]

theano/sandbox/gpuarray/subtensor.py
There where problems when the data element had to be broadcasted in some cases.
=> Fix problems with advsub in the gpuarray backend

theano/gof/cmodule.py
Wait before merging that we have confirmation that it help users with the problem
=> Keep the lock when we check the key

theano/scan_module/scan_opt.py, theano/scan_module/tests/test_scan.py
This is a fix for the segfault issue reported on the theano-users mailing list  (https://groups.google.com/forum/#!topic/theano-users/ryurT5G6G7M/discussion).
The issue was with the scanOp_pushout_seqs optimization which was trying to push out computation that did not depend on sequences and, therefore, should have been handled by scanOp_pushout_non_seqs.
=> [CRASH] Scan index error

.travis.yml, theano/ifelse.py, theano/sandbox/cuda/opt.py, theano/tests/test_ifelse.py
fix https://github.com/Theano/Theano/issues/2913
fix https://github.com/bartvm/blocks/issues/633
=> Ifelse remove warning and speed up

theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_basic_ops.py, theano/sandbox/cuda/tests/test_opt.py, theano/tensor/basic.py, theano/tensor/blas.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_blas.py
=> AllocEmpty

theano/sandbox/cuda/basic_ops.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/rng_mrg.py
I saw this as being a significant time in the profile from one user.
=> Speed reduce 100

theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/rng_mrg.py
I'm talking about https://github.com/Theano/libgpuarray/pull/46.
=> Follow the change in call protocol in libgpuarray.

theano/sandbox/cuda/tests/test_nnet.py
=> Upate test_nnet.py with language fixes

theano/sandbox/cuda/blas.py, theano/sandbox/cuda/tests/test_blas.py
@bouthilx. Addresses issue #2378. Work in progress.
- Moved batched gemm (by @benanne) to sandbox/cuda/blas
- Made unit test
- TODO: C code
=> GPU batched gemm

doc/extending/graphstructures.txt, doc/library/compile/debugmode.txt
Was reading through the docs and found 2 errors in the code snippets.
These changes are to make those 2 run.
=> Small Docs Fixes

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/opt.py
Profiling output after optimization: https://gist.github.com/t13m/f6b2cc1f23229eeabbba#file-profile_after_opt0
Profiling output befoer optimization: https://gist.github.com/t13m/f6b2cc1f23229eeabbba#file-profile_before_opt0
=> Remove useless gpu_from_host(host_from_gpu(x)) op.

theano/sandbox/cuda/blas.py, theano/sandbox/cuda/tests/test_blas.py
Wrote a quick gradient for the new batched_dot op just to get the ball rolling. Let me know what else needs to be written.
=> Added small gradient calculation for batched_dot

theano/sandbox/cuda/basic_ops.py
Optimization was failing in the previous version.
=> fix casting in advanced subtensor.

doc/library/tensor/basic.txt, theano/tensor/basic.py, theano/tensor/tests/test_basic.py
NEWS.txt: Add tensor.{allclose,isclose}
=> Added tensor implementation of numpy's allclose function.

theano/gof/fg.py, theano/gof/opt.py, theano/gof/optdb.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/opt.py, theano/tensor/opt.py
When register a optimizer to a EquilibiumOptimizerDB instance, 'final_opt' can be used as argument to make it a final_optimizer in the same time.
=> Opt EquilibiumOptimizer to do less pass

theano/tensor/nnet/conv3d2d.py, theano/tensor/nnet/tests/test_conv3d2d.py
=> Xeray master

doc/library/compile/nanguardmode.txt, doc/tutorial/nan_tutorial.txt, theano/compile/nanguardmode.py, theano/compile/tests/test_nanguardmode.py
This is a tentative tutorial about how to deal with NaNs. If you have more suggestions, please let me know so that I can add them into the tutorial. 
(A reply for #2770)
=> Tutorial about NaNs

theano/tensor/extra_ops.py, theano/tensor/tests/test_extra_ops.py
=> Class Unique 

theano/tensor/nnet/nnet.py, theano/tensor/nnet/tests/test_nnet.py
=> Make sure crossentropy op always raise error for negative index

theano/tensor/raw_random.py, theano/tensor/tests/test_raw_random.py
This should fix the problem reported at https://groups.google.com/d/topic/theano-users/dVvXV7PNLT8/discussion and https://groups.google.com/d/topic/theano-users/0J0ZUtTjvyc/discussion
=> Do not try to pickle `method_descriptor` objects

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/cuda_ndarray.cuh, theano/sandbox/gpuarray/basic_ops.py
=> [MRG] Implement c_code for GpuReshape

theano/sandbox/cuda/blas.py, theano/sandbox/cuda/conv.cu, theano/sandbox/gpuarray/conv.cu, theano/sandbox/gpuarray/conv.py
This should stop the buildbot from aborting the DEBUG_MODE part.
=> Don't assert for array sizes, just raise an exception.

doc/library/config.txt, doc/tutorial/debug_faq.txt, doc/tutorial/using_gpu.txt
Started writing the documentation for the assert_no_cpu_op.
=> Adding the documentation for assert_no_cpu_op #2881.

theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
max pool grad grad python code added
all tests passed
=> [MRG] implement padding for max pool grad grad

theano/compile/debugmode.py, theano/compile/mode.py, theano/gof/tests/test_vm.py, theano/gof/vm.py
Also make DebugMode not check strides by default.
=> [MRG] FAST_COMPILE now lazy by default

theano/compile/debugmode.py, theano/compile/mode.py, theano/compile/monitormode.py, theano/compile/profilemode.py, theano/scan_module/scan_op.py, theano/scan_module/tests/test_scan.py
I'm not sure it is the cleanest way of solving that problem.
Also, it is missing a unit test.
=> [MRG] Fix for using MonitorMode with scan

theano/printing.py
addressing the issue here: https://github.com/Theano/Theano/issues/2988
=> Add exception when using an old version of pydot

theano/configparser.py, theano/tensor/blas.py
I tested that without MKL, with MKL installed, with MKL installed and partially removed, both for a global installation and for an installation as a user, everything seemed to work.
=> Fixes for detection of mkl for win32 with anaconda

theano/compile/function_module.py, theano/compile/mode.py, theano/compile/profilemode.py, theano/gof/compiledir.py, theano/gof/compilelock.py, theano/gof/optdb.py, theano/gof/tests/test_vm.py, theano/gof/type.py, theano/misc/elemwise_time_test.py, theano/sandbox/cuda/tests/test_fftconv.py, theano/sandbox/cuda/tests/test_type.py, theano/sandbox/gpuarray/opt.py, theano/scalar/tests/test_basic_sympy.py, theano/tensor/elemwise.py, theano/tensor/inplace.py, theano/tensor/shared_randomstreams.py, theano/tensor/slinalg.py, theano/tensor/subtensor.py, theano/tensor/var.py, theano/tests/breakpoint.py, theano/tests/disturb_mem.py, theano/tests/test_dictionary_output.py, theano/tests/test_flake8.py, theano/tests/test_printing.py
This also somehow revealed a bunch of errors in files that where not on the whitelist, so I fixed those.
I also took off the whitelist files that pass due to this change.
=> [MRG] Ignore E501 (lines too long) for the flake8 test.

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> added optimization for dividing by one

bin/theano-nose, theano/tests/main.py
=> raising exception for running theano.test() with device=gpu

theano/scalar/tests/test_basic.py
=> Add missing test.

doc/tutorial/extending_theano.txt
Concerning #3085. Requested by Pascal Lamblin.
=> minor omission in previous ticket

theano/compile/tests/test_function_module.py, theano/sandbox/gpuarray/tests/test_basic_ops.py, theano/sandbox/scan_module/tests/test_scan.py, theano/scan_module/tests/test_scan.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_complex.py, theano/tensor/tests/test_fourier.py, theano/tensor/tests/test_opt.py, theano/tests/test_rop.py
I'm not sure of what I did but I hope it will be ok.
Thanks again 
Best
Thomas
=> knownfailuretest

.travis.yml
Hopefully, they will be faster combined.
=> Merge travis part

theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/comp.py, theano/sandbox/gpuarray/cudnn_helper.h, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/dnn_base.c, theano/sandbox/gpuarray/dnn_conv_base.c, theano/sandbox/gpuarray/dnn_fwd.c, theano/sandbox/gpuarray/dnn_gi.c, theano/sandbox/gpuarray/dnn_gw.c, theano/sandbox/gpuarray/gpuarray_helper.h, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/opt_util.py, theano/sandbox/gpuarray/tests/test_dnn.py, theano/sandbox/gpuarray/tests/test_nnet.py, theano/tensor/basic.py
This is a follow up of gh-3080.
What is still needed is refactor/move the misssing conv cudnn tests.
=> gpuarray in new back-end

theano/scan_module/scan_utils.py, theano/scan_module/tests/test_scan.py
This is for the issue raised in : https://groups.google.com/forum/#!topic/theano-dev/3-tRoZcnMuI
I don't yet have a test case for it.
=> Match broadcastable pattern of original variable

doc/library/tensor/basic.txt, theano/tensor/basic.py, theano/tensor/tests/test_basic.py
=> Finished mgrid and ogrid

theano/scan_module/scan_op.py
where izip is from theano.compat
=> Changed itertools.izip to izip for compatibility

doc/library/compile/index.txt, doc/library/compile/nanguardmode.txt, doc/tutorial/index.txt, doc/tutorial/nan_tutorial.txt
Add documentations about how to use NanGuardMode in theano, and added the way of using it in nan_tutorial. 
This is a fix for #3086 .
=> add docs for NanGuardMode

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
#1902
local optimization
Alloc(Alloc(m, x, 1), x, y) -> Alloc(m, x, y)
=> Opt: Alloc(Alloc(...),...) -> Alloc(...) #1902

theano/sparse/basic.py, theano/sparse/tests/test_basic.py
fix https://github.com/Theano/Theano/issues/3123
=> Add elemwise `conj` to `sparse`.

theano/tensor/tests/test_var.py, theano/tensor/var.py
This demonstrate how to fix gh-3040.
=> [WIP] Allow numpy.exp(theano_var) to build a graph.

theano/tensor/extra_ops.py, theano/tensor/tests/test_extra_ops.py
Can you let me know if I am on the right track? @abergeron I wrote the following based upon my memory of our conversation.
Kelvin
=> Cpu Contiguous

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> Make local_merge_alloc apply in more case

theano/tensor/extra_ops.py
This should fix travis that is failing on master:
https://travis-ci.org/Theano/Theano/builds/71255496
=> [TESTS] this fix a test while having concurrent PR that force pep8.

theano/compile/tests/test_debugmode.py
=> __props__ for theano/compile/tests/test_debugmode.py

theano/scan_module/scan_opt.py, theano/scan_module/tests/test_scan.py
this is preemtive fix. It could cause an crash or bad value. as_while isn't much used.
=> Don't push out the outputs of an 'as_while' Scan

theano/gof/compilelock.py
=> Don't remove compilelock we don't own

theano/sparse/basic.py, theano/sparse/opt.py
All __props__ checked in theano/sparse folder.
=> Props sparse

theano/gof/cc.py, theano/gof/tests/test_cc.py
Fix issue reported at https://groups.google.com/d/topic/theano-users/6dLaEqc2R6g/discussion
The test brings up a different problem.
=> Fix CLinker

theano/tensor/extra_ops.py
=> Props corrige2

theano/misc/check_blas.py
GPU gemm comparisons are getting too fast. Added a default 5000x5000x5000 test.
=> add larger matrix for check_blas

doc/extending/cop.txt, doc/extending/fibby.txt, doc/extending/op.txt, doc/tutorial/gpu_data_convert.txt, doc/tutorial/using_gpu.txt, theano/tests/test_gradient.py, theano/tests/test_rop.py, theano/tests/test_tutorial.py
=> Props tests

theano/typed_list/basic.py
All __props__  checked in the folder theano/typed_list
=> __props__ to basic.py

theano/tensor/nnet/Conv3D.py, theano/tensor/nnet/ConvGrad3D.py, theano/tensor/nnet/ConvTransp3D.py, theano/tensor/nnet/conv3d2d.py, theano/tensor/nnet/neighbours.py, theano/tensor/nnet/nnet.py
All __props__ checked in folder tensor/nnet/
=> Props tensor nnet

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/sandbox/cuda/cuda_ndarray.cuh, theano/sandbox/cuda/opt.py, theano/sandbox/gpuarray/subtensor.py, theano/tensor/tests/test_subtensor.py
advance gh-3111
todo before merging:
=> [WIP, BUG, CRASH] Fix GpuAdvancedIncSubtensor1_dev20 with negative index

theano/sparse/sandbox/sp.py, theano/sparse/sandbox/sp2.py
=> Props sparse sandbox

theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/dnn.py
=> Props sandbox gpuarray

theano/sandbox/fourier.py, theano/sandbox/multinomial.py, theano/sandbox/neighbourhoods.py, theano/sandbox/rng_mrg.py
=> Props sandbox

theano/tensor/extra_ops.py
Adds a dimension check pull request at #2949
=> Cpu Contiguous Dim Check

theano/configdefaults.py, theano/gof/toolbox.py
=> Debug flag print rejected optimizations when validate fails

theano/sandbox/cuda/basic_ops.py
This fixes a memory leak discussed in #3079. 
fix gh-3079
=> Free new_shape before exiting in gpu_reshape

theano/gof/fg.py, theano/gof/link.py, theano/gof/op.py, theano/gof/utils.py, theano/tensor/opt.py
I implemented proper stack trace copying for a couple of functions, and changed the printing of the stack trace. Now, a stack trace is list of lists of tuples. 
Sorry, I had to create a new pull request. I completely messed up my other branch trying to do rebase myself.
=> Further work on issue #3018.

theano/gof/graph.py, theano/gof/op.py, theano/gof/unify.py, theano/tests/test_flake8.py
It seems I forgot this pull request
=> Flake8 gof sequel

theano/sandbox/gpuarray/tests/test_basic_ops.py, theano/sandbox/gpuarray/type.py, theano/scalar/basic.py, theano/tensor/tests/test_basic.py
this fix 2 tests in the buildbot in debugmode
theano-nose theano/tensor/tests/test_basic.py:test_comparison.test_{isclose,allclose}
=> [BUG, TEST] Fix Sng handling of nan and fix related test

theano/tensor/sort.py, theano/tensor/tests/test_sort.py
=> changing sort.grad to work with other ndim

theano/sandbox/cuda/cuda_ndarray.cu, theano/tensor/subtensor.py
=> cuda bugfix with array over 2g

theano/misc/pycuda_example.py
=> props to theano/misc/pycuda_example.py

theano/tensor/basic.py, theano/tensor/blas.py, theano/tensor/elemwise.py, theano/tensor/extra_ops.py, theano/tensor/fourier.py, theano/tensor/io.py, theano/tensor/nlinalg.py, theano/tensor/opt.py, theano/tensor/raw_random.py, theano/tensor/slinalg.py, theano/tensor/sort.py, theano/tensor/subtensor.py, theano/tensor/type_other.py, theano/tests/test_printing.py
=> Props tensor

theano/gof/fg.py, theano/gof/link.py, theano/gof/op.py, theano/gof/utils.py, theano/tensor/opt.py
It fix one condition created in gh-3077.
This also fix the small comment there.
=> Stack trace fix (needed for the summer school)

theano/gof/compilelock.py
fix gh-3234
This came up another time before, so we should stop confusing user in corner case.
=> Don't use python random generator durint Theano compilation

theano/sandbox/cuda/blas.py
#2259 changed `BaseGpuCorrMM` to accept custom padding in `border_mode` and warn against using `pad`, but the docstring of `GpuCorrMM` was not updated accordingly. This PR updates the docstring to match the implementation. It removes the warning that `border_mode='full'` can be slower than `GpuCorrMM_gradInputs` because that would need to go with a lengthy explanation on how to use the latter instead, it's not *always* slower, and it's probably just confusing end users.
=> Fix outdated description of border_mode in GpuCorrMM constructor

theano/sandbox/cuda/dnn.py
#3245 rendered part of the `local_conv_dnn()` graph optimizer inoperable (due to an assertion on `direction_hint` in `dnn_conv()` being too strict, as described in #3248) and slow (due to `GpuDnnConvGradI` not being used any more, as described in #3249). This PR fixes both in one go, going for the third solution outlined in #3249.
It also resolves #2644, via the first solution proposed in https://github.com/Theano/Theano/issues/2644#issuecomment-84032628.
Fixes #3249. Closes #3248.
=> Fix GpuDnnConvGradI not being inserted automatically

theano/gof/utils.py, theano/tensor/var.py
This should fix unhelpful stack traces on Windows.
=> Also match Windows version of paths

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/tests/test_dnn.py, theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
@nouiz, resolves issue #2792 (WIP).
- I used the names given in issue #2792, although I feel that they clash too much against the current nomenclature.
- There is probably too much code duplication.
- Should I write the C code for `AveragePoolGrad`?
=> Average pooling

theano/sandbox/cuda/GpuConv3D.py, theano/sandbox/cuda/GpuConvGrad3D.py, theano/sandbox/cuda/GpuConvTransp3D.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/elemwise.py, theano/sandbox/cuda/extra_ops.py, theano/sandbox/cuda/fftconv.py, theano/sandbox/cuda/kernel_codegen.py, theano/sandbox/cuda/nnet.py, theano/sandbox/cuda/nvcc_compiler.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/rng_curand.py, theano/sandbox/cuda/type.py, theano/sandbox/cuda/var.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/comp.py, theano/sandbox/gpuarray/conv.py, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/gpuarray/kernel_codegen.py, theano/sandbox/gpuarray/nnet.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/subtensor.py, theano/sandbox/gpuarray/type.py, theano/sandbox/linalg/ops.py, theano/sandbox/scan_module/__init__.py, theano/sandbox/scan_module/scan.py, theano/sandbox/scan_module/scan_op.py, theano/sandbox/scan_module/scan_utils.py
Numpydoc for the second part of sandbox folder.
=> Numpydoc sandbox 2

theano/sandbox/cuda/dnn.py
=> numpydoc for theano/sandbox/cuda/dnn.py

theano/scalar/basic.py, theano/scalar/basic_scipy.py, theano/scalar/basic_sympy.py, theano/scalar/sharedvar.py, theano/typed_list/basic.py, theano/typed_list/type.py
Numpydoc for both folders : theano/typed_list and theano/scalar.
=> Numpydoc typed list scalar

doc/library/compile/function.txt, theano/compile/debugmode.py, theano/compile/function.py, theano/compile/function_module.py, theano/compile/pfunc.py, theano/compile/profilemode.py, theano/compile/profiling.py, theano/compile/tests/test_function_module.py, theano/gof/cc.py, theano/gof/fg.py, theano/gof/link.py, theano/gof/tests/test_vm.py
This PR allow users to swap sharedvariable when copy a function. Test included.
Please review this PR.
I will add another feature "delete update" in this PR later.
=> Swap SharedVariable

theano/sandbox/cuda/opt.py
compile is not correctly referenced and fails with "AttributeError: 'builtin_function_or_method' object has no attribute 'optdb'"
=> Fix AttributeError: 'builtin_function_or_method'

doc/LICENSE.txt, doc/index.txt, doc/install.txt, doc/library/config.txt, doc/tutorial/examples.txt, theano/compile/builders.py, theano/compile/mode.py, theano/compile/nanguardmode.py, theano/configdefaults.py, theano/gof/optdb.py, theano/gof/tests/test_opt.py, theano/misc/elemwise_openmp_speedup.py, theano/misc/pycuda_example.py, theano/sandbox/cuda/elemwise.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/tests/test_opt.py, theano/scalar/basic.py, theano/tensor/opt.py, theano/tensor/tests/test_gc.py, theano/tests/test_flake8.py
Follow up of #3263 since @nouiz is unavailable for the next two weeks.
=> Nouiz mixed

theano/tensor/basic.py
This will eventually allow us to exploit sandbox.cuda.blas.BatchedDotOp to perform batched tensor dot products.
=> Implement batched_tensordot in terms of batched_dot

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
I made a new PR regarding #399 and #3149 .
@carriepl , I need to talk to you once more to make sure that everything is ok and tests are expressive enough.
=> Prod dimshuffle opt

theano/gof/opt.py, theano/gof/tests/test_opt.py
ref: https://github.com/pymc-devs/pymc3/issues/803
=> Deactivate merge of assert as it cause cycle in the graph

theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py
We need to change it. The current default isn't useful and cause slower code as cudnn do not support it.
=> Warn about pending ignore_border default value change.

theano/printing.py
follow up from gh-3279 to fix pep8.
when travis pass anyone can merge.
=> Small visual changes (blue color) (bis)

doc/library/config.txt, theano/gof/cmodule.py, theano/printing.py, theano/sandbox/cuda/dnn.py, theano/tensor/basic.py
=> [CRASH] fix crash on Raspberry Pi 1

theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py
=> Gpu reshape opt.

theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py, theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> GpuReshape opt.

theano/gof/opt.py, theano/gof/tests/test_opt.py, theano/sandbox/cuda/tests/test_dnn.py
if they are identical, as well as other Ops that do not take any input.
@aalmah, can you check that this removes one of the convolution/pooling from your graph?
@vdumoulin, this may also fix the issue you had with batch normalization and DNN convolutions. Can you check?
=> Enable merging of GpuDnnPoolDesc

theano/scan_module/scan_opt.py
Fixes the docstring for the scan optimizations.
=> Fixed the docstring for the scan_opt.

theano/sandbox/gpuarray/gpuarray_helper.h, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/subtensor.py, theano/sandbox/gpuarray/tests/test_subtensor.py, theano/tensor/tests/test_subtensor.py, theano/tests/test_flake8.py
This also fixes a number of problems with GpuAdvancedIncSubtensor1_dev20 and makes it raise IndexError appropriately.
This depends on https://github.com/Theano/libgpuarray/pull/63
=> Implement GpuAdvancedSubtensor1 for gpuarray

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/tests/test_dnn.py
=> fix shape mismatch in GpuDnnPoolGrad

theano/gof/opt.py, theano/tensor/opt.py, theano/tensor/tests/test_opt.py
make it call itself recursively.
see issue #2971
=> Optimize local_fill_sink

theano/sandbox/gpuarray/blas.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/opt_util.py, theano/sandbox/gpuarray/tests/test_blas.py, theano/sandbox/gpuarray/type.py, theano/tests/test_flake8.py
This requires https://github.com/Theano/libgpuarray/pull/77.
=> Enables float16 gemm on gpuarray when the cuda version supports it

theano/gof/opt.py, theano/gradient.py, theano/printing.py
Also better error message, remove duplicate output and code simplification
=> Faster merge

doc/library/tensor/basic.txt, theano/sandbox/cuda/opt.py, theano/sandbox/gpuarray/opt.py, theano/sparse/basic.py, theano/tensor/basic.py, theano/tensor/fourier.py, theano/tensor/raw_random.py, theano/tensor/tests/test_basic.py
=> Numpy-like interface for stack.

doc/library/tensor/nnet/index.txt, theano/compile/profiling.py, theano/gradient.py, theano/sandbox/cuda/opt.py, theano/scalar/basic.py, theano/tensor/basic.py, theano/tensor/nnet/__init__.py, theano/tensor/nnet/bn.py, theano/tensor/nnet/nnet.py, theano/tensor/opt.py
Doc, allow to be inplace, printing, var name, function name, fast_compile
All this found while reviewing/testing the BN code.
=> BN follow up

doc/library/tensor/basic.txt, theano/tensor/basic.py
=> More explicit description for axis insertion in shape_padaxis

theano/compile/function_module.py, theano/gof/opt.py, theano/tensor/basic.py, theano/tensor/blas_c.py, theano/tensor/tests/test_blas_c.py
Work around crash in [[theano-users] Strange error with CLinker](https://groups.google.com/forum/#!msg/theano-users/6dLaEqc2R6g/51fH3TC6qf0J)
The cause of the crash isn't currently know or fixed. But I fixed the second error. This add an optimization for that use case that happen to fix the error.
=> crash fix and cgemv optimization

theano/sandbox/linalg/tests/test_linalg.py, theano/sandbox/tests/test_rng_mrg.py, theano/scan_module/tests/test_scan.py, theano/sparse/sandbox/test_sp.py, theano/sparse/tests/test_basic.py, theano/tensor/nnet/tests/test_conv.py, theano/tensor/nnet/tests/test_conv3d.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_blas.py, theano/tensor/tests/test_elemwise.py, theano/tensor/tests/test_extra_ops.py, theano/tensor/tests/test_keepdims.py, theano/tensor/tests/test_nlinalg.py, theano/tensor/tests/test_opt.py, theano/tensor/tests/test_slinalg.py, theano/tensor/tests/test_subtensor.py, theano/tests/unittest_tools.py
Hopefully, this will fix the doc on the web site
=> Don't crash with old nosetests

theano/d3viz/d3viz.py
Fix for issues described in #3426.
=> Remove Carriage returns and basename call in d3viz.

theano/scan_module/scan_opt.py, theano/scan_module/tests/test_scan.py
=> Scan push out seq scan

.travis.yml, doc/install.txt, setup.py
1.7.0 was released in 2012 or 2013.
This will make sure numpy support multiple axis on some reduction function.
=> update numpy version to 1.7.0

theano/gradient.py, theano/scan_module/scan_op.py
=> Revert "Scan grad speedup"

doc/library/tensor/basic.txt, theano/sandbox/cuda/dnn.py
=> Work around dnn pool infer shape

theano/gradient.py, theano/scan_module/scan_op.py
This is a second take for the PR #3435 which was merged by mistake and then subsequently reverted. It contains the same changes but the commits have been rebased together so they would not already be in the branch history and github would allow this PR.
@abergeron or @lamblin : please review this one instead of #3435
=> Speedup scan grad() method

theano/tensor/basic.py, theano/tensor/tests/test_basic.py
=> Don't be more strict then numpy rtol on float64.

theano/tensor/basic.py, theano/tensor/opt_uncanonicalize.py, theano/tensor/tests/test_basic.py
=> support for multiple axes in MaxAndArgMaxOp

theano/sandbox/tests/test_blocksparse.py
=> Remove a few pieces of unnecessary code in the tests of sparse block dot.

theano/compile/pfunc.py
This is done by in-lining one method in the other one.
=> Convert double recursion to simple recursion

theano/sandbox/cuda/dnn.py
Make them clearer and also correct the inverted x and y coordinates.
Fixes #3503.
=> Fix dnn_conv and dnn_pool docs

theano/tensor/sort.py, theano/tensor/tests/test_sort.py
Implemented grad for argsort op.
=> Grad argsort

theano/compile/debugmode.py, theano/compile/mode.py, theano/compile/tests/test_mode.py, theano/d3viz/tests/test_formatting.py, theano/gof/cc.py, theano/gof/cmodule.py, theano/printing.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py, theano/scan_module/scan_perform_ext.py, theano/tensor/basic.py, theano/tensor/opt.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_elemwise.py, theano/tests/test_printing.py
Also:
- Add debugprint(print_storage=False)
- make the "merge" string optimizer behave like the others.
=> Mixed: warning, error msg, tests fix, clean up, crash

doc/extending/optimization.txt, theano/compile/mode.py, theano/gof/cc.py, theano/gof/opt.py, theano/gof/optdb.py, theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/cudnn_helper.h, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/type.py, theano/tensor/basic.py, theano/tensor/opt.py, theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py, theano/tensor/tests/test_opt.py
This fix gh-3412. It fix the crash and the slow compilation time.
Should also close gh-3501 about the warnings
=> Crash gpu and opt speed up

theano/sandbox/cuda/__init__.py, theano/sandbox/gpuarray/__init__.py, theano/scan_module/scan_opt.py, theano/tests/test_flake8.py
Modify ScanInplaceOptimizer so Scan can be inplace on more of its inputs (instead of copying the contents of said inputs at execution time).
=> Scan inplace opt

theano/tensor/basic.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_opt.py
https://github.com/Theano/Theano/issues/2695
=> TH-2695 Accept symbolic `reps` in `tensor.tile`

theano/tensor/opt.py
This should fix https://github.com/fchollet/keras/issues/866#issuecomment-150024775
This is a forward looking change that try to fix the fondamental issue. We need to add recursion that that fix for a complete fix and need to have other optimization call get_shape instead of using shape_of direction. I let this to a later PR to fix quickly the regression. The full fix will also need optimization speed testing to not have it slow down too much compilation.
=> [ENH,REGRESSION FIX] Fix regression that introduce extra node related to infer shape

.travis.yml, doc/extending/type.txt, doc/library/tensor/basic.txt, theano/configdefaults.py, theano/gof/cc.py, theano/gof/link.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/var.py, theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/type.py, theano/tensor/basic.py, theano/tensor/sharedvar.py, theano/tensor/var.py
Some interface changes to allow for easier use of the multi-gpu and some small bug fixes for unusual circumstances.
=> Multi gpu followup

theano/tensor/opt.py
=> Fix extra scan due to old information in infer shape.

theano/tensor/basic.py, theano/tensor/tests/test_basic.py
=> Fix infer_shape of Join when axis < 0

theano/sandbox/cuda/blas.py, theano/tensor/blas.py
=> Fix unpickling of Gemm and GpuGemm Ops

theano/tensor/nnet/nnet.py
See https://groups.google.com/forum/#!topic/theano-users/33dqPAIQIHE
=> Fix a crash when using Softmax with the CLinker

theano/sandbox/cuda/basic_ops.py, theano/sandbox/gpuarray/basic_ops.py
This was introduced in #3482, and reported in https://groups.google.com/d/topic/theano-users/DFlcQ-992Ss/discussion
=> Fix return value of R_op in HostFromGpu/GpuFromHost

theano/tensor/nnet/abstract_conv2d.py
Fix BaseAbstractConv2d to convert kernel_shape and image_shape to tuples
@lamblin
=> Fix unhashable type if shapes are list

theano/tensor/extra_ops.py, theano/tensor/tests/test_extra_ops.py
https://github.com/Theano/Theano/issues/3025
=> support list of integer form repeats in repeats

theano/gof/fg.py, theano/tensor/var.py
this fix gh-3341
This inline 3 functions inside only 1. This should also speed up compilation time for big graph.
=> [ENH] Lower triple recursion to simple recursion

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> Remove useless reshape

theano/compile/mode.py, theano/gof/fg.py, theano/gof/link.py, theano/gof/op.py, theano/gof/utils.py, theano/tensor/opt.py, theano/tensor/tests/test_opt.py
@lamblin Can you have a look at the comments in some of the tests? For example, I'm not sure how to exclude all opts except for "local_subtensor_make_vector" in the class "test_local_subtensor_make_vector".
=> Continued work on #3018: Stacktrace fix

theano/tensor/signal/conv.py, theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_conv.py, theano/tensor/signal/tests/test_downsample.py
=>  pep8 tensor signal list directory

theano/scan_module/scan_op.py, theano/scan_module/scan_perform.c, theano/scan_module/scan_perform.pyx, theano/scan_module/scan_perform_ext.py
=> Clean up (outs|inps)_on_gpu to (outs|inps)_is_tensor

theano/sandbox/gpuarray/nnet.py
port gh-3163 to the new back-end
=> Port the speedup from #3163 to the new backend.

doc/extending/unittest.txt
=> Fixed error in doc

theano/sandbox/gpuarray/dnn.py, theano/tensor/nnet/abstract_conv2d.py, theano/tensor/nnet/conv.py, theano/tensor/nnet/corr.py
Tackling [this ticket](https://github.com/Theano/Theano/issues/3582).
=> Factoring inference of convolution output shape

theano/tensor/signal/tests/test_downsample.py
The test gives an error while comparing the two shapes.
fix gh-3687
=> Testing the output shape

doc/tutorial/profiling.txt
Hi @abergeron ,
Could you please take a look at the new documentation?
Thanks
=> Doc for the new type of profiling added.

theano/gof/cc.py, theano/gof/tests/test_cc.py
=> Crash cache c scalar

theano/sandbox/gpuarray/opt.py
Fix infer problems with optimizations.
=> Misc fixes

theano/sandbox/gpuarray/dnn_fwd.c, theano/sandbox/gpuarray/dnn_gi.c, theano/sandbox/gpuarray/dnn_gw.c, theano/sandbox/gpuarray/dnn_pool.c, theano/sandbox/gpuarray/dnn_pool_grad.c, theano/sandbox/gpuarray/dnn_softmax.c, theano/sandbox/gpuarray/dnn_softmax_grad.c
Reverts Theano/Theano#3724
This apparently fails to compile, so I'm reverting for the moment until we figure out a fix.
=> Revert "Add proper wait/record pairs for cudnn wrapper."

theano/sandbox/gpuarray/dnn_fwd.c, theano/sandbox/gpuarray/dnn_gi.c, theano/sandbox/gpuarray/dnn_gw.c, theano/sandbox/gpuarray/dnn_pool.c, theano/sandbox/gpuarray/dnn_pool_grad.c, theano/sandbox/gpuarray/dnn_softmax.c, theano/sandbox/gpuarray/dnn_softmax_grad.c
Take 2.
Updated version of #3724 that actually compiles.
I'm not completely sure it is the right thing yet.
=> Add proper wait/record pairs for cudnn wrapper.

theano/sandbox/cuda/dnn.py, theano/tensor/signal/downsample.py, theano/tensor/signal/tests/test_downsample.py, theano/tests/test_flake8.py
I didn't add a test for the bug fix as there is already one failing:
theano/sandbox/cuda/tests/test_blas.py:test_downsample
This test still fail in DebugMode, but due to the fact that DebugMode can't compare cudnn pooling descriptor. I let this to another PR.
fix gh-3578
=> [BUG] Fix DownsampleFactorMaxGradGrad.infer_shape. Fix a failing tests

theano/tensor/basic.py, theano/tensor/tests/test_basic.py
=> Rewrite Reshape.infer_shape

theano/tensor/basic.py
=> adding comment on negation

theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/basic_ops.py, theano/sandbox/cuda/extra_ops.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_basic_ops.py, theano/tensor/basic.py, theano/tensor/nnet/tests/test_sigm.py, theano/tensor/opt.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_opt.py
=> Refactor Flatten

theano/scan_module/scan_op.py, theano/scan_module/scan_opt.py, theano/scan_module/tests/test_scan.py, theano/scan_module/tests/test_scan_opt.py
Don't merge now, but it can be reviewed.
I need to check if there isn't extra scan in the graph. I'm not sure about that.
fix gh-3663
=> Fix BUG IN FGRAPH.REPLACE OR A LISTENER

theano/tensor/blas.py
=> Fix crash with c linker

theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/tests/test_conv.py
=> Fix broadcastable pattern of gradient in abstract conv

theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py, theano/tensor/nnet/__init__.py, theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/conv.py, theano/tensor/nnet/tests/test_conv.py
This should actually finish #3582, and fix #3732.
=> Abstract conv: fix tests and add infer_shape

theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py, theano/sandbox/gpuarray/__init__.py
Otherwise, changing device=gpu to device=cuda disable the convolution.
=> Enable cudnn by default when avaialable in the new back-end

theano/gof/graph.py, theano/tensor/opt.py, theano/typed_list/basic.py, theano/typed_list/tests/test_opt.py
=> Add TypedListConstant, this fix an optimization warning.

doc/library/compile/io.txt, doc/library/config.txt, doc/library/scan.txt, doc/tutorial/adding.txt, doc/tutorial/aliasing.txt, doc/tutorial/conditions.txt, doc/tutorial/debug_faq.txt, doc/tutorial/loop.txt, doc/tutorial/modes.txt, doc/tutorial/sparse.txt, doc/tutorial/symbolic_graphs.txt, doc/tutorial/using_gpu.txt, theano/gof/opt.py, theano/tensor/tests/test_sharedvar.py
* ProfileStats.summary() is fixed for Python 3;
* Python 2/3 compatible examples in tutorial and library reference;
* less deprecation warnings in tests in Python 3
=> Assorted Python 3 fixes

theano/gof/compiledir.py
=> Checks compiledir flag for prohibited characters. Fixes #3711

theano/compile/debugmode.py, theano/sandbox/multinomial.py, theano/sandbox/tests/test_multinomial.py, theano/sandbox/tests/test_rng_mrg.py, theano/scalar/basic.py, theano/tensor/elemwise.py, theano/tensor/nnet/abstract_conv.py, theano/tests/test_flake8.py
This fix a bunch of problem in the daily buildbot in DebugMode. The bug isn't expected in the normal user case and this is only for a new feature that you probably don't use.
=> [BUG] in python code and tests fix

theano/gof/cmodule.py
=> Don't take the lock  unless needed at exit

theano/tensor/nnet/tests/test_abstract_conv.py
=> Added test for get_conv_output_shape method

theano/gof/cc.py, theano/gof/op.py, theano/sandbox/cuda/dnn.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/dnn_base.c, theano/sandbox/gpuarray/nerv.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/tests/test_opt.py
The abstractconv tests should already test for that.
=> Fix the lifter for abstractconv2d.

setup.py
Addressed Issue-3658.
I've built and tested it with http://deeplearning.net/software/theano/library/d3viz/index.html
=> corrected setup of d3viz

theano/tensor/blas.py
Regarding issue #3744 and PR #3654 .
@nouiz , could you please take a look?
=> auxiliary function 'try_blas_flags' added.

theano/gof/cc.py, theano/gof/op.py, theano/sandbox/cuda/dnn.py, theano/sandbox/gpuarray/basic_ops.py, theano/sandbox/gpuarray/dnn_base.c, theano/sandbox/gpuarray/nerv.py
This fixes a segfault when deleting ops that use cudnn in the new backend.
Since it reverts the fix for the context problem I also did an alternate fix for that.
=> Fix segfault

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/tests/test_dnn.py
=> Disable average_exc_pad pooling for cudnn v3

doc/tutorial/examples.txt
I'm proposing a few additional comments in the logistic regression example (affecting theano/tutorial/examples.html ). No code changes.
=> added comments to logistic regression example in the documentation

theano/compile/function_module.py, theano/compile/tests/test_function.py, theano/d3viz/d3viz.py, theano/gof/callcache.py, theano/gof/cmodule.py, theano/gof/compiledir.py, theano/gof/compilelock.py, theano/misc/buildbot_filter.py, theano/misc/check_duplicate_key.py, theano/misc/hooks/check_whitespace.py, theano/misc/hooks/reindent.py, theano/sandbox/cuda/nvcc_compiler.py, theano/scan_module/scan_perform_ext.py, theano/scan_module/tests/test_scan.py, theano/tensor/tests/test_opt.py, theano/tests/run_tests_in_batch.py, theano/tests/test_flake8.py
Hi,
I've create pr for refactoring. @nouiz take a look. #3429 
The 'tests' module is little tricky than rest of pr.
=> Issue  #3429 - refactor some code to python 'with' statement

theano/sandbox/gpuarray/blas.py
fix gh-3878, the user tested it and it was working(after adding the missing import) that I amended in the commit.
=> Fix opt warning/not moving to GPU some node.

theano/compile/pfunc.py, theano/sandbox/gpuarray/tests/test_type.py, theano/sandbox/gpuarray/type.py
Also stop assuming that update_val will have a type in the error message.
=> Fix allow_downcast on gpuarray

theano/tensor/blas.py
Also fix broken default blas fallback.
=> Fix broken blas flags on Anaconda with openblas.

doc/tutorial/extending_theano.txt, theano/compile/ops.py, theano/compile/tests/test_ops.py, theano/gof/op.py, theano/gof/tests/test_op.py
=> Quick python op with gradient

theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/tests/test_dnn.py
=> Add optimizations to transfer new LogSoftmax op to the GPU as CuDNN softmax ops

theano/tensor/nnet/abstract_conv.py, theano/tests/test_rop.py
The implementation is exactly as in Conv2d.
Fixes #3888.
=> R_op for AbstractConv2d

.gitignore, theano/sandbox/gpuarray/tests/test_abstractconv.py, theano/tensor/nnet/opt.py
=> keep stacktrace in abstract_conv optimizations

theano/sandbox/cuda/opt.py
This fixes an ImportError when importing `theano.sandbox.cuda`.
=> Fix path for BatchedDot

theano/scalar/basic_scipy.py, theano/tensor/basic.py, theano/tensor/inplace.py, theano/tensor/tests/test_basic.py
Adding Scipy Bessel function. 
I have a few questions:
1) The PR adds both bessel0 and bessel1. Bessel1 is only added because I don't know how to call 
scipy.special.j1 when calculating the gradietn of bessel0?
2) Is `bessel0` ok for name? Alternatively i can call it `j0` to match scipy?
3) Not sure how tests work. I think i should follow https://github.com/jsalvatier/Theano-1/commit/b18e04323d91c29918341ffdb14501399a6f2acf and add them to ``theano/tensor/tests/test_basic.py
`` but i'm not sure how theano testing works.
=> [WIP] add bessel0

doc/library/compile/mode.txt
=> Fix typo in docs

doc/library/sandbox/cuda/op.txt, theano/sandbox/cuda/blas.py, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_blas.py
=> Renamed BatchedDotOp to GpuBatchedDot

theano/tensor/extra_ops.py, theano/tensor/signal/tests/test_pool.py, theano/tensor/subtensor.py, theano/tensor/tests/test_basic.py, theano/tensor/tests/test_extra_ops.py, theano/tests/test_printing.py
Also remove an old restriction that bincount can't work with uint64
=> Mostly tests fix for 32bit python

.travis.yml, theano/d3viz/d3viz.py, theano/sandbox/cuda/tests/test_blas.py, theano/tests/test_printing.py
=> Fix a test on GPU with mode=FAST_COMPILE

theano/compile/nanguardmode.py
=> Enable opt in NanGuardMode. Make it use the default optimizer.

theano/compile/profiling.py, theano/compile/tests/test_profiling.py
Also code clean up, refactoring and better output of the information.
=> profile_memory, print the expected peak memory usage if excluding inplace opt.

theano/tensor/basic.py, theano/tensor/opt.py
This is a fix to this keras issue: https://github.com/fchollet/keras/issues/1600
Mostly, one example was VERY slow to compile. With this, it get super fast to compile.
=> Faster optimisation

doc/library/config.txt, doc/library/sandbox/cuda/dnn.txt, theano/configdefaults.py, theano/sandbox/cuda/dnn.py, theano/sandbox/gpuarray/dnn.py
This allow to always disable cudnn without corner case where it is partially installed.
fix gh-3962
=> add flag dnn.enabled

theano/__init__.py, theano/compile/__init__.py, theano/compile/pfunc.py
=> Add back Param and make it deprecated

theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py
This fix the failing test in the daily buildbot.
=> Fix test when mode!=DebugMode on the GPU.

.travis.yml, doc/sandbox/ccodegen.txt, doc/scripts/docgen.py, doc/tutorial/extending_theano_c.txt, theano/misc/pkl_utils.py, theano/sparse/basic.py, theano/tensor/nnet/abstract_conv.py, theano/tensor/signal/pool.py
Since travis upped their job length restriction to 2h, we can merge some parts together.  This will save a tiny bit on setup time, but also possibly enable us to test a PR with a single set of jobs that run concurrently.
Here I'm adapting travis.yml by steps to check the timings.
=> Faster travis

theano/tensor/nnet/abstract_conv.py
related to issues #3872 and #3681
=> fixing make_node param passing for conv_grad (conv_transpose)

theano/compile/debugmode.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/sandbox/cuda/var.py
This make DebugMode error print the value instead of <CudaNdarray object at 0x7f229c2f6eb0>
It will help debug the daily buildbot error with DebugMode.
=> Add tp_repr to CudaNdarray. 

doc/dev_start_guide.txt
I am a beginner in the open source world, and so I was not acquainted with the development flow in github. I followed the dev_guide step by step and I was pushing my code to the branch without commiting my changes. So, I am adding these instructions in the code submission section of the tutorial.
=> Added the commit instruction in dev_guide submit text

doc/tutorial/extending_theano.txt, doc/tutorial/extending_theano_c.txt, doc/tutorial/symbolic_graphs.txt
Fix external broken links, as suggested by @nouiz in #3924
=> Replace deleted pages with link to new pages

theano/sandbox/multinomial.py, theano/sandbox/rng_mrg.py, theano/sandbox/tests/test_multinomial_wo_replacement.py, theano/sandbox/tests/test_weighted_select.py
=> Sample multinomial with replacement

theano/compile/debugmode.py, theano/sandbox/cuda/blas.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_opt.py
This fix daily buildbot error in python 3 and a crash during optimization.
=> Fix CudaNdarray repr in python 3 and a crash.

theano/sandbox/cuda/blas.py, theano/tensor/nnet/opt.py
=> Don't use CpuCorrMM when there is no CPU BLAS

theano/tensor/signal/downsample.py, theano/tensor/signal/pool.py, theano/tensor/signal/tests/test_pool.py, theano/tests/test_flake8.py
This should fix the DebugMode errors in the buildbot.
=> Fix the output shape in python to match the C code for DownsampleFactorMaxGradGrad.

.travis.yml, doc/cifarSC2011/advanced_theano.txt, doc/extending/extending_theano.txt, doc/extending/using_params.txt, doc/install_windows.txt, doc/library/scan.txt, doc/tutorial/debug_faq.txt, doc/tutorial/examples.txt, doc/tutorial/loading_and_saving.txt, doc/tutorial/printing_drawing.txt, doc/tutorial/profiling.txt, theano/compile/function.py, theano/misc/pkl_utils.py
Solves test failures in the doc tests. Fix for #3103 .
=> solving doc test failures

doc/extending/op.txt, theano/compile/debugmode.py, theano/gof/cc.py, theano/gof/op.py, theano/sandbox/cuda/basic_ops.py, theano/sandbox/gpuarray/basic_ops.py, theano/tensor/basic.py
Also use this to have AllocEmpty return memory with a fixed value to avoid tripping up checks by accident.
=> Make DebugMode handle a special version of perform.

theano/sandbox/cuda/__init__.py
cnmem usage message was wrong.
=> Fix the cnmem print percent message

theano/tensor/blas.py, theano/tensor/tests/test_blas.py
[theano-users] Optimization failure due to: LocalOptGroup(make_c_ger_destructive,make_c_gemv_destructive) TypeError: ('broadcastable mismatch between y and A', (TensorType(float64, (True,)), TensorType(float64, matrix))) https://groups.google.com/d/topic/theano-users/ybshs7jc8zE/discussion
=> Fix crash with gemv and some broadcast pattern

theano/compile/profiling.py
=> tip for mixed dtypes

doc/library/config.txt, theano/tensor/blas.py
This is needed on Helios cluster.
=> Try blas flags with rpath if they don't work.

doc/library/tensor/index.txt, doc/library/tensor/opt.txt, theano/tensor/opt.py
=> Add doc for opt.py

.travis.yml, theano/compile/debugmode.py, theano/compile/profiling.py, theano/configdefaults.py, theano/sandbox/cuda/__init__.py, theano/sandbox/gpuarray/__init__.py, theano/scan_module/scan_op.py, theano/tensor/blas.py
It seems a few flags were forgotten in #4042.
As a bonus this fixes linking with mkl which apparently never worked before because it require a strange hack.  This might speedup travis.
=> Move leftover flags

theano/gof/cmodule.py, theano/sandbox/cuda/nvcc_compiler.py
=> Remove empty string in the include and lib dir.

theano/sandbox/cuda/tests/test_abstractconv.py, theano/sandbox/gpuarray/tests/test_abstractconv.py, theano/tensor/nnet/__init__.py, theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/corr.py, theano/tensor/nnet/corr_gemm.c, theano/tensor/nnet/tests/test_abstract_conv.py
This also tests the CPU implementations even if there is no GPU.
=> Move the AbstractConv tests with the implementation

theano/sandbox/cuda/tests/test_abstractconv.py, theano/tensor/blas.py
The flake8 thing is just annoying while the other is an error.
=> Fix small buildbot problems

theano/gof/fg.py, theano/scan_module/scan_op.py
Take the good part of gh-3797.
This is mostly small cleanup/update
=> small cleanup, update

theano/sandbox/cuda/tests/test_driver.py
=> Try to detect bug in nvcc.

theano/sandbox/multinomial.py
Addressing #3143. One test is still failing but I made a PR for reference.
=> C implementation of sample without replacement OP

theano/gof/fg.py, theano/gof/toolbox.py
=> Assert to never reintroduce Apply node in fgraph

theano/compile/tests/test_function_name.py, theano/scalar/basic.py, theano/scalar/tests/test_basic.py, theano/scalar/tests/test_div_future.py, theano/scalar/tests/test_div_no_future.py, theano/scan_module/tests/test_scan.py, theano/tensor/xlogx.py
=> extension of #3983

theano/d3viz/tests/test_d3viz.py, theano/d3viz/tests/test_formatting.py, theano/tests/test_flake8.py
#4054 
fixe errors related to flake8  'd3viz/tests/*py'
=> fix flake8 'd3viz/tests/*py'

theano/tensor/blas.py, theano/tensor/nnet/corr.py, theano/tensor/nnet/tests/test_abstract_conv.py
This fix crash in travis. I don't know why the new travis don't link anymore to blas. But this fix a bug in that case.
=> Make BatchedDot don't try to use c code if there is no blas.

.travis.yml
This should hopefully fix the no-blas condition on travis.
fix gh-4187
=> Force older conda version on travis

theano/tensor/blas_c.py, theano/tensor/nnet/tests/test_abstract_conv.py, theano/tensor/tests/test_blas_c.py
=> Fix nan handling in output buffer for CGemv

theano/tensor/blas.py
This addresses the problem raised in #4088 in a clean way.
=> Make the python code for Gemv also check for the need to initialize the output with beta=0

.travis.yml, theano/configparser.py, theano/gof/fg.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/opt.py, theano/sandbox/gpuarray/opt.py, theano/tensor/signal/downsample.py
=> [OPT FAILURE] Fix gh-4131

theano/gof/op.py
Fixes https://github.com/Theano/Theano/issues/4199
=> Impossible to compile a COp

theano/tensor/nnet/conv3d2d.py, theano/tensor/nnet/nnet.py, theano/tensor/nnet/opt.py, theano/tensor/nnet/sigm.py, theano/tensor/nnet/tests/test_conv3d2d.py, theano/tensor/nnet/tests/test_nnet.py, theano/tensor/nnet/tests/test_opt.py, theano/tensor/nnet/tests/test_sigm.py
=> keep stack trace in optimizations of nnet folder

theano/misc/pycuda_init.py, theano/sandbox/cuda/fftconv.py
This PR fixes two failures caused by pycuda/cuda being installed, but GPUs not being available.
=> Fix docgen fails due to GPU not available

theano/configdefaults.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/nvcc_compiler.py, theano/sandbox/gpuarray/dnn.py, theano/sparse/tests/test_opt.py
These include:
- cudnn linking on mac
- sparse test failing on linux.
=> Fix problems for release

theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/tests/test_abstract_conv.py
First commit for issue #3928, bilinear interpolation.
=> Bilinear interpolation

doc/library/config.txt, theano/misc/check_blas.py, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/cuda_ndarray.cu, theano/tensor/nnet/nnet.py
=> Cnmem threashold, comment, don't call dnn_version and optimization registration.

theano/sandbox/cuda/opt.py, theano/sandbox/cuda/tests/test_conv_cuda_ndarray.py, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/cuda/tests/test_type.py, theano/sandbox/gpuarray/tests/test_pickle.py, theano/sandbox/tests/test_multinomial.py, theano/scalar/basic.py, theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/opt.py, theano/tensor/nnet/tests/test_abstract_conv.py
Hopefully these are the last ones.
=> Fix windows test failures

doc/extending/graphstructures.txt, doc/tutorial/debug_faq.txt, doc/tutorial/nan_tutorial.txt, doc/tutorial/profiling.txt
This uses the same branch I already merged to master before, do you have a policy against that?
=> (nit) tutorial typos

theano/d3viz/formatting.py
Caused some confusion: https://github.com/Theano/Theano/issues/1801
=> Clarified graphviz dependency

doc/library/tensor/nnet/nnet.txt
This PR fixes issue #4247 The wordings have been changed to explain softmax better
=> Fixes grammatical errors in theano.nnet.softmax doc

theano/gof/cmodule.py
This should get a test with CLT 7.2 to make sure it still works, but I'm confident it will.
fix gh-4277
=> Fix compilation on mac with CLT 7.3

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
Resolves #4213.
This is a simple first attempt. It fixes the problems I encountered in #3758, but based on your warnings, it will probably break other things. Let's see! (I didn't run the full test suite yet.)
=> Add graph optimization 0/x -> 0

theano/tensor/subtensor.py
It would raise a SystemError wrapping the IndexError already raised.
Fixes #4276.
=> Fix problem with python 3.5.

theano/gradient.py
Add missing R_op for DisconnectedGrad.
=> add R_op for DisconnectedGrad

NEWS.txt, doc/tutorial/faq_tutorial.txt, theano/sandbox/cuda/__init__.py, theano/sandbox/cuda/cuda_ndarray.cu
The assert was triggered by:
[theano-users] Assertion failed! (File: mod.cu, Line 4072)
=> small fix: doc, assert -> python error, printing, code clean up.

theano/scalar/basic.py, theano/scalar/tests/test_basic.py, theano/tensor/tests/test_basic.py
Otherwise, -False is True, and -True is False.
This fixes an existing test in DebugMode.
=> Make sure the input of Neg.impl is not a numpy.bool_

theano/sandbox/gpuarray/basic_ops.py, theano/tensor/tests/test_basic.py
This PR implements the suggestions given in #4262
=> GpuJoin takes negative values for axis

theano/sandbox/cuda/conv.cu
=> conv.cu simple comment fix

theano/tensor/opt.py
Should fix https://github.com/fchollet/keras/issues/2187
=> Add broadcastable dimensions in opt where needed

theano/sandbox/cuda/cuda_ndarray.cu, theano/tensor/opt.py
=> fix gh-4328 This was done for python3, but not python2.

doc/dev_start_guide.txt, doc/extending/extending_theano.txt, doc/extending/unittest.txt, doc/library/tensor/elemwise.txt, doc/library/tensor/index.txt, theano/misc/doubleop.py, theano/tensor/elemwise.py
This PR integrates #4189 and closes issue #4085 .
=> Check RST files in '/theano/doc/' to follow numpy's docstring + Fix elemwise

.travis.yml, doc/install.txt, requirement-rtd.txt, setup.py, theano/configdefaults.py, theano/sandbox/cuda/dnn.py, theano/sandbox/cuda/dnn_base.c, theano/sandbox/cuda/dnn_fwd.c, theano/sandbox/cuda/dnn_gi.c, theano/sandbox/cuda/dnn_gw.c, theano/sandbox/cuda/tests/test_dnn.py, theano/sandbox/gpuarray/conv_desc.c, theano/sandbox/gpuarray/dnn.py, theano/sandbox/gpuarray/dnn_base.c, theano/sandbox/gpuarray/dnn_fwd.c, theano/sandbox/gpuarray/dnn_gi.c, theano/sandbox/gpuarray/dnn_gw.c, theano/sandbox/gpuarray/dnn_pool.c, theano/sandbox/gpuarray/dnn_pool_grad.c, theano/sandbox/gpuarray/tests/test_dnn.py, theano/tests/unittest_tools.py
=> Added cuDNN v5 support & Added optional dependencies to setup.py

theano/compile/sharedvalue.py, theano/misc/pkl_utils.py
Fix problems mentioned in issue #4358
=> Fix PersistentNdarrayLoad problem restoring same object multiple times

theano/gof/opt.py, theano/tensor/nnet/conv3d2d.py, theano/tensor/nnet/nnet.py, theano/tensor/nnet/opt.py, theano/tensor/nnet/sigm.py, theano/tensor/opt.py
=> [WIP] Helper function that check stack traces

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
=> sumsqr2dot added to the opt.py

doc/library/compile/function.txt, theano/compile/function_module.py, theano/gof/tests/test_vm.py, theano/gof/vm.py
An implementation of the partial function evaluation on the VM.
First step to fix #2472.
=> Partial function evaluation

theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/gpuarray/subtensor.py, theano/sandbox/gpuarray/tests/test_elemwise.py, theano/tensor/tests/test_elemwise.py
This gives us a nice speedup since we now perform dimension collapsing and call a contiguous kernel when possible.
Further improvements are possible within the libgpuarray code, but shouldn't require more changes here.
=> Use the new GpuElemwise from libgpuarray

theano/gof/opt.py
=> Update check trace to allow more argument types

theano/sandbox/gpuarray/__init__.py, theano/sandbox/gpuarray/blockgemv.c, theano/sandbox/gpuarray/blockger.c, theano/sandbox/gpuarray/blocksparse.py, theano/sandbox/gpuarray/opt.py, theano/sandbox/gpuarray/tests/test_blocksparse.py, theano/tensor/nnet/tests/test_blocksparse.py
This is a port of blocksparse for the new backend.
=> Blocksparse for gpuarray

theano/tensor/nnet/abstract_conv.py, theano/tensor/nnet/tests/test_abstract_conv.py
Error fix #4303  with batch_size==None and num_input_channels==None during reshaping
=> fix issue 4303 : reshaping part

theano/tensor/opt.py, theano/tensor/tests/test_opt.py
Hi @lamblin ,
Regarding issue #2943, I replaced ```Tile``` op with theano ```tile```. The test seems to fail.
So, where should I change?
=> test using theano tile added

theano/tensor/opt.py, theano/tensor/tests/test_opt.py, theano/tensor/tests/test_var.py, theano/tensor/var.py
Replace some subtensors with DimShuffle, issue #4162
=> Replace some subtensors with DimShuffle first commit

doc/faq.txt, theano/scalar/basic.py, theano/scalar/tests/test_basic.py, theano/tensor/tests/test_opt.py
=> Change the grad of abs to prevent relu from generating nan in fast_compile

doc/install.txt, doc/install_ubuntu.txt, theano/misc/check_blas.py
Just a couple of small doc fixes.
=> Small doc fixes

doc/install.txt, doc/install_ubuntu.txt, doc/library/config.txt, doc/tutorial/conditions.txt, doc/tutorial/debug_faq.txt, theano/configdefaults.py, theano/gof/cc.py, theano/misc/do_nightly_build, theano/scan_module/scan.py
Should help lower the number of compiled files when we change Theano flags.
=> Doc Ubuntu 16.04 and clean up flag in_c_key

theano/compile/debugmode.py, theano/compile/profiling.py, theano/gof/graph.py, theano/gof/vm.py, theano/misc/check_blas.py, theano/printing.py, theano/sandbox/gpuarray/opt.py, theano/scan_module/tests/test_scan.py, theano/tensor/opt.py, theano/tests/test_printing.py
- Make debugprint print the clients information
- doc
- error message
- simplification
=> Small stuff

setup.py, theano/sandbox/cuda/type.py, theano/sandbox/gpuarray/elemwise.py, theano/sandbox/gpuarray/opt.py, theano/tensor/type.py
=> Compatibility between both GPU back-end and doc.
