- .mailmap
- NEWS.txt
- doc/citation.txt
- doc/index.txt
- doc/theano-full.bib
- doc/theano-short.bib
Also update the news, and update author's aliases.
> Add reference to new article

- theano/sandbox/cuda/nvcc_compiler.py
Reported at: https://groups.google.com/d/topic/theano-users/DqlvVjNUK-U/discussion
fix gh-4485
> Fix regression added in 1a3948cc53d2 that cause crashes.

- doc/library/compile/nanguardmode.txt
- doc/tutorial/examples.txt
- theano/sandbox/cuda/opt.py
Small doc and example change at the same time.
> [CRASH,REGRESSION] Fix crash gpufft

- doc/library/config.txt
- theano/compile/function_module.py
- theano/configdefaults.py
- theano/gof/fg.py
- theano/gof/opt.py
- theano/gof/toolbox.py
- theano/gof/utils.py
- theano/gpuarray/__init__.py
- theano/sandbox/cuda/dnn_fwd.c
- theano/sandbox/cuda/dnn_gi.c
- theano/sandbox/cuda/dnn_gw.c
- theano/tensor/basic.py
- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
- theano/tensor/var.py
- Add debug flags
- otherwise add an optimization that remove useless elemwise and have as a side effect to remove the extra scan introduced. So this is a work around some extra scan introduced by https://github.com/Theano/Theano/pull/4356/files#r61901454
> Scan reintroduced benchmark

- theano/sandbox/cuda/nvcc_compiler.py
Support -std=c++11 as flag to nvcc
> Fix for #4514

- theano/gof/fg.py
- theano/gof/opt.py
- theano/scan_module/scan_opt.py
- theano/tensor/opt.py
This depend on PR: https://github.com/Theano/Theano/pull/4463
> Scan reintroduced

- theano/compile/nanguardmode.py
- theano/compile/tests/test_nanguardmode.py
reported at: [theano-users] The latest 0.9.0dev version seems not to support NaNGuard mode for the slice object
> Fix nanguardmode with slices

- theano/gpuarray/opt.py
- theano/tensor/extra_ops.py
- theano/tensor/tests/test_extra_ops.py
without this fix, there is a test failure in the buildbot.
> Finish the regression fix in gh-4533

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
> Speed up GpuDnnSoftmaxGrad by using the best mapping.

- doc/library/config.txt
- theano/configdefaults.py
This also needs to be backported into the release branch 0.8.X.
> Update doc conv flags

- theano/gpuarray/__init__.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/blockgemv.c
- theano/gpuarray/blockger.c
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
- theano/gpuarray/elemwise.py
- theano/gpuarray/extra_ops.py
- theano/gpuarray/gemm16.c
- theano/gpuarray/neighbours.py
- theano/gpuarray/nerv.py
- theano/gpuarray/nnet.py
- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_elemwise.py
- theano/gpuarray/tests/test_extra_ops.py
- theano/gpuarray/tests/test_opt.py
This goes with https://github.com/Theano/libgpuarray/pull/178 and its dependant PRs.
> libgpuarray api changes

- theano/tensor/nlinalg.py
- theano/tensor/tests/test_nlinalg.py
Hello, tensorinv() function from linalg added with corresponding test.
If I should add something there, please tell me.
> TensorInv op added, test for tensorinv added

- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
Don't merge yet, I want to double something first. But it can be reviewed now.
fix gh-4534
> Pool shape

- theano/scan_module/scan_opt.py
- theano/tensor/blas.py
- theano/tensor/tests/test_blas_c.py
Fix daily buildbot tests error in DebugMode.
> Make recent scan opt change deterministic.

- .gitignore
- doc/conf.py
- doc/extending/extending_theano.txt
- doc/install.txt
- doc/install_ubuntu.txt
- doc/install_windows.txt
- doc/library/config.txt
- doc/optimizations.txt
- doc/tutorial/aliasing.txt
- doc/tutorial/using_gpu.txt
- doc/tutorial/using_gpu_solution_1.py
- doc/tutorial/using_multi_gpu.txt
- theano/configdefaults.py
- theano/misc/check_blas.py
- theano/sandbox/gpuarray/__init__.py
Submitting now, but it can be saved for later when the new backend is fully stable.
> Update doc with instructions for using new gpu backend

- theano/gof/link.py
- theano/tensor/subtensor.py
It is to help debug a corner case on Windows found by in pymc3
> Better error message

- theano/gpuarray/opt.py
Using instantiated OPs to reduce the time in instantiating them repeatedly by the optimizations, thus saving some time.
> Pre-instantiating GPUOps

- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/test_basic_ops.py
> Fix GpuToGpu

- doc/tutorial/modes.txt
- theano/compile/nanguardmode.py
- theano/gof/vm.py
This removes the check on inputs that NanGuardMode used to do, but I feel it is not a big loss since you can check your function inputs easily.
> Convert NanGuardMode to use the VM linker instead of WrapLinker.

- README.txt
Made phrasing, layout and grammatical improvements to README.txt to make it more understandable and coherent.
> Proofread README.txt

- theano/gpuarray/__init__.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/gpuarray/type.py
This also removes the use of ElemwiseKernel which is removed by https://github.com/Theano/libgpuarray/pull/179
> Don't rebuild inplace add kernels all the time for GpuIncSubtensor.

- theano/compile/profiling.py
- theano/gof/opt.py
- theano/tensor/tests/test_sort.py
fix https://github.com/Theano/Theano/issues/4610
> Split test to help work around travis timeout. They are super fast here.

- doc/tutorial/nan_tutorial.txt
#4224
@adri-romsor
@lamblin 
@nouiz
> NaN Introduced by AllocEmpty

- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/sigm.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_conv3d2d.py
- theano/tensor/nnet/tests/test_nnet.py
- theano/tensor/nnet/tests/test_opt.py
- theano/tensor/nnet/tests/test_sigm.py
It needs #4290 to be merged first. I will do a rebase once done.
I have only modified the asserts that were already written, I have not added any.
There are several cases I am not sure about, for which I use ops_to_check='all'.
Related ticket: #4114 @lamblin.
> [WIP] Use check_stack_trace helper function in tensor/nnet/tests/

- theano/tensor/basic.py
- theano/tensor/opt.py
This fix the master of travis.
the problem was triggered by gh-4128. But it was already there before. It just that now we don't clean up the problem in fast_compile.
> [FIX TRAVIS] Make the new node on a graph not depend on the old node.

- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
> Add support for no indices in advincsub1 for gpuarrray.

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
> Useless alloc

- doc/library/tensor/basic.txt
- theano/tensor/basic.py
fix gh-4548
@adri-romsor
@lamblin
> ones_like and zeros_like dtype parameter is documented

- doc/library/config.txt
- theano/configdefaults.py
- theano/gpuarray/__init__.py
- theano/gpuarray/opt_util.py
This include a fix for #4622 (the float64 part).
> Single stream flag

- .travis.yml
Also update our version descriptors for python versions officially supported.
> Update the versions tested on travis

- theano/tensor/opt.py
> if broadcastable is the same then no need to op

- doc/extending/extending_theano_gpu.txt
- doc/extending/index.txt
- doc/extending/using_params.txt
- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/test_cgpukernelbase.py
- theano/gpuarray/tests/tstgpueye.c
This explains some of the specifics about making gpu ops and also introduces a class that merges COp and GpuKernelBase if you want to use both.
I've explained all that I could think could be a problem when building new GPU ops, but if you think of something else, add a comment and I'll see what I can do about it.
> Add some documentation on how to write gpu ops.

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
> useless dimshuffle in reshape is removed

- doc/.static/version_switch.js
- doc/.templates/layout.html
@fvisin and @lamblin, this should correct the issues with the RTD version switcher.
> Rtd theme correct

- theano/tensor/subtensor.py
- theano/tensor/tests/test_subtensor.py
This fixes the error reported at https://github.com/Theano/Theano/issues/4636#issuecomment-229689775, and maybe other open issues that I could not find.
> Fix inc/set_subtensor when indexing with one non-vector

- theano/gpuarray/tests/test_abstractconv.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/tests/test_abstract_conv.py
Fixes the error reported in #4680. And, a small optimization
fix gh-4680
> Fixed few errors generated from Dilation PR

- theano/gpuarray/elemwise.py
Made this [suggestion](https://groups.google.com/forum/#!topic/theano-dev/CyudghMklcE)
> Speeding up local_gpua_careduce

- theano/sandbox/cuda/__init__.py
> Use nvcc flags to compile with cuDNN

- doc/dev_start_guide.txt
- theano/d3viz/formatting.py
- theano/gpuarray/dnn.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/opt.py
- theano/printing.py
- theano/tensor/elemwise.py
- theano/tensor/nlinalg.py
> Small mixed changes.

- theano/gpuarray/multinomial.py
- theano/gpuarray/tests/test_multinomial.py
This is the finishing touches of #4639
> Multinomial Without Replacement

- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_batchnorm.c
- theano/gpuarray/dnn_batchnorm_base.c
- theano/gpuarray/dnn_batchnorm_grad.c
- theano/gpuarray/dnn_batchnorm_inf.c
- theano/gpuarray/tests/test_dnn.py
This ports the cuDNN batch normalization code to the gpuarray backend.
Note that in order for the tests to pass you will need https://github.com/Theano/libgpuarray/pull/226
> GpuArray BatchNorm

- theano/compile/function_module.py
- theano/gof/lazylinker_c.c
- theano/gof/lazylinker_c.py
- theano/gof/tests/test_vm.py
- theano/gof/vm.py
I started to implement partial evaluation in CVM. I didn't do the `output_keys` yet, just the partial evaluation when the `output_subset` is a list of indices.
Could you take a look?
Tries to fix #4624.
> Partial evaluation in CVM

- theano/gpuarray/subtensor.py
This will fix the problem about not having an exception set, but the fix for the root cause is in https://github.com/Theano/libgpuarray/pull/233
> Fix handling of errors in the Set case of GpuIncSubtensor.

- doc/library/config.txt
- theano/configdefaults.py
- theano/gpuarray/__init__.py
> Add the theano flags gpuarray.sched

- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
Method DownsampleFactorMaxGradGrad.grad and method test_DownsampleFactorMaxGradGrad_grad have been added respectively to pool.py and tests/test_pool.py.
> Addition of DownsampleFactorMaxGradGrad.grad and its test

- theano/gpuarray/tests/test_fft.py
Recreated to remove tests from git history
> make gpuarray/test_fft compatible with numpy<1.10

- theano/gpuarray/tests/test_subtensor.py
- theano/gradient.py
- theano/sandbox/cuda/tests/test_basic_ops.py
- theano/sandbox/cuda/tests/test_tensor_op.py
- theano/tensor/nnet/tests/test_conv3d2d.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_subtensor.py
These should fix the existing issues on Jenkins.
> Fix jenkins

- theano/compile/nanguardmode.py
> Ignore more frequently the mrg rng state in the old back-end. 

- theano/tensor/basic.py
- theano/tensor/opt.py
- theano/tensor/tests/test_basic.py
> add ddof to var and std, apply Fred-fix to opt

- theano/gpuarray/opt.py
- theano/tensor/basic.py
This pull request solves all the original issues in  https://github.com/Theano/Theano/pull/4777#discussion_r72066004. This one is correctly rebased, so the history should not be messy.
close gh-4601
> ccw4601 remove name from reshape op

- theano/sandbox/cuda/opt.py
> Lift more assert

- theano/compile/profiling.py
- theano/gof/opt.py
> Fix opt profile crash

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Adressing Issue #4825, our change is simply that if a client in the op has an Alloc, it will not apply local_useless_alloc
> Issue 4825

- theano/tensor/nlinalg.py
- theano/tensor/tests/test_nlinalg.py
It works. I have only one question: I copy-pasted tensorsolve docstring from numpy. Is it okay to do that?
> Add tensorsolve to theano.tensor.nlinalg. Test.

- doc/library/tensor/basic.txt
- theano/tensor/basic.py
- theano/tensor/extra_ops.py
- theano/tensor/opt.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_opt.py
- theano/tensor/tests/test_subtensor.py
- theano/tensor/var.py
> Raising error for Indexing subtensor with a Boolean mask

- doc/developer/scan.txt
Finish PR #4015 
@nouiz I addressed the comments of @mgermain on @carriepl 's PR.
Just one small detail: what is the correct syntax : Scan Op / scan op /Scan op ?
Otherwise I think the text is quite clear, although I havn't looked into the code of the internals of scan yet.
> [WIP] Scan doc internal

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
resolved issue #4625, which adds issue and PR template to Theano
> Adding issue and PR template to Theano repo

- theano/gpuarray/type.py
You can make a pull request to Theano github repo in order to fix a bug or add new features.
Once a pull request is submitted, [Travis](https://travis-ci.org/) is launched to verify the pull request
given the current stack of unit-tests in Theano.
_name_for_ctx do not iter for loop enough
raise identation error fixed
> _name_for_ctx do not iter for loop enough

- doc/index.txt
http://www.mila.umontreal.ca/Home/courses moved.
> Changed courses URL

- .jenkins/jenkins_pretest.sh
> add xunit to jenkins pretest

- doc/extending/extending_theano.txt
- theano/gof/op.py
- theano/gof/utils.py
This will remove problems with inheriting __eq__ or __hash__ that shadows our own.
> Add a metaclass implementation of __props__ and generalize it to all theano objects

- theano/gof/opt.py
by '[theano-dev] Recent Theano changes break my Op with multiple outputs'
> Fix error reported

- theano/gof/optdb.py
- theano/sandbox/cuda/opt.py
Better fix then:
https://github.com/Theano/Theano/pull/4979
> Fix optimization order and jenkins

- theano/compile/debugmode.py
- theano/compile/nanguardmode.py
- theano/gof/type.py
This requires #4924 so that the tests will pass.
> Drop support for python 2.6 in CDataType

- .travis.yml
- theano/tensor/tests/test_gc.py
You can make a pull request to Theano github repo in order to fix a bug or add new features.
Once a pull request is submitted, [Travis](https://travis-ci.org/) is launched to verify the pull request
given the current stack of unit-tests in Theano.
> Better error message to help debug travis problem

- PULL_REQUEST_TEMPLATE.md
> The contributing message is annoying.

- theano/configparser.py
> Fix Theano deprecation warning

- theano/gpuarray/multinomial.py
- theano/gpuarray/tests/test_multinomial.py
Allowing GPUArray multinomial op to handle more dtypes. Fixes #4455
> Gpu multinomial more dtypes

- theano/tensor/opt_uncanonicalize.py
- theano/tensor/tests/test_opt_uncanonicalize.py
First attempt to fix the first point of the issue: dropping the dimshuffle of the Alloc if the dimshuffle only adds dimension to the left. This need review since I am still unfamiliar on how to play around with these classes!
gh-4647
> [WIP] Opt Alloc(DimShuffle(...)...) -> Alloc(...) #4647

- theano/gpuarray/dnn.py
More algo are available.
I did the update only in the new back-end.
This should fix crash related to "[theano-users] Error using floatX = float16 to save memory"
> Update 3d conv algo avail in cudnn v5

- theano/compile/nanguardmode.py
- theano/compile/ops.py
- theano/configdefaults.py
- theano/gpuarray/__init__.py
- theano/gpuarray/dnn.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/nnet.py
- theano/gpuarray/tests/test_dnn.py
- theano/gradient.py
- theano/scalar/basic.py
- theano/tensor/basic.py
- theano/tensor/nnet/sigm.py
- theano/tensor/opt.py
> Collection of fixes to make the DLT work in float16

- theano/tensor/basic.py
> Change numpy.any to numpy.all in check_equal_numpy

- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
The dev20 version doesn't but that's accessory.
> GpuAdvancedIncSubtensor1 supports mixed dtypes.

- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
@lamblin, I checked on my machine that the new test fails with master and all tests in test_dnn.py pass with fix.
fix gh-5056
> fix softmaxgrad dnn opt error fixes #5056

- doc/library/tensor/signal/pool.txt
- theano/gpuarray/dnn.py
- theano/gpuarray/opt_util.py
- theano/gpuarray/tests/config.py
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/opt.py
- theano/sandbox/cuda/opt_util.py
- theano/sandbox/cuda/tests/test_blas.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
This would add a 3D CPU implementation for `theano.tensor.signal.Pool` and its gradients, which can then be optimised with a GPU implementation.
(Actually, it turns the Pool op into a more generic Nd pooling operation, which may or may not be a good idea.)
See also issue #4731.
> theano.tensor.signal.Pool with 3D support

- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
> Regression FIX

- theano/tensor/signal/pool.py
- theano/tensor/signal/tests/test_pool.py
To be able to merge faster gh-5090 (a regression fix), I let the code clean up in this PR.
> Finish code clean up from the regression fix

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> Fix maxargmax zero shape

- doc/extending/extending_theano.txt
- doc/extending/op.txt
- doc/tutorial/gpu_data_convert.txt
- doc/tutorial/using_gpu.txt
- theano/compile/builders.py
- theano/compile/debugmode.py
- theano/d3viz/formatting.py
- theano/gof/cc.py
- theano/gof/link.py
- theano/gof/op.py
- theano/gof/tests/test_lazy.py
- theano/gof/vm.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/fft.py
- theano/ifelse.py
- theano/misc/pycuda_example.py
- theano/sandbox/cuda/__init__.py
- theano/sandbox/cuda/blas.py
- theano/sandbox/cuda/cula.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/extra_ops.py
- theano/sandbox/cuda/fftconv.py
- theano/scalar/basic.py
- theano/scan_module/scan_op.py
- theano/sparse/basic.py
- theano/tensor/blas.py
- theano/tensor/blas_scipy.py
- theano/tensor/elemwise.py
- theano/tensor/opt.py
- theano/tensor/signal/pool.py
continue https://github.com/Theano/Theano/pull/4959
fix gh-4317
>  Removing _op_use_c_code attribute

- theano/gof/fg.py
This cause problems: https://github.com/Theano/Theano/issues/5107
This is not the full fix, but a revert while waiting for a full fix.
> Manual revert of 29e67107e0558ec979be1834df47bf50fb948284

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
> Log sum exp optimization for numerical stability

- theano/tensor/nnet/nnet.py
@mgermain @bouthilx 
I have generated the doc and it looks nice.
> Improve docstring of h_softmax and add basic example

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> make var() return float16 when input is float16.

- theano/gpuarray/tests/test_dnn.py
~~Tests with float16 are successful.~~
> use floatX in gpuarray dnn tests

- theano/compile/function_module.py
- theano/tensor/elemwise.py
- theano/tensor/type.py
> [ENH] fix opt error/skip and better error printing.

- theano/gpuarray/blas.py
- theano/gpuarray/opt.py
- theano/gpuarray/pool_grad_grad.c
- theano/gpuarray/tests/test_blas.py
Adds support for gpuarray pool grad grad. Currently, does not support padding and similar to cuda pool grad grad.
I placed implementation in `blas.py` which is similar to cuda backend.
> Gpuarray pool grad grad

- theano/gpuarray/elemwise.py
- theano/gpuarray/tests/test_elemwise.py
- theano/scalar/basic.py
- theano/scalar/tests/test_basic.py
> [REG, CRASH] fix crash related to float16 introduced in gh-5077

- benchmark/autoencoder/aa.py
- benchmark/autoencoder/aa_numpy.py
- benchmark/convolution/conv2d.py
- benchmark/convolution/opencv.py
- benchmark/regression/regression.py
Changed imports of numpy to one common form of `import numpy as np` in code (only) in `Theano/benchmark/*` files
> Import numpy

- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
ticket 2801, first commit, more test to be done.https://github.com/Theano/Theano/issues/2801
> #2801:subtensor-incsubtensor

- theano/tensor/elemwise.py
- theano/tensor/tests/test_elemwise.py
Fixes #5171 and https://github.com/pymc-devs/pymc3/issues/1496
> Fix grad of elemwise with boolean inputs.

- theano/tensor/nnet/nnet.py
> Fix h_softmax example data types

- theano/sparse/basic.py
- theano/sparse/opt.py
- theano/sparse/sandbox/sp.py
- theano/sparse/sandbox/sp2.py
- theano/sparse/sandbox/test_sp.py
- theano/sparse/sandbox/truedot.py
- theano/sparse/tests/test_basic.py
- theano/sparse/tests/test_opt.py
- theano/sparse/tests/test_sp2.py
- theano/sparse/tests/test_utils.py
- theano/sparse/type.py
Changed imports of numpy to one common form of `import numpy as np` in `Theano/tensor/sparse/*` files
> Numpy imports

- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
> Added checks for taps values.

- doc/install.txt
Added small section on AWS Marketplace AMI for Theano by Bitfusion. This was okayed by nouiz a couple months ago in the google group: https://groups.google.com/forum/#!searchin/theano-users/AMI%7Csort:relevance/theano-users/bZczMYoqdFU/gXEdvohhBAAJ
> AWS Marketplace AMI install doc section

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
noticed that max_and_argmax fails, test + fix, see this [travis message](https://travis-ci.org/pymc-devs/pymc3/jobs/175961733#L1020)
> noticed that max_and_argmax fails, test + fix

- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_nnet.py
> Fix the optim to replace the gradient of log softmax (true_div problem)

- theano/tensor/opt.py
- theano/tensor/tests/test_subtensor.py
The replacement was not correct when there were explicitly broadcastable
dimensions, or if the dtype changed.
This issue was introduced in #4355, and was detected by a test in DebugMode.
I will try to add explicit tests for these corner cases.
> Fix issue in local_subtensor_incsubtensor

- .travis.yml
theano/tensor tests are splitted into:
- all theano/tensor tests excluding test_basic
- just test_basic
`mode=FAST_COMPILE` tests are splitted into:
- all tests excluding theano/tensor tests
- just theano/tensor tests
@nouiz
> Update TRAVIS config: tests splitted

- theano/tensor/subtensor.py
- theano/tensor/tests/test_subtensor.py
This pull request fixes subtensor.take
fix gh-5112
@lamblin
> fixing subtensor.take

- theano/scalar/basic.py
> Add c code for conj except for complex

- theano/tensor/tests/test_opt.py
- theano/tensor/tests/test_subtensor.py
- theano/tests/test_flake8.py
> Add tests for local_subtensor_inc_subtensor

- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
Does part of https://github.com/Theano/Theano/issues/4159
> Make mrg_uniform_base to be broadcastable

- theano/scan_module/tests/test_scan.py
- theano/tensor/tests/test_elemwise.py
This fix one test in jenkins and add information to help fix another one later.
> Fix one test in debugmode

- theano/tensor/elemwise.py
This is a code clean up, but probably also fi gh-5273. Sadly, I wasn't able to make a test to make sure I fix it. So having the original code that produce this would help add this test.
> Clean up and maybe fix gh-5273. No test for the fix to issue.

- doc/LICENSE.txt
- theano/gof/tests/test_utils.py
- theano/gof/utils.py
- theano/misc/frozendict.py
- theano/misc/pycuda_example.py
- theano/scalar/basic.py
- theano/tensor/elemwise.py
- theano/tensor/tests/test_opt.py
This PR is the first part of #5071 alone
> New frozen dict

- theano/configdefaults.py
- theano/gpuarray/tests/test_opt.py
- theano/ifelse.py
- theano/tensor/tests/test_elemwise.py
- the blas is a crash fix
- the ifelse in the new back-end is a bug fix
- add a test for gh-5277 too
> Fix blas detection in corner case

- theano/scan_module/scan.py
- theano/scan_module/scan_checkpoints.py
- theano/scan_module/tests/test_scan_checkpoints.py
Fixes #5106
I made the changes to remove the limitation that the length of the sequence has to be a multiple of `save_every_N`. It still requires proper testing, and also I still need to check the behavior when the user pases `n_steps`.
> Removed save_every_N sequence size limitiation.

- theano/tensor/subtensor.py
- theano/tensor/tests/test_subtensor.py
> Fix in advanced_inc_subtensor1 if index is broadcastable

- theano/gpuarray/blas.py
- theano/gpuarray/tests/test_blas.py
The output is now initialized to zeros. 
fix gh-3217
> Uninitialized memory returned from empty GpuGemv dot-product

- theano/sandbox/tests/test_rng_mrg.py
https://github.com/Theano/Theano/issues/4159
> broadcastable test for binomial, multinomial and normal

- theano/gof/destroyhandler.py
- theano/gof/tests/test_destroyhandler.py
In PR #5190 I have been having problems with the order in which multiple optimizations run. In some cases, this might incorrectly optimize an Op into an inplace version, even if that that shouldn't be allowed because it destroys variables that are still needed.
I must admit that I'm not entirely sure if this is the correct solution, but this patch seemed to fix my problem. The DestroyHandler is looping through the destroyers and destroyed input to create a dictionary `rval`. It seems to assume that `rval[app]` will always be empty, so it just sets the value. This usually works fine, except in a few rare cases where `rval[app]` already contains a list of nodes. Because the code overwrites `rval[app]`, it will forget about the nodes that were already there. In just the right circumstances, …
> DestroyHandler should not overwrite existing rval[app] values

- theano/gof/cmodule.py
- theano/gof/op.py
- theano/gof/type.py
- theano/sandbox/cuda/dnn.py
- theano/scalar/basic.py
We need to find a better fix then the last commit.
> Fix reload pickle

- theano/gpuarray/fft.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
This PR tries to unify the interface for Diagonal and ExtractDiag.
> Moving ExtractDiag op to the new backend

- theano/gpuarray/__init__.py
We will now use the soversion like for everything else.
> Remove the custom version check in the __init__ of pygpu.

- .jenkins/jenkins_buildbot_nogpp.sh
- .jenkins/jenkins_buildbot_release_extra.sh
> Jenkins release scripts

- theano/gof/utils.py
rebased version of https://github.com/Theano/Theano/pull/5294
> close file with context manager

- theano/scalar/basic.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
Fix gh-5280. 
This should fix a compilation with newer glibc.
> Remove isnan from the graph for discrete dtype.

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
If the conditions of an `Assert` are constant and True, `get_scalar_constant_value` could return the value if it it also constant.
> Try to get_scalar_constant_value for Assert nodes

- theano/tensor/basic.py
- theano/tensor/opt_uncanonicalize.py
> Fix opt crash

- doc/tutorial/shape_info.txt
- theano/scan_module/scan_checkpoints.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
Hi @nouiz ,
Regarding issue #5253,  I changed the perform function to output a view of input in the case of only one non-empty input. How can we test if it is working correctly? The graph seems not to change as expected.
> Make join work inplace

- theano/gpuarray/dnn.py
- theano/sandbox/cuda/dnn.py
This should fix #5003.
I'll also add some tests.
> [WIP] Use __call__ instead of make_node to avoid bypassing test values

- theano/scan_module/scan_op.py
> Use a default value compatible with broadcastable of type

- .travis.yml
Otherwise, it is just using the cached one...
> Force install of the new commit of Theano

- theano/gpuarray/tests/test_extra_ops.py
Problem introduced in gh-5317.
> Fix test that we don't move 4d tensor to the GPU

- .jenkins/jenkins_test2.sh
- theano/gpuarray/__init__.py
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_base.c
- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
- theano/gpuarray/dnn_pool.c
- theano/gpuarray/dnn_pool_grad.c
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/type.py
New PR rebased of gh-5305 to try to get travis passing.
> Select the dnn convolution algorithm using actually available memory

- theano/gof/type.py
> Mixed fixes

- theano/gpuarray/tests/test_dnn.py
A test to keep if the issue in #5373 from coming back.
> Add regression test for nvcc.compiler_bindir (#5373)

- theano/scalar/basic.py
- theano/scalar/basic_scipy.py
- theano/tensor/nnet/tests/test_sigm.py
- theano/tensor/tests/test_basic.py
Hi @nouiz ,
I added binary tests in ```_good_broadcast_binary_normal``` for uint16. The tests seem to be fine. Is there any other place that I need to add uint?
Thanks
fix gh-850
> uint16 added into _good_broadcast_binary_normal

- theano/gradient.py
> Complete Add grad_scale Op

- theano/gpuarray/multinomial.py
- theano/sandbox/multinomial.py
fix memory leak and speed up when there is few multinomials as in gh-5338.
> [ENH] Multinomial without replacement

- theano/scan_module/scan_perform.pyx
Fixed a typo of value error comment. Fixes issue #5414
> Typo-Fix of value error comment

- theano/gpuarray/pool.py
fix #5409, This is for fixing a typo that prevents T.grad on gpuarray.pool
> as per #5409,  fixing a typo

- setup.py
- theano/gpuarray/__init__.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/extra_ops.py
- theano/gpuarray/gemm16.c
- theano/gpuarray/multinomial.py
- theano/gpuarray/neighbours.py
- theano/gpuarray/nnet.py
- theano/gpuarray/subtensor.py
As per https://github.com/Theano/libgpuarray/issues/248 and https://github.com/Theano/libgpuarray/pull/325.
> Switch gs and ls to follow libgpuarray.

- theano/gof/opt.py
Regarding issue #5125 , I removed the ```pruner``` function, and instead we are now only checking if the node exists in the ```fgraph.apply_nodes``` dictionary.
> removed pruner function of EquilibriumOptimizer class

- theano/tensor/elemwise.py
grad() functions were changed to L_op wherever outputs were recreated. Fixes #5426
> Changed grad() to L_op in given ops

- doc/library/config.txt
- theano/configdefaults.py
- theano/tensor/basic.py
- theano/tensor/var.py
> Change default of round() to be as NumPy and warn about it.

- .mailmap
- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/LICENSE.txt
- doc/conf.py
- doc/index.txt
- doc/internal/how_to_release.txt
- doc/introduction.txt
- setup.py
This is a PR to prepare release 0.9.0beta1. It will be updated to match theano/master branch updates until we release.
What do you think ? @nouiz @lamblin
> Pull Request for release 0.9.0beta1

- theano/tensor/tests/test_basic.py
uint8 can't store the value of gamme for input greater then 6.
> Fix jenkins in 32bit

- .travis.yml
- doc/conf.py
- doc/library/tensor/basic.txt
- setup.cfg
- theano/configdefaults.py
- theano/d3viz/formatting.py
- theano/gradient.py
- theano/printing.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/gpuarray/dnn.py
- theano/tensor/extra_ops.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_bn.py
- theano/tensor/nnet/tests/test_corr.py
- theano/tensor/var.py
- theano/tests/test_flake8.py
> Backport of support for pydot-ng in 0.8.x

- doc/internal/how_to_release.txt
fix #4999 and other typos.
@nouiz @lamblin
> Update internal documentation about "How to make a release".

- theano/compile/function_module.py
- theano/compile/tests/test_function_module.py
Fixes https://github.com/Theano/Theano/issues/2762
> Fix bug caused when setting default value in Param in interactive mode

- theano/compile/function_module.py
- theano/compile/pfunc.py
- theano/compile/profiling.py
- theano/configdefaults.py
- theano/gof/vm.py
> Print profile stats

- theano/compile/builders.py
- theano/compile/debugmode.py
- theano/compile/function.py
- theano/compile/function_module.py
- theano/compile/monitormode.py
- theano/compile/ops.py
- theano/compile/profiling.py
- theano/compile/sharedvalue.py
- theano/compile/tests/test_builders.py
- theano/compile/tests/test_debugmode.py
- theano/compile/tests/test_function.py
- theano/compile/tests/test_function_module.py
- theano/compile/tests/test_misc.py
- theano/compile/tests/test_monitormode.py
- theano/compile/tests/test_nanguardmode.py
- theano/compile/tests/test_ops.py
- theano/compile/tests/test_pfunc.py
- theano/compile/tests/test_profiling.py
- theano/compile/tests/test_shared.py
#4218 
all files in the directory theano/compile have been changed
> import numpy (theano/compile)

- theano/misc/check_blas.py
- theano/misc/check_multi_gpu.py
- theano/misc/latence_gpu_transfert.py
- theano/misc/may_share_memory.py
- theano/misc/pkl_utils.py
- theano/misc/pycuda_example.py
- theano/misc/safe_asarray.py
- theano/misc/tests/test_cudamat_utils.py
- theano/misc/tests/test_gnumpy_utils.py
- theano/misc/tests/test_may_share_memory.py
- theano/misc/tests/test_pkl_utils.py
- theano/misc/tests/test_pycuda_example.py
- theano/misc/tests/test_pycuda_theano_simple.py
- theano/misc/tests/test_pycuda_utils.py
> Import numpy (theano/misc)

- theano/tensor/tests/test_var.py
- theano/tensor/var.py
closes https://github.com/Theano/Theano/issues/5374
> Implement indexing with empty list

- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
> GpuArray_take1 requires contiguous inputs.

- theano/gof/cc.py
- theano/gof/cmodule.py
- theano/gof/compiledir.py
- theano/gof/graph.py
- theano/gof/link.py
- theano/gof/op.py
- theano/gof/opt.py
- theano/gof/tests/test_cc.py
- theano/gof/tests/test_cmodule.py
- theano/gof/tests/test_compute_test_value.py
- theano/gof/tests/test_graph.py
- theano/gof/tests/test_graph_opt_caching.py
- theano/gof/tests/test_lazy.py
- theano/gof/tests/test_link.py
- theano/gof/tests/test_op.py
- theano/gof/tests/test_types.py
- theano/gof/tests/test_vm.py
- theano/gof/utils.py
#4218
all files in the directory theano/gof have been changed
> Import numpy gof

- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/config.py
- theano/gpuarray/tests/test_dnn.py
- theano/sandbox/cuda/dnn.py
- theano/sandbox/cuda/tests/test_dnn.py
- theano/scalar/basic.py
- theano/tensor/nnet/bn.py
- theano/tensor/nnet/tests/test_bn.py
- theano/tensor/type.py
I merged https://github.com/Theano/Theano/pull/5190 too fast. Here are some updates for corner cases.
I still need to locally make sure all tests pass and that it don't make the tests too long (also in DebugMode) before merging this PR.
The master isn't in a bad state. Just that corner case won't be as optimized as they should and some tests crash when floatX=float64.
> Follow up from abstract bn PR

- theano/gof/cmodule.py
Addresses and fixes #5491. The issue was introduced in this [commit](https://github.com/Theano/Theano/commit/316f10443fbad9cd2185f6be64e5cb3dad275910).
> Fixing numpy imports

- theano/gpuarray/type.py
- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
can be done without additional memory usage.
fix gh-https://github.com/Theano/Theano/issues/5449
> Add inplace filtering for GpuArrayType so that shared value replacement

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
Adresses #5224 and fix #5384
I added an error message (it is still unclear for the moment), and a small test with the failure case.
> Added broadcast check in scan.

- theano/sandbox/cuda/__init__.py
It was asked on the mailing if we remove it for 0.9 or the next one.
> clarify error message.

- theano/gpuarray/opt.py
- theano/scan_module/scan_op.py
> Fix gpu integers in scan.

- theano/gpuarray/basic_ops.py
- theano/sandbox/cuda/basic_ops.py
- theano/tensor/basic.py
(C code only for CPU currently, C code for GPU to come later)
Method: for each split, an adapted view is created and then copied into an output.
To come up:
* Add C code for GPU.
* Check if `self.len_splits` can be defined as a param op.
@nouiz @lamblin 
close https://github.com/Theano/Theano/pull/5499
> Add C code for CPU and GPU for tensor.Split op.

- theano/tensor/tests/test_basic.py
Fixes #5498.
Thanks @rebecca-palmer and @jrtc27 for the fix.
> Fix test for Python 3 on 32-bit

- doc/library/scan.txt
Finishes  #4942
I addressed @nouiz's comment and added the error message in the doc.
> Improve the example for strict=True in the scan() doc part 2.

- theano/gpuarray/multinomial.py
- theano/gpuarray/tests/test_multinomial.py
This is to fix one issue in #4455, output should support float16 and input should support float16 and float64
> multiple data type support for GPUMultinomialFromUniform output

- theano/gof/op.py
fix https://github.com/Theano/Theano/issues/5540
> Convert dos end of line to unix version

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
op_lifer expect that. fix gh-5589
> [CRASH] Fix local_gpua_advanced_incsubtensor to return variable on the GPU

- theano/compile/nanguardmode.py
- theano/compile/tests/test_nanguardmode.py
finish https://github.com/Theano/Theano/pull/4780
>  Fix NaNGuardMode to permit None variables

- theano/compile/profiling.py
- theano/tests/test_flake8.py
> Print scan profile again

- theano/sandbox/cuda/cuda_ndarray.cu
merging updates back to master
> Updates to solve potential problems with compiler-specific casting

- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
> Fix dnn conv grad issues

- theano/gpuarray/blas.py
> Remove warning by warn_float64 when we want the upcast to float64.

- .mailmap
- NEWS.txt
- NEWS_DEV.txt
- doc/conf.py
- doc/index.txt
- doc/introduction.txt
- setup.py
> Prepare release 0.9.0rc2

- theano/gpuarray/elemwise.py
- theano/gpuarray/extra_ops.py
- theano/gpuarray/kernel_codegen.py
- theano/gpuarray/subtensor.py
This also lift the dependency on warpSize == 32.
> Remove warp-synchronous programming.

- doc/library/config.txt
- theano/configdefaults.py
- theano/gof/opt.py
- theano/gpuarray/basic_ops.py
- theano/scan_module/scan_utils.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/opt.py
I think we should include this in our rc3
> [ENH] for rc3, Graph clean up, faster compilation, conv.assert_shape Theano flags, add unsafe in useless opt

- theano/gpuarray/dnn.py
Fix gh-5649. Replace https://github.com/Theano/Theano/pull/5569
> Fix precision in cudnn

- theano/tensor/nnet/nnet.py
> Warn if taking softmax over broadcastable dimension

- .jenkins/jenkins_test2.sh
- theano/compile/profiling.py
- theano/compile/tests/test_profiling.py
- theano/gof/op.py
- theano/gof/vm.py
- theano/gpuarray/tests/test_dnn.py
- theano/printing.py
- theano/scan_module/tests/test_scan_checkpoints.py
- theano/tests/test_printing.py
Those were failing when executing `theano-nose` with Python 3.5.2, numpy 1.12, a GTX 580 (without cuDNN) and the new back-end, without separating CPU vs GPU tests in different processes.
> A couple of test fixes

- theano/gpuarray/subtensor.py
- theano/tensor/tests/test_subtensor.py
> Fix error in Advanced indexing with > 2D

- theano/gpuarray/elemwise.py
I removed a useless `printf('slow')`
> Removed useless printf.

- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
> Fix offset in GpuIncSubtensor

- theano/compile/debugmode.py
part of https://github.com/Theano/Theano/pull/5687/ that is sure to be ok to merge for rc4.
> Make DebugMode keep memory layout when possible.

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_subtensor.py
- theano/tests/unittest_tools.py
Should we back-port 3c0b51f to 0.9?
> Various small fixes.

- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
The counterpart of #5247, proposed in #1221
> Diag --> AllocDiag

- theano/scalar/basic.py
- theano/scalar/basic_scipy.py
- theano/tensor/elemwise.py
- theano/tensor/nnet/nnet.py
- theano/tensor/signal/pool.py
Related to https://github.com/Theano/Theano/issues/5426
> Change grad to L_op 

- theano/tensor/nnet/tests/test_abstract_conv.py
I get the following missing input errors, but @lamblin the code worked for you?
======================================================================                                                                                                                                                                                    
ERROR: Compares calculated abstract grads wrt inputs with the fwd grads                                                                                                                                                                                   
---------------------------------------------------------------------- …
> Test abstract conv

- theano/gof/fg.py
- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
> Added meaningful message when missing inputs to scan.

- theano/compile/profiling.py
- theano/gpuarray/basic_ops.py
- theano/sandbox/cuda/basic_ops.py
- theano/scan_module/scan_op.py
The first step is to port GPU profilemode to profiling.py and new back-end
will fix gh-5055 when finished
> 5055:Port ProfileMode GPU to new back-end and profiling.py

- doc/install_ubuntu.txt
- doc/library/config.txt
- theano/compile/function_module.py
- theano/configdefaults.py
- theano/gpuarray/dnn.py
- theano/sandbox/cuda/__init__.py
To help speed the import, in particular when multiple process start at the same time.
> dnn.enabled=no_check

- theano/gof/cmodule.py
fix https://github.com/Theano/Theano/issues/1680
> Ccw c message

- doc/tutorial/shape_info.txt
- theano/compile/tests/test_profiling.py
- theano/gof/graph.py
- theano/gof/opt.py
- theano/gof/tests/test_graph.py
- theano/gof/tests/test_link.py
- theano/sparse/tests/test_basic.py
- theano/tensor/elemwise.py
- theano/tensor/elemwise_cgen.py
- theano/tensor/nnet/tests/test_sigm.py
- theano/tensor/tests/test_opt.py
- theano/tests/test_printing.py
This fixes a minor error generated in docs for #5042 .
> IO_toposort

- theano/tests/breakpoint.py
- theano/tests/diverse_tests.py
- theano/tests/test_2nd_order_grads.py
- theano/tests/test_breakpoint.py
- theano/tests/test_ifelse.py
- theano/tests/test_pickle_unpickle_theano_fn.py
- theano/tests/test_printing.py
- theano/tests/test_rop.py
- theano/tests/unittest_tools.py
Hi,
@nouiz I committed changes for this issue https://github.com/Theano/Theano/issues/4218.
Thank you.
> Updated numpy as np #4218 #5640

- theano/tensor/tests/mlp_test.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_blas.py
- theano/tensor/tests/test_blas_scipy.py
- theano/tensor/tests/test_complex.py
- theano/tensor/tests/test_elemwise.py
- theano/tensor/tests/test_extra_ops.py
- theano/tensor/tests/test_fft.py
- theano/tensor/tests/test_fourier.py
- theano/tensor/tests/test_gc.py
- theano/tensor/tests/test_inc_subtensor.py
- theano/tensor/tests/test_io.py
- theano/tensor/tests/test_keepdims.py
- theano/tensor/tests/test_merge.py
- theano/tensor/tests/test_misc.py
- theano/tensor/tests/test_nlinalg.py
- theano/tensor/tests/test_opt.py
- theano/tensor/tests/test_opt_uncanonicalize.py
- theano/tensor/tests/test_raw_random.py
- theano/tensor/tests/test_shared_randomstreams.py
- theano/tensor/tests/test_sharedvar.py
- theano/tensor/tests/test_slinalg.py
- theano/tensor/tests/test_subtensor.py
- theano/tensor/tests/test_utils.py
Hi,
@nouiz I committed changes for this issue https://github.com/Theano/Theano/issues/4218.
Thank you.
> Updated numpy as np #4218

- theano/gradient.py
- theano/scan_module/scan_utils.py
fix problem introduced in 80d3b56afe15e9ac802957ad31d3d0
fix gh-5753
> Fix opt crash fix and  more information when verify_grad detect an error.

- theano/gpuarray/multinomial.py
- theano/gpuarray/tests/test_gpuarray_multinomial_wo_replacement.pkl
- theano/gpuarray/tests/test_multinomial.py
- theano/sandbox/multinomial.py
- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_multinomial_wo_replacement.py
- theano/sandbox/tests/test_sandbox_multinomial_wo_replacement.pkl
Following instructions by @nouiz from issue #5408.
> MultinomialWOReplacementFromUniform := ChoiceFromUniform

- .travis/travis_install.sh
- theano/compile/function_module.py
- theano/compile/profiling.py
- theano/gof/vm.py
- theano/gpuarray/__init__.py
- theano/gpuarray/blas.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/opt.py
- theano/scalar/basic_scipy.py
- theano/tensor/tests/test_basic.py
fix https://github.com/pymc-devs/pymc3/issues/1939
also add the offset information to the memory profile
> make work Gammaln on the new gpu back-end

- theano/gpuarray/corr3d_gemm.c
- theano/gpuarray/corr_gemm.c
- theano/gpuarray/pool.c
- theano/gpuarray/pool_ave_grad.c
- theano/gpuarray/pool_grad_grad.c
- theano/gpuarray/pool_max_grad.c
- theano/gpuarray/pool_max_rop.c
1. add GLOBAL_MEM
2. remove static_cast<> from OpenCL kernel code
> add GLOBAL_MEM

- theano/gpuarray/tests/test_opt.py
- theano/tensor/basic.py
- theano/tensor/opt.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_opt.py
This optimize more cases.
fix https://github.com/Theano/Theano/issues/5804
> Make opt useless_reshape handle -1

- theano/gpuarray/multinomial.py
- theano/gpuarray/tests/test_multinomial.py
- theano/sandbox/multinomial.py
- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_multinomial_wo_replacement.py
fix https://github.com/Theano/Theano/issues/5408
> replace as ChoiceFromUniform prop

- theano/sparse/basic.py
> fix theano.sparse.mul docs

- theano/tensor/opt.py
- theano/tensor/subtensor.py
- theano/tensor/tests/test_opt.py
> inc to set for zeros

- theano/tensor/nnet/Conv3D.py
- theano/tensor/nnet/ConvGrad3D.py
- theano/tensor/nnet/ConvTransp3D.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/blocksparse.py
- theano/tensor/nnet/bn.py
- theano/tensor/nnet/conv.py
- theano/tensor/nnet/neighbours.py
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/sigm.py
@nouiz 
I have updated the file https://github.com/Theano/Theano/issues/4218.
Thank you.
> Updated numpy as np #4218 

- .travis/travis_install.sh
- theano/tensor/alt_gemm_template.c
- theano/tensor/blas_headers.py
Fix #5810, a memory leak when `blas.ldflags == ''`.
> Fix memory leak

- doc/library/config.txt
- theano/configdefaults.py
- theano/gof/cmodule.py
- theano/gpuarray/__init__.py
This goes with https://github.com/Theano/libgpuarray/pull/335
also fix gh-5731
fix https://github.com/Theano/Theano/issues/4817
> Disk cache option for gpuarray

- theano/gpuarray/basic_ops.py
As it is trying over and over to compile it as source.
Also, start removing generation of binaries from Theano.
> Remove call to GpuKernel_init with binary

- theano/gpuarray/basic_ops.py
- theano/gpuarray/tests/test_basic_ops.py
The tests will be coming up, thought I'd do a pull request to get some feedback before I carry on.
@ReyhaneAskari #2763
> Changes to GpuEye to enable `k` offset parameter.

- theano/configdefaults.py
change default dnn path on windows
include path: CUDA_ROOT\include
library path: CUDA_ROOT\lib\x64
#5776
> change default dnn path on windows

- .jenkins/jenkins_buildbot_nogpp.sh
- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_32bit.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- .jenkins/jenkins_buildbot_python3.sh
- .jenkins/jenkins_buildbot_release_extra.sh
To allow jenkins to clean git repo before each build.
> move buildbot cache outside workspace

- theano/gpuarray/__init__.py
should fix https://github.com/Theano/Theano/issues/5849
> Always import gpuarray.rng_mrg to have its optimizer imported.

- theano/gpuarray/tests/test_rng_mrg.py
- theano/gradient.py
- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
> Setting gradient for MRG_RandomStreams distribution variables to be null

- theano/gpuarray/basic_ops.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_basic_ops.py
- theano/gpuarray/tests/test_blas.py
- theano/gpuarray/tests/test_opt.py
- theano/gpuarray/tests/test_subtensor.py
- theano/gpuarray/tests/test_type.py
- theano/gpuarray/type.py
- theano/tensor/nnet/opt.py
fix https://github.com/Theano/Theano/issues/5864
> fix opt warning in the ifelse lifter

- theano/scalar/basic.py
- theano/tensor/basic.py
- theano/tensor/nnet/tests/test_neighbours.py
- theano/tensor/opt.py
This should fix the crash (floating point exception, core dumped) in the buildbot in DebugMode.
> Fix hard crash when dividing by 0

- theano/gpuarray/tests/config.py
- theano/gpuarray/tests/test_cgpukernelbase.py
> Prevent gpu initialization when not required

- theano/tensor/opt.py
Reported in: [theano-users] Error occurred while refactoring code
> Stop the compilation when we found a negative shape.

- doc/dev_start_guide.txt
Just a small spelling error in the developer docs. 
fix https://github.com/Theano/Theano/issues/5884
> Fixed minor spelling error

- theano/compile/debugmode.py
- theano/scalar/basic.py
This should solve the `InvalidValurError` and `TypeError: __init__() takes at least 3 arguments (2 given)` in the daily DebugMode buildbot.
> Fix more issues in DebugMode

- theano/tensor/slinalg.py
- theano/tensor/tests/test_slinalg.py
The cholesky Op always raises an exception if the matrix is not positive definite. In some cases it can help if it returned nans instead, so that that case can be handled within the theano graph.
This was first implemented in pymc-devs/pymc3#2028
CC @nouiz
> Add on_error option for Cholesky

- doc/library/config.txt
- theano/configdefaults.py
- theano/gpuarray/linalg.py
- theano/gpuarray/magma_inv.c
- theano/gpuarray/magma_linalg.c
- theano/gpuarray/magma_svd.c
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_linalg.py
- theano/tensor/nlinalg.py
- theano/tensor/tests/test_nlinalg.py
Adds magma gpu for computing svd and matrix inverse.
Benchmark results of magma library against lapack on 6 core cpu and Titan X. Results were taken from magma testing suite. Similar performance should be expected for theano.
<a id="orgfc86fbd"></a>
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<colgroup>
<col  class="org-right" />
<col  class="org-right" />
<col  class="org-right" />
</colgroup>
<tbody>
<tr>
<td class="org-right">M</td>
<td class="org-right">CPU time (sec)</td>
<td class="org-right">GPU time (sec)</td>
</tr>
<tr>
<td class="org-right">1088</td>
<td class="org-right">0.1155</td>
<td class="org-right">0.2345</td>
</tr>
<tr>
<td class="org-right">2112</td>
<td class="org-right">0.5797</td>
<td class="org-right">0.5252</td>
</tr>
<tr>
<td …
> Add magma gpu svd and matrix inverse

- theano/gpuarray/subtensor.py
- theano/tensor/subtensor.py
- theano/tensor/tests/test_subtensor.py
> [BUG,CRASH] Fix crash in GPU advanced indexing with no arrays

- .jenkins/jenkins_buildbot_nogpp.sh
- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- .jenkins/jenkins_buildbot_python3.sh
- .jenkins/jenkins_buildbot_release_extra.sh
- doc/library/config.txt
- theano/configdefaults.py
- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
Remove incorrect case in `local_adv_sub1_adv_inc_sub1`.
Fix #5919
> Remove bug in optimization

- theano/gof/cmodule.py
I read from #5887 that this simple fix is acceptable.
> BUG: fix bytes/string concat error, closes #5887

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
> Split elemwise addmul

- theano/configdefaults.py
- theano/tensor/opt.py
Addresses @nouiz's comments on #5921.
> Mention duplicated values in warning messages.

- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
The FAST_COMPILE buildbot exposes a few ops that don't have perform methods:
http://darjeeling.iro.umontreal.ca:8080/job/Theano_buildbot_python2/168/testReport/
> add gpuarray to python2 buildbot

- theano/gpuarray/dnn.py
After further tests (reported in comment https://github.com/Theano/Theano/issues/5143#issuecomment-300886934 ), it seems that convolution gradient with respect to weights may fail only for floatX=float32 arrays with old cuDNN versions. So, This PR updates the warnings conditions:
- Show warnings only if floatX==float32.
- Show warnings only for cuDNN prior to v6.
@nouiz @lamblin
> (small update) Add restrictions to warning messages condition in GpuDnnConvGradW

- theano/configdefaults.py
> Give a good error when people use device=gpu

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_blas.py
- theano/gpuarray/tests/test_opt.py
This should be merged only after https://github.com/Theano/libgpuarray/pull/436
It should fix #5730 completely.
> Test for fix in libgpuarray, plus fix in batched_dot opt

- theano/tensor/nnet/corr.py
While working on gpuarray DNN convolutions, I am trying to reduce C code for other ops that may be used by related tests. Here I wrap op params for **`theano.tensor.nnet.corr.BaseCorrMM`** and sub-classes (I had already done it for Corr**3d**MM in a previous PR).
@nouiz not sure if this could answer your previous question about Corr**3d**MM, but I have run a simple benchmark to compare execution time before and after using op params.
Benchmark:
```bash
#!/usr/bin/env bash
git checkout master
theano-cache purge
nosetests -xvs theano/tensor/nnet/tests/test_corr.py > corr-before.log 2>&1
theano-cache list > list-corr-before.log
git checkout op-params-tensor-corr2d
theano-cache purge
nosetests -xvs theano/tensor/nnet/tests/test_corr.py > corr-after.log 2>&1
theano-cache list > …
```
> Wrap Op params for theano.tensor.nnet.corr.BaseCorrMM and sub-classes.

- theano/compile/builders.py
- theano/compile/tests/test_builders.py
- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
> crash fix and opt warning fix(make opt apply)

- theano/gpuarray/extra_ops.py
This should work for CUDA, not for OpenCL but I'm not even sure this Op supported OpenCL in the first place.
> Do not forget offset in GpuCumOp

- theano/gpuarray/extra_ops.py
> Correctly handle offset in GpuCumOp

- theano/tensor/signal/pool.py
added an example to make it easy
> added description to strides in pools

- .jenkins/docker_cuda_theano/Dockerfile
- .jenkins/jenkins_pretest.sh
- .jenkins/jenkins_test1.sh
- .jenkins/jenkins_test2.sh
Dockerfile to create docker container for buildbots.
> dockerfile for jenkins buildbot

- theano/tensor/type.py
[Issue #5978](https://github.com/Theano/Theano/issues/5978)
fix gh-5978
> Fix arguments order in register_specify_shape_c_code of tensor/type.py

- doc/optimizations.txt
- doc/tutorial/modes.txt
- theano/compile/mode.py
- theano/configdefaults.py
> Doc tradeoff comp run

- theano/tensor/basic.py
- theano/tensor/utils.py
> Function that check the axes

- doc/index.txt
> Fix link to 2014 presentation

- theano/gpuarray/nnet.py
- theano/gpuarray/opt.py
Only float32 is working now on OpenCL.
I can't test on CUDA. Can anyone test this on CUDA?
> Port Softmax kernel to OpenCL

- theano/tensor/basic.py
- theano/tensor/opt.py
- theano/tensor/tests/test_opt.py
> Fix issue in optimizations with bitwise operations

- theano/compile/nanguardmode.py
- theano/compile/tests/test_nanguardmode.py
- theano/gpuarray/tests/test_misc.py
- theano/scalar/basic.py
> [ENH] Speed up nanguardmode by not checking *int* dtype

- theano/gpuarray/neighbours.py
- theano/tensor/nnet/neighbours.py
- theano/tensor/nnet/tests/test_neighbours.py
> Added mode 'half' to Images2Neibs. Tests pass.

- doc/library/config.txt
- theano/configdefaults.py
By default, all algorithms supported in last cuDNN version (v6020) are included.
@lamblin @abergeron @nouiz
> Update documentation and config flags about supported cuDNN algorithms.

- theano/gpuarray/subtensor.py
- theano/tensor/subtensor.py
instead of segfaulting like a barbarian.
Also add a couple of exceptions before failures.
> Fail if output memory not allocated

- theano/gpuarray/basic_ops.py
- theano/gpuarray/corr3d_gemm.c
- theano/gpuarray/corr_gemm.c
- theano/gpuarray/multinomial.py
- theano/gpuarray/pool.c
- theano/gpuarray/pool_ave_grad.c
- theano/gpuarray/pool_grad_grad.c
- theano/gpuarray/pool_max_grad.c
- theano/gpuarray/pool_max_rop.c
- theano/gpuarray/rng_mrg.py
- theano/gpuarray/tests/tstgpueye.c
> Fix parameter types in ave_pool kernels, remove static_cast, add GLOBAL_MEM

- theano/tensor/nnet/tests/test_neighbours.py
This should speed up the FAST_COMPILE buildbot
> Use FAST_RUN for reference version.

- .jenkins/jenkins_buildbot_python2.sh
- .jenkins/jenkins_buildbot_python2_32bit.sh
- .jenkins/jenkins_buildbot_python2_debug.sh
- .jenkins/jenkins_buildbot_python3.sh
Change buildbot scripts with more detailed test suite names, to distinguish in jenkins pipelines.
[New pipeline buildbot here](http://earlgrey.iro.umontreal.ca:8080/job/Theano_buildbot/)
> Buildbot testsuite names

- theano/tensor/nlinalg.py
- theano/tensor/tests/test_nlinalg.py
This provides a gradient for the matrix pseudoinverse MatrixPinv (see #5851).
> Gradient for matrix pseudoinverse

- theano/gof/cc.py
- theano/tensor/blas.py
- theano/tensor/blas_c.py
- theano/tensor/signal/pool.py
They seem to slow down tests with empty cache.
> Params for Gemm, CGer, CGemv

- theano/gpuarray/blas.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_blas.py
This requires https://github.com/Theano/libgpuarray/pull/447
> Enable float16 for GpuGemmBatch.

- .travis.yml
- .travis/travis_install.sh
- doc/dev_start_guide.txt
- doc/faq.txt
- doc/requirements.inc
- setup.py
- theano/compile/profiling.py
Also enable nosetests profile of tests
fix https://github.com/Theano/Theano/issues/4507
> Bump min Python version to 3.4 (fix slowness travis in Python 3.3)

- .jenkins/jenkins_buildbot_windows.bat
- theano/gpuarray/tests/test_type.py
Pending [test run on jenkins](http://earlgrey.iro.umontreal.ca:8080/job/Theano_buildbot_win/50/).
> add windows buildbot

- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
This would break at compilation because cuda did not support it.
> Add support for atomic{Exch,Add} on long longs.

- theano/compile/debugmode.py
- theano/compile/function_module.py
- theano/compile/mode.py
- theano/tensor/basic.py
- theano/tensor/nnet/tests/test_nnet.py
Regarding https://github.com/Theano/Theano/issues/6033.  I didn't completely understand the 3rd point. I don't need to change the place of the OutputGuard class, right? Just change the mechanism somehow that we would see a failure when outputguard got inserted successfully?
Do we want to benchmark this?
> Remove output guard

- theano/gpuarray/basic_ops.py
- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_subtensor.py
- `theano/gpuarray/opt.py` added optimisation to include new op
- `theano/gpuarray/subtensor.py` added op
- `theano/gpuarray/tests/test_subtensor.py` added simple test case
#930 @nouiz making a pull request for initial comments, it's still incomplete, but I just want to check if I'm on the right track.
> Implementing `GpuAdvancedIncSubtensor`

- theano/tensor/nnet/bn.py
- theano/tensor/nnet/tests/test_bn.py
This adds a `grad` method for `AbstractBatchNormTrainGrad` (see #5811).
> Implement grad for AbstractBatchNormTrainGrad

- theano/tensor/tests/test_blas.py
- theano/tests/test_flake8.py
> Flake8 for test_blas.py

- .jenkins/jenkins_pr_mac.sh
> pr mac tests

- theano/gpuarray/blas.py
- theano/gpuarray/corr_gemm.c
- theano/gpuarray/dnn.py
- theano/gpuarray/dnn_base.c
- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/corr_gemm.c
- theano/tensor/nnet/opt.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
Continues work from https://github.com/Theano/Theano/pull/5973
Related to https://github.com/Theano/Theano/issues/5621
> Implement Grouped Convolutions

- theano/gradient.py
Could someone explain me where does this ... is coming from:
`/home/travis/build/Theano/Theano/theano/gradient.py:docstring of theano.gradient.Rop:21: WARNING: Field list ends without a blank line; unexpected unindent.`
> Added options for `disconnected_outputs` to Rop.

- theano/scan_module/scan_op.py
- theano/scan_module/tests/test_scan.py
Fixes #5439
Still work in progress. I made a few changes. There is one test failing: `test_grad_multiple_outs_some_truncate`.
I will investigate it.
> Correct gradient of scan until.

- doc/library/gradient.txt
- theano/gradient.py
- theano/tensor/slinalg.py
Here's the PR I mentioned in #6156.
> Docstring improvements

- theano/gpuarray/blas.py
- theano/gpuarray/tests/test_blas.py
> Fix strides when using dot inside gemv

- theano/gpuarray/subtensor.py
- theano/tensor/tests/test_subtensor.py
Fix the logic for axes reordering.
Fix #6152.
> Fix for GpuAdvancedIndexing

- theano/gpuarray/neighbours.py
- theano/gpuarray/opt.py
- theano/tensor/slinalg.py
Added convenience function for `solve_symmetric`. 
Added correct handling of `lower_triangular` and `upper_triangular` in the GpuSolve Operator.
Moved the Op lifter for Images2Neibs in `opt.py` such that it is included in the optimisation passes. Closes #6158
> Small issues fixed.

- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
- theano/gpuarray/tests/config.py
- Skip tests when the GPU could not be initialized
- Stop using arithmetic on void pointers
> Fix some problems with the GPU

- theano/gpuarray/basic_ops.py
> (small improvement) Remove Python loop from GpuContiguous's C code.

- doc/library/tensor/nnet/nnet.txt
- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/nnet.py
- theano/tensor/nnet/tests/test_nnet.py
[Self-Normalizing Neural Networks](https://arxiv.org/abs/1706.02515)
> Scaled Exponential Linear Unit (SELU) activation

- .jenkins/jenkins_buildbot_mac.sh
- .jenkins/jenkins_buildbot_windows.bat
- .jenkins/jenkins_pr_mac.sh
Should pass without errors once #6147 is merged.
> Jenkins mac buildbot

- theano/gpuarray/blas.py
this solves #6136 
@notoraptor
> uses inplace as op params for GpuGer, GpuGemm, GpuGemmBatch and GpuGemv

- theano/scalar/basic.py
> Forward test value in clone_float32

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_subtensor.py
> Added lifter optimizations for AllocDiag and ExtractDiag

- theano/gof/op.py
- theano/gpuarray/dnn_fwd.c
- theano/gpuarray/dnn_gi.c
- theano/gpuarray/dnn_gw.c
Also:
- Fix docstring for c_init_code_struct.
- Update support_code_struct for dnn_gi ( try to fix #6157 based on comment https://github.com/Theano/Theano/issues/6157#issuecomment-316088272 ).
Should I add any kind of tests ? @lamblin @abergeron .
> Add DEBUG messages into cuDNN conv codes.

- theano/gpuarray/basic_ops.py
- theano/tensor/basic.py
> using op params for Reshape ops

- doc/library/config.txt
- theano/compile/mode.py
- theano/configdefaults.py
- theano/gof/__init__.py
- theano/gof/opt.py
Regarding https://github.com/Theano/Theano/issues/6133, this PR checks which optimizations have empty stack traces. The last step for this ticket is to add a dummy value for the empty stack traces.
> Fix stack trace

- theano/compile/function.py
- theano/compile/function_module.py
- theano/scan_module/scan_utils.py
Follow up for https://github.com/Theano/Theano/pull/4982
> Fix the copy for aliased function arguments

- theano/gpuarray/basic_ops.py
> Remove traces of kernel pre-compilation.

- theano/tensor/slinalg.py
Addresses #5426 for the slinalg.py ops.
> Changed grad to L_op for cholesky and solve ops

- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/tests/test_subtensor.py
- disable lifter for AdvancedIncSubtensor (see #6144)
- update tests to execute more on GPU
> Updates in GPU indexing

- theano/gpuarray/tests/test_linalg.py
This PR should fix magma-related inplace tests that fail in DEBUG_MODE: http://earlgrey.iro.umontreal.ca:8080/job/Theano_buildbot/45/testReport/
@nouiz @slefrancois
> Fix magma-related inplace tests that fail in DEBUG_MODE

- theano/configdefaults.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/blas.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/multinomial.py
- theano/gpuarray/neighbours.py
- theano/gpuarray/nnet.py
- theano/gpuarray/reduction.py
This PR is intended to fix #6249 . I think these changes won't be included in the next release, but we can start working on it!
Let's see if all Jenkins tests pass.
> Remove config.gpuarray.sync from Theano code.

- theano/scan_module/scan_op.py
Fix gh-6268. 
but we do theano.function(..., profile=True)
> [CRASH] Crash fix when we don't do scan(..., profile=True)

- theano/gpuarray/basic_ops.py
- theano/tensor/basic.py
> Alloc ops params

- theano/compile/debugmode.py
- theano/compile/function.py
- theano/compile/function_module.py
- theano/compile/mode.py
- theano/compile/tests/test_function_module.py
- theano/configdefaults.py
should fix https://github.com/Theano/Theano/issues/5736
> Make sure to pickle all attribute of Function (and FunctionMaker)

- .mailmap
- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/conf.py
- doc/index.txt
- doc/install_generic.inc
- doc/introduction.txt
- setup.py
This PR prepares release **`0.10.0beta1`**.
NB: I have not updated the `Vision State` section into `Theano/doc/introduction.txt`.
@nouiz
> Prepare beta release 0.10.0beta1.

- theano/gpuarray/basic_ops.py
- theano/tensor/basic.py
- theano/tensor/opt_uncanonicalize.py
- theano/tensor/tests/test_opt_uncanonicalize.py
fix https://github.com/Theano/Theano/issues/6287
> [BUG] Fix gh-6287 and a regression introduced in gh-6218

- requirement-rtd.txt
Pick changes from #6283 related to `requirement-rtd.txt`.
@nouiz
> (small fix) fix requirement-rtd

- doc/library/config.txt
- theano/configdefaults.py
- theano/gof/opt.py
- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
related to https://github.com/Theano/Theano/issues/2072
Task list:
> Implement Meta-optimizer on new backend

- doc/faq.txt
- doc/tutorial/modes.txt
- theano/compile/debugmode.py
- theano/compile/function_module.py
- theano/compile/ops.py
- theano/configdefaults.py
- theano/gof/destroyhandler.py
- theano/gof/tests/test_destroyhandler.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_linalg.py
- theano/gpuarray/tests/test_opt.py
- theano/scan_module/tests/test_scan.py
- theano/sparse/tests/test_basic.py
- theano/tensor/nnet/tests/test_nnet.py
- theano/tensor/nnet/tests/test_opt.py
- theano/tensor/opt.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_blas.py
- theano/tensor/tests/test_opt.py
- theano/tensor/tests/test_sharedvar.py
- theano/tests/unittest_tools.py
Issue #5976. Supervisor class is kept but we added a has_destroyers attribute to fgraph, but some tests regarding dumping the pickle failed because a new attribute was added to the fgraph. I changed it like this : 
```python
fgraph.destroyers = [get_destroyers_of, has_destroyers]
```
@nouiz  what do you suggest?
fix https://github.com/Theano/Theano/issues/6230
> New destroy handler

- doc/library/tensor/basic.txt
- theano/gpuarray/opt.py
- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/subtensor.py
- theano/tensor/tests/test_subtensor.py
- theano/tensor/var.py
This would be the easy way of adding support for boolean indexing, as suggested in #5192. It passes the simple tests, but it's not unlikely that there are edge cases that I didn't consider.
> Add support for boolean indexing

- theano/gpuarray/blas.py
- theano/gpuarray/c_code/corr3d_gemm.c
- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/gpuarray/tests/test_gemmcorr3d.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/c_code/corr3d_gemm.c
- theano/tensor/nnet/corr3d.py
- theano/tensor/nnet/opt.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
- theano/tensor/nnet/tests/test_corr3d.py
Related to https://github.com/Theano/Theano/issues/5621
Tasks:
> 3D Grouped Convolutions

- doc/library/tensor/nnet/conv.txt
- theano/gpuarray/opt.py
- theano/tensor/nnet/conv.py
fix https://github.com/Theano/Theano/issues/5047
this also include a fix to the optimization tag.
> Update conv doc.

- theano/gpuarray/ctc.py
- theano/tensor/nnet/ctc.py
Try to fix #6304 .
also fix gh-6314
@nouiz
> Add g++ "-WL,-rpath" argument for CTC ops.

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
I added a simple function theano.tensor.cov using existing theano functions so that it may run on a GPU. This is is modeled after np.cov but matches only one of it's function signatures.
These guys helped me figure this out!
Olexa Bilaniuk @obilaniu
Zhouhan Lin @hantek
> Add covariance matrix function theano.tensor.cov

- theano/compile/debugmode.py
- theano/compile/mode.py
- theano/compile/tests/test_function_module.py
- theano/configdefaults.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
- theano/scalar/basic.py
- theano/scalar/basic_scipy.py
- theano/tensor/nnet/tests/test_ctc.py
- theano/tensor/tests/test_basic.py
Also allow the flag mode to be an instance of Mode.
> Fix test in the daily buildbot and make sure to don't loose the current linker.

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/gpuarray/tests/test_gemmcorr3d.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
- theano/tensor/nnet/tests/test_corr3d.py
There seems to be an optimization error for cudnn. Thanks @gvtulder  for pointing that out
> test optimization in grouped convolution

- theano/gof/cc.py
- theano/gpuarray/c_code/dnn_fwd.c
- theano/gpuarray/c_code/dnn_gi.c
- theano/gpuarray/c_code/dnn_gw.c
> Try to fix segmentation fault related to last updates in cuDNN conv codes.

- theano/compile/function_module.py
- theano/compile/tests/test_function_module.py
Shared variable was not triggering the input alias check and that was right.
> Fix Theano function overhead increase due to gh-6275. 

- theano/gpuarray/blas.py
- theano/gpuarray/c_code/corr_gemm.c
- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_gemmcorr.py
- theano/tensor/nnet/__init__.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/nnet/c_code/corr_gemm.c
- theano/tensor/nnet/corr.py
- theano/tensor/nnet/opt.py
- theano/tensor/nnet/tests/test_abstract_conv.py
- theano/tensor/nnet/tests/test_corr.py
Continues work from #6007. Related to #5620.
Old PR was rebased since the grouped convolution was merged first. I thought this would be neater to continue discussion, seeing as the old one was already rather messy.
> Implement Unshared Convolution

- theano/compile/function_module.py
Should be faster, in particular on function without updates.
> Loop over the updates and not all inputs.

- theano/gof/graph.py
> Flag to disable pickling test values

- theano/gpuarray/c_code/dnn_fwd.c
- theano/gpuarray/c_code/dnn_gi.c
- theano/gpuarray/c_code/dnn_gw.c
While investigating WrongValue errors for tests script in #5932 , I found some errors that occur only for timed runtime algorithms (time_once or time_on_shape_change) and only if beta is not null. This is a code to reproduce the problem:
**File `test_beta.py`**:
```python
from __future__ import absolute_import, print_function, division
import theano
import numpy as np
import theano.tests.unittest_tools as utt
from theano.compile.ops import shape_i_op
from theano.gpuarray.basic_ops import infer_context_name, as_gpuarray_variable, gpu_contiguous, GpuAllocEmpty
from theano.gpuarray.dnn import GpuDnnConvDesc, GpuDnnConv, version, get_precision
from theano.gpuarray.tests.config import mode_with_gpu, ref_cast
from theano.tensor.nnet.abstract_conv import get_conv_output_shape, assert_conv_shape …
```
> Fix error related to cuDNN runtime timed algos when beta is not null.

- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
addresses https://github.com/Theano/Theano/issues/6360
> fix 3d optimizers for grouped convolutions and add more test cases

- theano/configdefaults.py
- theano/gpuarray/tests/test_dnn.py
Partially solves #6365 (still need to add fallback code for [sd]gemv, and probably [sd]dot too).
> Fix MKL linking on Windows.

- conda/meta.yaml
The version is at 0.10.0beta1 for now, but a bump is easy
> Add conda recipe

- theano/sandbox/rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
Allow manual work around #6337
> MRG distribution, add a target parameter

- theano/gof/graph.py
- theano/gof/opt.py
- theano/gpuarray/basic_ops.py
- theano/gpuarray/blas.py
- theano/gpuarray/dnn.py
- theano/gpuarray/opt.py
- theano/gpuarray/opt_util.py
- theano/gpuarray/tests/test_opt.py
- theano/tensor/blas.py
- theano/tensor/opt_uncanonicalize.py
> gpuarray: keep stack trace

- doc/library/gpuarray/dnn.txt
- doc/tutorial/using_gpu.txt
- theano/gpuarray/dnn.py
> Add some documentation to RNNBlock.

- theano/gpuarray/__init__.py
Replace https://github.com/Theano/libgpuarray/pull/515 .
@nouiz
> Fix pygpu version detection.

- .mailmap
- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/conf.py
- doc/index.txt
- doc/install_generic.inc
- doc/introduction.txt
- setup.py
@nouiz 
- Date set to August 25th (tomorrow).
- Vision/State unchanged.
- NB: Check if cuDNN news are convenient !
> Prepare release 0.10.0beta2

- theano/gpuarray/tests/test_opt.py
Related to https://github.com/Theano/Theano/issues/6360
> Improve tests for meta-optimizer

- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_opt.py
A follow up for https://github.com/Theano/Theano/pull/5688. Still in progress.
> Gpu stack follow up

- theano/gof/tests/c_code/test_cenum.h
- theano/gof/tests/test_types.py
- theano/gof/type.py
> Fix unit tests for CEnumType.

- theano/gpuarray/dnn.py
- theano/gpuarray/rng_mrg.py
- theano/gpuarray/tests/config.py
- theano/gpuarray/tests/test_rng_mrg.py
- theano/sandbox/tests/test_rng_mrg.py
test MRG random stream with device=cuda and target=cpu, shared variable + computation in a real model stay on CPU. fix #6382
> test MRG random stream with device=cuda and target=cpu

- theano/tensor/basic.py
- theano/tensor/nlinalg.py
- theano/tensor/tests/test_nlinalg.py
Pull request for issue #5633 @nouiz @ReyhaneAskari
> ExtractDiag cleanup #5633

- theano/gpuarray/subtensor.py
- theano/tensor/tests/test_subtensor.py
This needs E_PADSHAPE to be present in libgpuarray.
> Use E_PADSHAPE flag in GPU Incsubtensor

- theano/gpuarray/dnn.py
fix https://github.com/Theano/Theano/issues/5109
> add decsription for rnnblock

- theano/gradient.py
- theano/tests/test_gradient.py
Related to issue #5797 .
I've modified theano/gradient.py and theano/tests/test_gradient.py
> R_op for ZeroGrad + tests

- .appveyor.yml
- .circleci/config.yml
- conda/meta.yaml
noarch: python is broken according to continuum so do it the hard way with multiple packages.
> Fix conda package builds

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> Fix min function to work with uint* and bool

- .jenkins/jenkins_pr_core.sh
- .jenkins/jenkins_pr_gpu.sh
- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/index.txt
- theano/tensor/tests/test_mpi.py
> Prepare release 0.10.0beta3

- theano/gof/opt.py
- theano/gpuarray/tests/test_type.py
- theano/tensor/opt.py
- theano/tests/test_gradient.py
> Remove ViewOp subclass during optimization

- .mailmap
- NEWS.txt
- NEWS_DEV.txt
@nouiz
Notes:
- I wait for this PR to be merged before uploading PyPI package, to have news up to date.
- conda packages are already online and then will not have news up to date.
> Update news to include topk ops.

- theano/compile/builders.py
- theano/compile/tests/test_builders.py
#5426 
- Interface is backward compatible
- added a test case
> L_op for OpFromGraph

- theano/gpuarray/subtensor.py
- theano/gpuarray/tests/test_subtensor.py
- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
#5633 @ReyhaneAskari 
Starting off the pull request.
> Generalised AllocDiag for more than 2D input

- theano/tensor/basic.py
- theano/tensor/tests/test_basic.py
> correct gradient for ARange

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
@nouiz @abergeron @lamblin 
fix https://github.com/Theano/Theano/issues/6435
> Disallow float16 precision for convolution gradients functions.

- theano/scalar/basic.py
- theano/tensor/opt.py
- theano/tensor/tests/test_basic.py
- theano/tensor/tests/test_opt.py
Fix gh-6470. But also enable more optimization by using a real cast instead of mimiking one.
> Minimum maximum gradient fix

- .travis.yml
- doc/internal/how_to_release.txt
- setup.py
- theano/__init__.py
- theano/gof/cmodule.py
- theano/gpuarray/__init__.py
- theano/gpuarray/dnn.py
- theano/version.py
fix https://github.com/Theano/Theano/issues/6465
> Add good user error in corner case that are hard to debug.

- .mailmap
- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/index.txt
- doc/introduction.txt
- theano/version.py
@nouiz 
NB: Vision / State not updated (should we mention here that theano development will be stopped ?).
> Prepare release 0.10.0beta4

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/check_dnn_conv.py
Fix #6486 
@nouiz @lamblin @abergeron
> Refactor dnn conv functions

- theano/gpuarray/dnn.py
- theano/gpuarray/elemwise.py
- theano/gpuarray/opt.py
- theano/gpuarray/tests/test_dnn.py
- theano/gpuarray/tests/test_opt.py
- theano/tensor/tests/test_elemwise.py
Same PR as #6491 but with libgpuarray compiled in `Debug` mode for jenkins tests.
@nouiz @abergeron @lamblin
> Optimize SUM(x^2), SUM(ABS(X)) and MAX(ABS(X)) to cuDNN reduction.

- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/index.txt
- doc/introduction.txt
- theano/version.py
> Prepare release candidate 1.0.0rc1

- HISTORY.txt
- NEWS.txt
- NEWS_DEV.txt
- doc/index.txt
- doc/introduction.txt
- theano/version.py
> Prepare final release 1.0.0

- theano/gpuarray/c_code/topk_common.cuh
- theano/gpuarray/c_code/topk_dense.cu
- theano/gpuarray/c_code/topk_dense_large.cu
- theano/gpuarray/sort.py
- theano/gpuarray/tests/test_sort.py
- theano/tensor/opt.py
- theano/tensor/tests/test_sort.py
Partial fix for #6511 
However, I also found out that GpuTopKOp doesn't have any test.  This should be rectified before we declare this fixed since there might be other problems in the code than just surface compilation errors.
@khaotik You were the one that wrote this, can you also make some tests please?
> Fix compilation of GpuTopKOp

- theano/gpuarray/linalg.py
> Add cuda include path for magma ops

- theano/tensor/nnet/tests/test_bn.py
> Fix function parameters order in test_bn/test_batch_normalization

- doc/introduction.txt
It was just bugging me a little
> Remove awkward language

- theano/tensor/nlinalg.py
Partial is required to make pickling possible. This is required in PyMC3 and [this](https://github.com/pymc-devs/pymc3/pull/2731/) PR in particular.
> Switched lambda to partial in EighGrad

- theano/gpuarray/basic_ops.py
- theano/gpuarray/type.py
This should fix the problems in DEBUG_MODE.
> Add a map of values_approx functions from cpu to gpu.

- theano/gpuarray/type.py
This should fix the new buildbot problem.
> support allow_remove_{inf,nan}

- theano/gof/lazylinker_c.py
Try to help https://github.com/Theano/Theano/issues/6567
> Better error msg

- .mailmap
- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
- theano/tests/test_printing.py
fix gh-6578
Note, this only fix variable names. So there is no computation changes.
> Fix scan names of variables.

- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
> Fix MissingInputError when scan use hidden variable to calculate condition

- theano/scan_module/scan.py
- theano/scan_module/tests/test_scan.py
> Fix one step scan use wrong seq slice bug

- theano/gpuarray/dnn.py
- theano/gpuarray/tests/test_dnn.py
> Fix for mixed-dtype input in dnn_conv

- theano/configdefaults.py
fix https://github.com/Theano/Theano/issues/6599
> On windows, check for intel OpenMP if gnu failed for mkl

- theano/gof/compilelock.py
> Fix lock for python 3

- theano/sparse/basic.py
- theano/sparse/tests/test_basic.py
Supersedes https://github.com/Theano/Theano/pull/6522
> Broadcast sparse dot

- theano/scalar/basic_scipy.py
- theano/scalar/c_code/gamma.c
- theano/tensor/basic.py
> WIP: Add gamma family functions from SciPy with C code for GPU

- theano/gpuarray/basic_ops.py
This should fix test in the daily buildbot
> GpuContiguous need a perform method.

- theano/tensor/nnet/abstract_conv.py
This is my promised fix for [this](https://github.com/Theano/Theano/pull/6665#issuecomment-447538668).
> Fixed shape error of frac bilinear upsample

- doc/library/config.txt
- theano/configdefaults.py
Docs update that closes #6677.
> Update the documentation on gpuarray.sched

- theano/tensor/subtensor.py
Fix another one of the numpy indexing warnings
> Fix subtensor numpy warning

- theano/compile/profiling.py
> Fix simple typo: varible->size -> variable->size

- theano/gof/cmodule.py
Fixes gh-4926.
We encountered gh-4926 at conda-forge in https://github.com/conda-forge/theano-feedstock/pull/30.
The system's `g++` from Mingw-w64 failed with `error: '::hypot' has not been declared`:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=109907&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0d1d4714-3221-52cd-cfdb-f62a891e036b&l=1945
```
Exception: Compilation failed (return status=1): In file included from C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/math.h:36,
from D:\bld\theano_1578673727137\_test_env\include/pyport.h:194,
from D:\bld\theano_1578673727137\_test_env\include/Python.h:53,
from C:\Users\VssAdministrator\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6 …
```
> Counteract hypot redefinition for old Python versions

- theano/compat/__init__.py
- theano/compile/nanguardmode.py
- theano/misc/frozendict.py
- theano/scalar/basic.py
- theano/tensor/nnet/abstract_conv.py
- theano/tensor/subtensor.py
See https://github.com/Theano/Theano/pull/6664#issuecomment-581845517
> Various Python 3.9 related import changes

- theano/compile/mode.py
- theano/tensor/nnet/bn.py
> flake8 code style fixes

- .travis.yml
Hopefully, this will fix travis.
> Use conda-forge for Python 3.4 to fix travis
